// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"market-backend/internal/alarm"
	"market-backend/internal/conf"
	"market-backend/internal/data"
	"market-backend/internal/server"
	"market-backend/internal/service/http_api"
	"market-backend/internal/service/sse_api"
	"market-backend/internal/sse"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, custom *conf.Custom, logger log.Logger) (*kratos.App, func(), error) {
	dataData := data.NewData(confData, custom, logger)
	httpApiService := http_api.NewHttpApiService(dataData, confData, custom, logger)
	connectionManager := sse.NewConnectionManager(dataData, logger)
	sseApiService := sse_api.NewSseApiService(dataData, confData, custom, logger, connectionManager)
	larkAlarm := alarm.NewLarkAlarm(custom, logger)
	httpServer := server.NewHTTPServer(confServer, custom, confData, httpApiService, sseApiService, logger, dataData, larkAlarm)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
