// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Custom        *Custom                `protobuf:"bytes,3,opt,name=custom,proto3" json:"custom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetCustom() *Custom {
	if x != nil {
		return x.Custom
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *Server_GRPC           `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postgresql    *Data_PostgresqlData   `protobuf:"bytes,1,opt,name=postgresql,proto3" json:"postgresql,omitempty"`
	Redis         *Data_RedisData        `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Alchemy       *Data_Alchemy          `protobuf:"bytes,3,opt,name=alchemy,proto3" json:"alchemy,omitempty"`
	S3            *Data_S3               `protobuf:"bytes,4,opt,name=s3,proto3" json:"s3,omitempty"`
	Rpc           *Data_Rpc              `protobuf:"bytes,5,opt,name=rpc,proto3" json:"rpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetPostgresql() *Data_PostgresqlData {
	if x != nil {
		return x.Postgresql
	}
	return nil
}

func (x *Data) GetRedis() *Data_RedisData {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetAlchemy() *Data_Alchemy {
	if x != nil {
		return x.Alchemy
	}
	return nil
}

func (x *Data) GetS3() *Data_S3 {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *Data) GetRpc() *Data_Rpc {
	if x != nil {
		return x.Rpc
	}
	return nil
}

type Custom struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AssetTokens      *Custom_AssetTokens    `protobuf:"bytes,1,opt,name=asset_tokens,json=assetTokens,proto3" json:"asset_tokens,omitempty"`
	NewUserPoints    uint32                 `protobuf:"varint,2,opt,name=new_user_points,json=newUserPoints,proto3" json:"new_user_points,omitempty"`
	Chain            string                 `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`
	LarkWebhookKey   string                 `protobuf:"bytes,4,opt,name=lark_webhook_key,json=larkWebhookKey,proto3" json:"lark_webhook_key,omitempty"`
	MinVolume        uint32                 `protobuf:"varint,5,opt,name=min_volume,json=minVolume,proto3" json:"min_volume,omitempty"`
	MaxDeadlineHours uint32                 `protobuf:"varint,6,opt,name=max_deadline_hours,json=maxDeadlineHours,proto3" json:"max_deadline_hours,omitempty"`
	LarkEnabled      bool                   `protobuf:"varint,7,opt,name=lark_enabled,json=larkEnabled,proto3" json:"lark_enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Custom) Reset() {
	*x = Custom{}
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Custom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom) ProtoMessage() {}

func (x *Custom) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom.ProtoReflect.Descriptor instead.
func (*Custom) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Custom) GetAssetTokens() *Custom_AssetTokens {
	if x != nil {
		return x.AssetTokens
	}
	return nil
}

func (x *Custom) GetNewUserPoints() uint32 {
	if x != nil {
		return x.NewUserPoints
	}
	return 0
}

func (x *Custom) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Custom) GetLarkWebhookKey() string {
	if x != nil {
		return x.LarkWebhookKey
	}
	return ""
}

func (x *Custom) GetMinVolume() uint32 {
	if x != nil {
		return x.MinVolume
	}
	return 0
}

func (x *Custom) GetMaxDeadlineHours() uint32 {
	if x != nil {
		return x.MaxDeadlineHours
	}
	return 0
}

func (x *Custom) GetLarkEnabled() bool {
	if x != nil {
		return x.LarkEnabled
	}
	return false
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_PostgresqlData struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Usercenter    *Data_PostgresqlData_Postgresql `protobuf:"bytes,1,opt,name=usercenter,proto3" json:"usercenter,omitempty"`
	Marketcenter  *Data_PostgresqlData_Postgresql `protobuf:"bytes,2,opt,name=marketcenter,proto3" json:"marketcenter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_PostgresqlData) Reset() {
	*x = Data_PostgresqlData{}
	mi := &file_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_PostgresqlData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_PostgresqlData) ProtoMessage() {}

func (x *Data_PostgresqlData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_PostgresqlData.ProtoReflect.Descriptor instead.
func (*Data_PostgresqlData) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_PostgresqlData) GetUsercenter() *Data_PostgresqlData_Postgresql {
	if x != nil {
		return x.Usercenter
	}
	return nil
}

func (x *Data_PostgresqlData) GetMarketcenter() *Data_PostgresqlData_Postgresql {
	if x != nil {
		return x.Marketcenter
	}
	return nil
}

type Data_RedisData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usercenter    *Data_RedisData_Redis  `protobuf:"bytes,1,opt,name=usercenter,proto3" json:"usercenter,omitempty"`
	Marketcenter  *Data_RedisData_Redis  `protobuf:"bytes,2,opt,name=marketcenter,proto3" json:"marketcenter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_RedisData) Reset() {
	*x = Data_RedisData{}
	mi := &file_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_RedisData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_RedisData) ProtoMessage() {}

func (x *Data_RedisData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_RedisData.ProtoReflect.Descriptor instead.
func (*Data_RedisData) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_RedisData) GetUsercenter() *Data_RedisData_Redis {
	if x != nil {
		return x.Usercenter
	}
	return nil
}

func (x *Data_RedisData) GetMarketcenter() *Data_RedisData_Redis {
	if x != nil {
		return x.Marketcenter
	}
	return nil
}

type Data_Alchemy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ApiKey            string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Network           string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	ChainId           uint64                 `protobuf:"varint,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	PolicyId          string                 `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	EntrypointAddress string                 `protobuf:"bytes,5,opt,name=entrypoint_address,json=entrypointAddress,proto3" json:"entrypoint_address,omitempty"`
	FallbackAddress   string                 `protobuf:"bytes,6,opt,name=fallback_address,json=fallbackAddress,proto3" json:"fallback_address,omitempty"`
	SignTxFromAddress string                 `protobuf:"bytes,7,opt,name=sign_tx_from_address,json=signTxFromAddress,proto3" json:"sign_tx_from_address,omitempty"`
	SignTxPrivateKey  string                 `protobuf:"bytes,8,opt,name=sign_tx_private_key,json=signTxPrivateKey,proto3" json:"sign_tx_private_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Data_Alchemy) Reset() {
	*x = Data_Alchemy{}
	mi := &file_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Alchemy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Alchemy) ProtoMessage() {}

func (x *Data_Alchemy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Alchemy.ProtoReflect.Descriptor instead.
func (*Data_Alchemy) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Data_Alchemy) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Data_Alchemy) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Alchemy) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Data_Alchemy) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *Data_Alchemy) GetEntrypointAddress() string {
	if x != nil {
		return x.EntrypointAddress
	}
	return ""
}

func (x *Data_Alchemy) GetFallbackAddress() string {
	if x != nil {
		return x.FallbackAddress
	}
	return ""
}

func (x *Data_Alchemy) GetSignTxFromAddress() string {
	if x != nil {
		return x.SignTxFromAddress
	}
	return ""
}

func (x *Data_Alchemy) GetSignTxPrivateKey() string {
	if x != nil {
		return x.SignTxPrivateKey
	}
	return ""
}

type Data_S3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     string                 `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	BizBucket     string                 `protobuf:"bytes,3,opt,name=biz_bucket,json=bizBucket,proto3" json:"biz_bucket,omitempty"`
	AdminBucket   string                 `protobuf:"bytes,4,opt,name=admin_bucket,json=adminBucket,proto3" json:"admin_bucket,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	TenantSlug    string                 `protobuf:"bytes,6,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"` // ADR-008: S3 key prefix (default: arb-sepolia-usdc)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_S3) Reset() {
	*x = Data_S3{}
	mi := &file_internal_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_S3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_S3) ProtoMessage() {}

func (x *Data_S3) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_S3.ProtoReflect.Descriptor instead.
func (*Data_S3) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Data_S3) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *Data_S3) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Data_S3) GetBizBucket() string {
	if x != nil {
		return x.BizBucket
	}
	return ""
}

func (x *Data_S3) GetAdminBucket() string {
	if x != nil {
		return x.AdminBucket
	}
	return ""
}

func (x *Data_S3) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Data_S3) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

type Data_Rpc struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RecommendationRpc *Data_Rpc_RpcClient    `protobuf:"bytes,1,opt,name=recommendation_rpc,json=recommendationRpc,proto3" json:"recommendation_rpc,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Data_Rpc) Reset() {
	*x = Data_Rpc{}
	mi := &file_internal_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Rpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Rpc) ProtoMessage() {}

func (x *Data_Rpc) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Rpc.ProtoReflect.Descriptor instead.
func (*Data_Rpc) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 4}
}

func (x *Data_Rpc) GetRecommendationRpc() *Data_Rpc_RpcClient {
	if x != nil {
		return x.RecommendationRpc
	}
	return nil
}

type Data_PostgresqlData_Postgresql struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Dsn             string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	MaxIdleConns    int32                  `protobuf:"varint,2,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	MaxOpenConns    int32                  `protobuf:"varint,3,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	ConnMaxLifetime *durationpb.Duration   `protobuf:"bytes,4,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_PostgresqlData_Postgresql) Reset() {
	*x = Data_PostgresqlData_Postgresql{}
	mi := &file_internal_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_PostgresqlData_Postgresql) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_PostgresqlData_Postgresql) ProtoMessage() {}

func (x *Data_PostgresqlData_Postgresql) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_PostgresqlData_Postgresql.ProtoReflect.Descriptor instead.
func (*Data_PostgresqlData_Postgresql) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Data_PostgresqlData_Postgresql) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Data_PostgresqlData_Postgresql) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Data_PostgresqlData_Postgresql) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_PostgresqlData_Postgresql) GetConnMaxLifetime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return nil
}

type Data_RedisData_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,5,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,6,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	DialTimeout   *durationpb.Duration   `protobuf:"bytes,7,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_RedisData_Redis) Reset() {
	*x = Data_RedisData_Redis{}
	mi := &file_internal_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_RedisData_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_RedisData_Redis) ProtoMessage() {}

func (x *Data_RedisData_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_RedisData_Redis.ProtoReflect.Descriptor instead.
func (*Data_RedisData_Redis) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 1, 0}
}

func (x *Data_RedisData_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_RedisData_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_RedisData_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Data_RedisData_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_RedisData_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_RedisData_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Data_RedisData_Redis) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

type Data_Rpc_RpcClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Rpc_RpcClient) Reset() {
	*x = Data_Rpc_RpcClient{}
	mi := &file_internal_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Rpc_RpcClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Rpc_RpcClient) ProtoMessage() {}

func (x *Data_Rpc_RpcClient) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Rpc_RpcClient.ProtoReflect.Descriptor instead.
func (*Data_Rpc_RpcClient) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 4, 0}
}

func (x *Data_Rpc_RpcClient) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Rpc_RpcClient) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Custom_AssetTokens struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Points        *Custom_AssetTokensToken `protobuf:"bytes,1,opt,name=points,proto3" json:"points,omitempty"`
	Usdc          *Custom_AssetTokensToken `protobuf:"bytes,2,opt,name=usdc,proto3" json:"usdc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Custom_AssetTokens) Reset() {
	*x = Custom_AssetTokens{}
	mi := &file_internal_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Custom_AssetTokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom_AssetTokens) ProtoMessage() {}

func (x *Custom_AssetTokens) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom_AssetTokens.ProtoReflect.Descriptor instead.
func (*Custom_AssetTokens) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Custom_AssetTokens) GetPoints() *Custom_AssetTokensToken {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *Custom_AssetTokens) GetUsdc() *Custom_AssetTokensToken {
	if x != nil {
		return x.Usdc
	}
	return nil
}

type Custom_AssetTokensToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals      uint32                 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Custom_AssetTokensToken) Reset() {
	*x = Custom_AssetTokensToken{}
	mi := &file_internal_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Custom_AssetTokensToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom_AssetTokensToken) ProtoMessage() {}

func (x *Custom_AssetTokensToken) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom_AssetTokensToken.ProtoReflect.Descriptor instead.
func (*Custom_AssetTokensToken) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *Custom_AssetTokensToken) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Custom_AssetTokensToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Custom_AssetTokensToken) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Custom_AssetTokensToken) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

var File_internal_conf_conf_proto protoreflect.FileDescriptor

const file_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x18internal/conf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\x89\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12*\n" +
	"\x06custom\x18\x03 \x01(\v2\x12.kratos.api.CustomR\x06custom\"\xa0\x01\n" +
	"\x06Server\x12+\n" +
	"\x04grpc\x18\x01 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xb3\r\n" +
	"\x04Data\x12?\n" +
	"\n" +
	"postgresql\x18\x01 \x01(\v2\x1f.kratos.api.Data.PostgresqlDataR\n" +
	"postgresql\x120\n" +
	"\x05redis\x18\x02 \x01(\v2\x1a.kratos.api.Data.RedisDataR\x05redis\x122\n" +
	"\aalchemy\x18\x03 \x01(\v2\x18.kratos.api.Data.AlchemyR\aalchemy\x12#\n" +
	"\x02s3\x18\x04 \x01(\v2\x13.kratos.api.Data.S3R\x02s3\x12&\n" +
	"\x03rpc\x18\x05 \x01(\v2\x14.kratos.api.Data.RpcR\x03rpc\x1a\xe0\x02\n" +
	"\x0ePostgresqlData\x12J\n" +
	"\n" +
	"usercenter\x18\x01 \x01(\v2*.kratos.api.Data.PostgresqlData.PostgresqlR\n" +
	"usercenter\x12N\n" +
	"\fmarketcenter\x18\x02 \x01(\v2*.kratos.api.Data.PostgresqlData.PostgresqlR\fmarketcenter\x1a\xb1\x01\n" +
	"\n" +
	"Postgresql\x12\x10\n" +
	"\x03dsn\x18\x01 \x01(\tR\x03dsn\x12$\n" +
	"\x0emax_idle_conns\x18\x02 \x01(\x05R\fmaxIdleConns\x12$\n" +
	"\x0emax_open_conns\x18\x03 \x01(\x05R\fmaxOpenConns\x12E\n" +
	"\x11conn_max_lifetime\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x0fconnMaxLifetime\x1a\xb3\x03\n" +
	"\tRedisData\x12@\n" +
	"\n" +
	"usercenter\x18\x01 \x01(\v2 .kratos.api.Data.RedisData.RedisR\n" +
	"usercenter\x12D\n" +
	"\fmarketcenter\x18\x02 \x01(\v2 .kratos.api.Data.RedisData.RedisR\fmarketcenter\x1a\x9d\x02\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12<\n" +
	"\fread_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12<\n" +
	"\fdial_timeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\x1a\xae\x02\n" +
	"\aAlchemy\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\x04R\achainId\x12\x1b\n" +
	"\tpolicy_id\x18\x04 \x01(\tR\bpolicyId\x12-\n" +
	"\x12entrypoint_address\x18\x05 \x01(\tR\x11entrypointAddress\x12)\n" +
	"\x10fallback_address\x18\x06 \x01(\tR\x0ffallbackAddress\x12/\n" +
	"\x14sign_tx_from_address\x18\a \x01(\tR\x11signTxFromAddress\x12-\n" +
	"\x13sign_tx_private_key\x18\b \x01(\tR\x10signTxPrivateKey\x1a\xbd\x01\n" +
	"\x02S3\x12\x1d\n" +
	"\n" +
	"access_key\x18\x01 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tR\tsecretKey\x12\x1d\n" +
	"\n" +
	"biz_bucket\x18\x03 \x01(\tR\tbizBucket\x12!\n" +
	"\fadmin_bucket\x18\x04 \x01(\tR\vadminBucket\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1f\n" +
	"\vtenant_slug\x18\x06 \x01(\tR\n" +
	"tenantSlug\x1a\xac\x01\n" +
	"\x03Rpc\x12N\n" +
	"\x12recommendation_rpc\x18\x01 \x01(\v2\x1f.kratos.api.Data.Rpc.Rpc_clientR\x11recommendationRpc\x1aU\n" +
	"\n" +
	"Rpc_client\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x96\x04\n" +
	"\x06Custom\x12A\n" +
	"\fasset_tokens\x18\x01 \x01(\v2\x1e.kratos.api.Custom.AssetTokensR\vassetTokens\x12&\n" +
	"\x0fnew_user_points\x18\x02 \x01(\rR\rnewUserPoints\x12\x14\n" +
	"\x05chain\x18\x03 \x01(\tR\x05chain\x12(\n" +
	"\x10lark_webhook_key\x18\x04 \x01(\tR\x0elarkWebhookKey\x12\x1d\n" +
	"\n" +
	"min_volume\x18\x05 \x01(\rR\tminVolume\x12,\n" +
	"\x12max_deadline_hours\x18\x06 \x01(\rR\x10maxDeadlineHours\x12!\n" +
	"\flark_enabled\x18\a \x01(\bR\vlarkEnabled\x1a\xf0\x01\n" +
	"\vAssetTokens\x12<\n" +
	"\x06points\x18\x01 \x01(\v2$.kratos.api.Custom.AssetTokens.tokenR\x06points\x128\n" +
	"\x04usdc\x18\x02 \x01(\v2$.kratos.api.Custom.AssetTokens.tokenR\x04usdc\x1ai\n" +
	"\x05token\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x04 \x01(\rR\bdecimalsB#Z!market-service/internal/conf;confb\x06proto3"

var (
	file_internal_conf_conf_proto_rawDescOnce sync.Once
	file_internal_conf_conf_proto_rawDescData []byte
)

func file_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)))
	})
	return file_internal_conf_conf_proto_rawDescData
}

var file_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),                      // 0: kratos.api.Bootstrap
	(*Server)(nil),                         // 1: kratos.api.Server
	(*Data)(nil),                           // 2: kratos.api.Data
	(*Custom)(nil),                         // 3: kratos.api.Custom
	(*Server_GRPC)(nil),                    // 4: kratos.api.Server.GRPC
	(*Data_PostgresqlData)(nil),            // 5: kratos.api.Data.PostgresqlData
	(*Data_RedisData)(nil),                 // 6: kratos.api.Data.RedisData
	(*Data_Alchemy)(nil),                   // 7: kratos.api.Data.Alchemy
	(*Data_S3)(nil),                        // 8: kratos.api.Data.S3
	(*Data_Rpc)(nil),                       // 9: kratos.api.Data.Rpc
	(*Data_PostgresqlData_Postgresql)(nil), // 10: kratos.api.Data.PostgresqlData.Postgresql
	(*Data_RedisData_Redis)(nil),           // 11: kratos.api.Data.RedisData.Redis
	(*Data_Rpc_RpcClient)(nil),             // 12: kratos.api.Data.Rpc.Rpc_client
	(*Custom_AssetTokens)(nil),             // 13: kratos.api.Custom.AssetTokens
	(*Custom_AssetTokensToken)(nil),        // 14: kratos.api.Custom.AssetTokens.token
	(*durationpb.Duration)(nil),            // 15: google.protobuf.Duration
}
var file_internal_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.custom:type_name -> kratos.api.Custom
	4,  // 3: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	5,  // 4: kratos.api.Data.postgresql:type_name -> kratos.api.Data.PostgresqlData
	6,  // 5: kratos.api.Data.redis:type_name -> kratos.api.Data.RedisData
	7,  // 6: kratos.api.Data.alchemy:type_name -> kratos.api.Data.Alchemy
	8,  // 7: kratos.api.Data.s3:type_name -> kratos.api.Data.S3
	9,  // 8: kratos.api.Data.rpc:type_name -> kratos.api.Data.Rpc
	13, // 9: kratos.api.Custom.asset_tokens:type_name -> kratos.api.Custom.AssetTokens
	15, // 10: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	10, // 11: kratos.api.Data.PostgresqlData.usercenter:type_name -> kratos.api.Data.PostgresqlData.Postgresql
	10, // 12: kratos.api.Data.PostgresqlData.marketcenter:type_name -> kratos.api.Data.PostgresqlData.Postgresql
	11, // 13: kratos.api.Data.RedisData.usercenter:type_name -> kratos.api.Data.RedisData.Redis
	11, // 14: kratos.api.Data.RedisData.marketcenter:type_name -> kratos.api.Data.RedisData.Redis
	12, // 15: kratos.api.Data.Rpc.recommendation_rpc:type_name -> kratos.api.Data.Rpc.Rpc_client
	15, // 16: kratos.api.Data.PostgresqlData.Postgresql.conn_max_lifetime:type_name -> google.protobuf.Duration
	15, // 17: kratos.api.Data.RedisData.Redis.read_timeout:type_name -> google.protobuf.Duration
	15, // 18: kratos.api.Data.RedisData.Redis.write_timeout:type_name -> google.protobuf.Duration
	15, // 19: kratos.api.Data.RedisData.Redis.dial_timeout:type_name -> google.protobuf.Duration
	15, // 20: kratos.api.Data.Rpc.Rpc_client.timeout:type_name -> google.protobuf.Duration
	14, // 21: kratos.api.Custom.AssetTokens.points:type_name -> kratos.api.Custom.AssetTokens.token
	14, // 22: kratos.api.Custom.AssetTokens.usdc:type_name -> kratos.api.Custom.AssetTokens.token
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_internal_conf_conf_proto_init() }
func file_internal_conf_conf_proto_init() {
	if File_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_internal_conf_conf_proto = out.File
	file_internal_conf_conf_proto_goTypes = nil
	file_internal_conf_conf_proto_depIdxs = nil
}
