// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: market-backend/v1/api.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSseApiSubscribe = "/api.v1.SseApi/Subscribe"
const OperationSseApiUnsubscribe = "/api.v1.SseApi/Unsubscribe"

type SseApiHTTPServer interface {
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeReply, error)
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeReply, error)
}

func RegisterSseApiHTTPServer(s *http.Server, srv SseApiHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/sse/subscribe", _SseApi_Subscribe0_HTTP_Handler(srv))
	r.POST("/api/v1/sse/unsubscribe", _SseApi_Unsubscribe0_HTTP_Handler(srv))
}

func _SseApi_Subscribe0_HTTP_Handler(srv SseApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubscribeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSseApiSubscribe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Subscribe(ctx, req.(*SubscribeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubscribeReply)
		return ctx.Result(200, reply)
	}
}

func _SseApi_Unsubscribe0_HTTP_Handler(srv SseApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnsubscribeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSseApiUnsubscribe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Unsubscribe(ctx, req.(*UnsubscribeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UnsubscribeReply)
		return ctx.Result(200, reply)
	}
}

type SseApiHTTPClient interface {
	Subscribe(ctx context.Context, req *SubscribeRequest, opts ...http.CallOption) (rsp *SubscribeReply, err error)
	Unsubscribe(ctx context.Context, req *UnsubscribeRequest, opts ...http.CallOption) (rsp *UnsubscribeReply, err error)
}

type SseApiHTTPClientImpl struct {
	cc *http.Client
}

func NewSseApiHTTPClient(client *http.Client) SseApiHTTPClient {
	return &SseApiHTTPClientImpl{client}
}

func (c *SseApiHTTPClientImpl) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...http.CallOption) (*SubscribeReply, error) {
	var out SubscribeReply
	pattern := "/api/v1/sse/subscribe"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSseApiSubscribe))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SseApiHTTPClientImpl) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...http.CallOption) (*UnsubscribeReply, error) {
	var out UnsubscribeReply
	pattern := "/api/v1/sse/unsubscribe"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSseApiUnsubscribe))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationHttpApiClaimMarketResult = "/api.v1.HttpApi/ClaimMarketResult"
const OperationHttpApiClaimTaskReward = "/api.v1.HttpApi/ClaimTaskReward"
const OperationHttpApiDownloadFile = "/api.v1.HttpApi/DownloadFile"
const OperationHttpApiFollowMarket = "/api.v1.HttpApi/FollowMarket"
const OperationHttpApiFollowUser = "/api.v1.HttpApi/FollowUser"
const OperationHttpApiGetBanners = "/api.v1.HttpApi/GetBanners"
const OperationHttpApiGetBaseTokenConfig = "/api.v1.HttpApi/GetBaseTokenConfig"
const OperationHttpApiGetCategories = "/api.v1.HttpApi/GetCategories"
const OperationHttpApiGetComments = "/api.v1.HttpApi/GetComments"
const OperationHttpApiGetEventDetail = "/api.v1.HttpApi/GetEventDetail"
const OperationHttpApiGetEvents = "/api.v1.HttpApi/GetEvents"
const OperationHttpApiGetFollowMarkets = "/api.v1.HttpApi/GetFollowMarkets"
const OperationHttpApiGetHoldingPositionsMarket = "/api.v1.HttpApi/GetHoldingPositionsMarket"
const OperationHttpApiGetHotMarkets = "/api.v1.HttpApi/GetHotMarkets"
const OperationHttpApiGetInviteUserList = "/api.v1.HttpApi/GetInviteUserList"
const OperationHttpApiGetLeaderboard = "/api.v1.HttpApi/GetLeaderboard"
const OperationHttpApiGetMarketDetail = "/api.v1.HttpApi/GetMarketDetail"
const OperationHttpApiGetMarketOptionPriceHistory = "/api.v1.HttpApi/GetMarketOptionPriceHistory"
const OperationHttpApiGetMarketPosts = "/api.v1.HttpApi/GetMarketPosts"
const OperationHttpApiGetMarketTrades = "/api.v1.HttpApi/GetMarketTrades"
const OperationHttpApiGetMarkets = "/api.v1.HttpApi/GetMarkets"
const OperationHttpApiGetPaymasterData = "/api.v1.HttpApi/GetPaymasterData"
const OperationHttpApiGetSections = "/api.v1.HttpApi/GetSections"
const OperationHttpApiGetTags = "/api.v1.HttpApi/GetTags"
const OperationHttpApiGetTasks = "/api.v1.HttpApi/GetTasks"
const OperationHttpApiGetUserAssetHistory = "/api.v1.HttpApi/GetUserAssetHistory"
const OperationHttpApiGetUserAssetInfo = "/api.v1.HttpApi/GetUserAssetInfo"
const OperationHttpApiGetUserBaseInfo = "/api.v1.HttpApi/GetUserBaseInfo"
const OperationHttpApiGetUserNotifications = "/api.v1.HttpApi/GetUserNotifications"
const OperationHttpApiGetUserPositions = "/api.v1.HttpApi/GetUserPositions"
const OperationHttpApiGetUserTrades = "/api.v1.HttpApi/GetUserTrades"
const OperationHttpApiGetUserTransactions = "/api.v1.HttpApi/GetUserTransactions"
const OperationHttpApiLikeContent = "/api.v1.HttpApi/LikeContent"
const OperationHttpApiLogin = "/api.v1.HttpApi/Login"
const OperationHttpApiMarkNotificationsAsRead = "/api.v1.HttpApi/MarkNotificationsAsRead"
const OperationHttpApiPlaceOrder = "/api.v1.HttpApi/PlaceOrder"
const OperationHttpApiPublishComment = "/api.v1.HttpApi/PublishComment"
const OperationHttpApiPublishPost = "/api.v1.HttpApi/PublishPost"
const OperationHttpApiSearch = "/api.v1.HttpApi/Search"
const OperationHttpApiSetAvatar = "/api.v1.HttpApi/SetAvatar"
const OperationHttpApiSetDescription = "/api.v1.HttpApi/SetDescription"
const OperationHttpApiSetName = "/api.v1.HttpApi/SetName"
const OperationHttpApiShareTaskDone = "/api.v1.HttpApi/ShareTaskDone"
const OperationHttpApiTransferBaseToken = "/api.v1.HttpApi/TransferBaseToken"
const OperationHttpApiTranslate = "/api.v1.HttpApi/Translate"
const OperationHttpApiUnfollowMarket = "/api.v1.HttpApi/UnfollowMarket"
const OperationHttpApiUnfollowUser = "/api.v1.HttpApi/UnfollowUser"
const OperationHttpApiUnlikeContent = "/api.v1.HttpApi/UnlikeContent"
const OperationHttpApiUploadFile = "/api.v1.HttpApi/UploadFile"

type HttpApiHTTPServer interface {
	// ClaimMarketResult 领取市场结果 need_auth = true
	ClaimMarketResult(context.Context, *ClaimMarketResultRequest) (*ClaimMarketResultReply, error)
	ClaimTaskReward(context.Context, *ClaimTaskRewardRequest) (*ClaimTaskRewardReply, error)
	// DownloadFile 下载文件 need_auth = false
	DownloadFile(context.Context, *DownloadFileRequest) (*DownloadFileReply, error)
	// FollowMarket 关注市场 need_auth = true
	FollowMarket(context.Context, *FollowMarketRequest) (*FollowMarketReply, error)
	// FollowUser 关注用户 need_auth = true
	FollowUser(context.Context, *FollowUserRequest) (*FollowUserReply, error)
	// GetBanners 获取banner列表 need_auth = false
	GetBanners(context.Context, *GetBannersRequest) (*GetBannersReply, error)
	// GetBaseTokenConfig 获取基础代币配置 need_auth = false
	GetBaseTokenConfig(context.Context, *GetBaseTokenConfigRequest) (*GetBaseTokenConfigReply, error)
	// GetCategories 获取市场分类列表 need_auth = false
	GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesReply, error)
	// GetComments 获取评论区 root_uuid为空只获取根评论 root_uuid不为空只获取该根评论下的二级评论(回复) need_auth = false
	GetComments(context.Context, *GetCommentsRequest) (*GetCommentsReply, error)
	// GetEventDetail 获取 Event 详情（含子市场列表） need_auth = false
	GetEventDetail(context.Context, *GetEventDetailRequest) (*GetEventDetailReply, error)
	// GetEvents 获取 Event 列表（分页） need_auth = false
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsReply, error)
	// GetFollowMarkets 获取自己关注的市场列表 need_auth = true
	GetFollowMarkets(context.Context, *GetFollowMarketsRequest) (*GetFollowMarketsReply, error)
	// GetHoldingPositionsMarket 获取持仓的市场列表（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
	GetHoldingPositionsMarket(context.Context, *GetHoldingPositionsMarketRequest) (*GetHoldingPositionsMarketReply, error)
	// GetHotMarkets 获取热门市场列表 need_auth = false
	GetHotMarkets(context.Context, *GetHotMarketsRequest) (*GetHotMarketsReply, error)
	// GetInviteUserList 获取邀请用户列表 need_auth = true
	GetInviteUserList(context.Context, *GetInviteUserListRequest) (*GetInviteUserListReply, error)
	GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error)
	// GetMarketDetail 获取市场详情 代币信息 与当前价格 need_auth = false
	GetMarketDetail(context.Context, *GetMarketDetailRequest) (*GetMarketDetailReply, error)
	// GetMarketOptionPriceHistory 获取市场期权价格历史 need_auth = false
	GetMarketOptionPriceHistory(context.Context, *GetMarketOptionPriceHistoryRequest) (*GetMarketOptionPriceHistoryReply, error)
	// GetMarketPosts 获取市场帖子列表 need_auth = false
	GetMarketPosts(context.Context, *GetMarketPostsRequest) (*GetMarketPostsReply, error)
	// GetMarketTrades 获取市场交易记录 need_auth = false
	GetMarketTrades(context.Context, *GetMarketTradesRequest) (*GetMarketTradesReply, error)
	// GetMarkets 首页获取市场列表 need_auth = false
	GetMarkets(context.Context, *GetMarketsRequest) (*GetMarketsReply, error)
	// GetPaymasterData 获取paymaster数据 need_auth = true
	GetPaymasterData(context.Context, *GetPaymasterDataRequest) (*GetPaymasterDataReply, error)
	// GetSections 获取section列表 need_auth = false
	GetSections(context.Context, *GetSectionsRequest) (*GetSectionsReply, error)
	// GetTags 获取标签列表 need_auth = false
	GetTags(context.Context, *GetTagsRequest) (*GetTagsReply, error)
	GetTasks(context.Context, *GetTasksRequest) (*GetTasksReply, error)
	// GetUserAssetHistory 查看用户资产历史变化（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
	GetUserAssetHistory(context.Context, *GetUserAssetHistoryRequest) (*GetUserAssetHistoryReply, error)
	// GetUserAssetInfo 获取用户自身的当前资产信息 need_auth = false
	GetUserAssetInfo(context.Context, *GetUserAssetInfoRequest) (*GetUserAssetInfoReply, error)
	// GetUserBaseInfo 获取用户基础信息(可以看自己 也可以看别人) need_auth = false
	GetUserBaseInfo(context.Context, *GetUserBaseInfoRequest) (*GetUserBaseInfoReply, error)
	// GetUserNotifications 获取用户通知列表 need_auth = true
	GetUserNotifications(context.Context, *GetUserNotificationsRequest) (*GetUserNotificationsReply, error)
	// GetUserPositions 获取用户持仓信息 可以看自己 也可以看别人 need_auth = false
	GetUserPositions(context.Context, *GetUserPositionsRequest) (*GetUserPositionsReply, error)
	// GetUserTrades 查看交易记录 可以看自己 也可以看别人 need_auth = false
	GetUserTrades(context.Context, *GetUserTradesRequest) (*GetUserTradesReply, error)
	// GetUserTransactions 获取用户交易记录 need_auth = true
	GetUserTransactions(context.Context, *GetUserTransactionsRequest) (*GetUserTransactionsReply, error)
	// LikeContent 点赞 need_auth = true
	LikeContent(context.Context, *LikeContentRequest) (*LikeContentReply, error)
	// Login 用户登录 每次在登录后调用 需要登录态didtoken need_auth = true
	// 没找到用户则自动创建 返回用户uid
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// MarkNotificationsAsRead 标记用户的通知为已读 need_auth = true
	MarkNotificationsAsRead(context.Context, *MarkNotificationsAsReadRequest) (*MarkNotificationsAsReadReply, error)
	// PlaceOrder 下单交易 need_auth = true
	PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderReply, error)
	// PublishComment 发布评论 need_auth = true
	PublishComment(context.Context, *PublishCommentRequest) (*PublishCommentReply, error)
	// PublishPost 发布帖子 need_auth = true
	PublishPost(context.Context, *PublishPostRequest) (*PublishPostReply, error)
	// Search 搜索 支持市场 用户 搜索  need_auth = false
	Search(context.Context, *SearchRequest) (*SearchReply, error)
	// SetAvatar 设置用户头像 need_auth = true
	SetAvatar(context.Context, *SetAvatarRequest) (*SetAvatarReply, error)
	// SetDescription 设置用户描述 need_auth = true
	SetDescription(context.Context, *SetDescriptionRequest) (*SetDescriptionReply, error)
	// SetName 设置用户名称 need_auth = true
	SetName(context.Context, *SetNameRequest) (*SetNameReply, error)
	ShareTaskDone(context.Context, *ShareTaskDoneRequest) (*ShareTaskDoneReply, error)
	// TransferBaseToken 转账基础代币 need_auth = true
	TransferBaseToken(context.Context, *TransferBaseTokenRequest) (*TransferBaseTokenReply, error)
	Translate(context.Context, *TranslateRequest) (*TranslateReply, error)
	// UnfollowMarket 取消关注市场 need_auth = true
	UnfollowMarket(context.Context, *UnfollowMarketRequest) (*UnfollowMarketReply, error)
	// UnfollowUser 取消关注用户 need_auth = true
	UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserReply, error)
	// UnlikeContent 取消点赞 need_auth = true
	UnlikeContent(context.Context, *UnlikeContentRequest) (*UnlikeContentReply, error)
	// UploadFile 上传文件 need_auth = true   上传文件返回访问的key(非完整url)
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileReply, error)
}

func RegisterHttpApiHTTPServer(s *http.Server, srv HttpApiHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/user/login", _HttpApi_Login0_HTTP_Handler(srv))
	r.POST("/api/v1/user/set-avatar", _HttpApi_SetAvatar0_HTTP_Handler(srv))
	r.POST("/api/v1/user/set-name", _HttpApi_SetName0_HTTP_Handler(srv))
	r.POST("/api/v1/user/set-description", _HttpApi_SetDescription0_HTTP_Handler(srv))
	r.POST("/api/v1/market/place-order", _HttpApi_PlaceOrder0_HTTP_Handler(srv))
	r.POST("/api/v1/market/claim-market-result", _HttpApi_ClaimMarketResult0_HTTP_Handler(srv))
	r.POST("/api/v1/market/transfer-base-token", _HttpApi_TransferBaseToken0_HTTP_Handler(srv))
	r.POST("/api/v1/market/follow-market", _HttpApi_FollowMarket0_HTTP_Handler(srv))
	r.POST("/api/v1/market/unfollow-market", _HttpApi_UnfollowMarket0_HTTP_Handler(srv))
	r.POST("/api/v1/base/upload-file", _HttpApi_UploadFile0_HTTP_Handler(srv))
	r.GET("/api/v1/base/download-file", _HttpApi_DownloadFile0_HTTP_Handler(srv))
	r.POST("/api/v1/community/publish-post", _HttpApi_PublishPost0_HTTP_Handler(srv))
	r.POST("/api/v1/community/publish-comment", _HttpApi_PublishComment0_HTTP_Handler(srv))
	r.POST("/api/v1/community/like-content", _HttpApi_LikeContent0_HTTP_Handler(srv))
	r.POST("/api/v1/community/unlike-content", _HttpApi_UnlikeContent0_HTTP_Handler(srv))
	r.POST("/api/v1/user/follow-user", _HttpApi_FollowUser0_HTTP_Handler(srv))
	r.POST("/api/v1/user/unfollow-user", _HttpApi_UnfollowUser0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-follow-markets", _HttpApi_GetFollowMarkets0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-holding-positions-market", _HttpApi_GetHoldingPositionsMarket0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-hot-markets", _HttpApi_GetHotMarkets0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-market-detail", _HttpApi_GetMarketDetail0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-market-trades", _HttpApi_GetMarketTrades0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-user-trades", _HttpApi_GetUserTrades0_HTTP_Handler(srv))
	r.GET("/api/v1/community/get-market-posts", _HttpApi_GetMarketPosts0_HTTP_Handler(srv))
	r.GET("/api/v1/community/get-comments", _HttpApi_GetComments0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-user-positions", _HttpApi_GetUserPositions0_HTTP_Handler(srv))
	r.GET("/api/v1/user/get-user-base-info", _HttpApi_GetUserBaseInfo0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-user-asset-info", _HttpApi_GetUserAssetInfo0_HTTP_Handler(srv))
	r.GET("/api/v1/base/search", _HttpApi_Search0_HTTP_Handler(srv))
	r.GET("/api/v1/user/get-user-asset-history", _HttpApi_GetUserAssetHistory0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-market-option-price-history", _HttpApi_GetMarketOptionPriceHistory0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-markets", _HttpApi_GetMarkets0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-tags", _HttpApi_GetTags0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-categories", _HttpApi_GetCategories0_HTTP_Handler(srv))
	r.POST("/api/v1/market/get-paymaster-data", _HttpApi_GetPaymasterData0_HTTP_Handler(srv))
	r.GET("/api/v1/user/get-user-notifications", _HttpApi_GetUserNotifications0_HTTP_Handler(srv))
	r.POST("/api/v1/user/mark-notifications-as-read", _HttpApi_MarkNotificationsAsRead0_HTTP_Handler(srv))
	r.GET("/api/v1/user/get-invite-user-list", _HttpApi_GetInviteUserList0_HTTP_Handler(srv))
	r.GET("/api/v1/user/get-user-transactions", _HttpApi_GetUserTransactions0_HTTP_Handler(srv))
	r.GET("/api/v1/base/get-base-token-config", _HttpApi_GetBaseTokenConfig0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-banners", _HttpApi_GetBanners0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-sections", _HttpApi_GetSections0_HTTP_Handler(srv))
	r.GET("/api/v1/task/get-tasks", _HttpApi_GetTasks0_HTTP_Handler(srv))
	r.POST("/api/v1/task/claim-task-reward", _HttpApi_ClaimTaskReward0_HTTP_Handler(srv))
	r.POST("/api/v1/task/share-task-done", _HttpApi_ShareTaskDone0_HTTP_Handler(srv))
	r.POST("/api/v1/base/translate", _HttpApi_Translate0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-leaderboard", _HttpApi_GetLeaderboard0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-event-detail", _HttpApi_GetEventDetail0_HTTP_Handler(srv))
	r.GET("/api/v1/market/get-events", _HttpApi_GetEvents0_HTTP_Handler(srv))
}

func _HttpApi_Login0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_SetAvatar0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetAvatarRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiSetAvatar)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetAvatar(ctx, req.(*SetAvatarRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetAvatarReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_SetName0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetNameRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiSetName)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetName(ctx, req.(*SetNameRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetNameReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_SetDescription0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetDescriptionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiSetDescription)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetDescription(ctx, req.(*SetDescriptionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetDescriptionReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_PlaceOrder0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PlaceOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiPlaceOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PlaceOrder(ctx, req.(*PlaceOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PlaceOrderReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_ClaimMarketResult0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClaimMarketResultRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiClaimMarketResult)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClaimMarketResult(ctx, req.(*ClaimMarketResultRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClaimMarketResultReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_TransferBaseToken0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TransferBaseTokenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiTransferBaseToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TransferBaseToken(ctx, req.(*TransferBaseTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TransferBaseTokenReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_FollowMarket0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FollowMarketRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiFollowMarket)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FollowMarket(ctx, req.(*FollowMarketRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FollowMarketReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_UnfollowMarket0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnfollowMarketRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiUnfollowMarket)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnfollowMarket(ctx, req.(*UnfollowMarketRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UnfollowMarketReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_UploadFile0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiUploadFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadFile(ctx, req.(*UploadFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadFileReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_DownloadFile0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DownloadFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiDownloadFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DownloadFile(ctx, req.(*DownloadFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DownloadFileReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_PublishPost0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PublishPostRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiPublishPost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PublishPost(ctx, req.(*PublishPostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PublishPostReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_PublishComment0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PublishCommentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiPublishComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PublishComment(ctx, req.(*PublishCommentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PublishCommentReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_LikeContent0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LikeContentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiLikeContent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LikeContent(ctx, req.(*LikeContentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LikeContentReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_UnlikeContent0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnlikeContentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiUnlikeContent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnlikeContent(ctx, req.(*UnlikeContentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UnlikeContentReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_FollowUser0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FollowUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiFollowUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FollowUser(ctx, req.(*FollowUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FollowUserReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_UnfollowUser0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnfollowUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiUnfollowUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnfollowUser(ctx, req.(*UnfollowUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UnfollowUserReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetFollowMarkets0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetFollowMarketsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetFollowMarkets)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetFollowMarkets(ctx, req.(*GetFollowMarketsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetFollowMarketsReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetHoldingPositionsMarket0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetHoldingPositionsMarketRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetHoldingPositionsMarket)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetHoldingPositionsMarket(ctx, req.(*GetHoldingPositionsMarketRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetHoldingPositionsMarketReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetHotMarkets0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetHotMarketsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetHotMarkets)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetHotMarkets(ctx, req.(*GetHotMarketsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetHotMarketsReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetMarketDetail0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMarketDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetMarketDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMarketDetail(ctx, req.(*GetMarketDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMarketDetailReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetMarketTrades0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMarketTradesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetMarketTrades)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMarketTrades(ctx, req.(*GetMarketTradesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMarketTradesReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetUserTrades0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserTradesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetUserTrades)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserTrades(ctx, req.(*GetUserTradesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserTradesReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetMarketPosts0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMarketPostsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetMarketPosts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMarketPosts(ctx, req.(*GetMarketPostsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMarketPostsReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetComments0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCommentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetComments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetComments(ctx, req.(*GetCommentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCommentsReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetUserPositions0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserPositionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetUserPositions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserPositions(ctx, req.(*GetUserPositionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserPositionsReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetUserBaseInfo0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserBaseInfoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetUserBaseInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserBaseInfo(ctx, req.(*GetUserBaseInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserBaseInfoReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetUserAssetInfo0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserAssetInfoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetUserAssetInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserAssetInfo(ctx, req.(*GetUserAssetInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserAssetInfoReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_Search0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiSearch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Search(ctx, req.(*SearchRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetUserAssetHistory0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserAssetHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetUserAssetHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserAssetHistory(ctx, req.(*GetUserAssetHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserAssetHistoryReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetMarketOptionPriceHistory0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMarketOptionPriceHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetMarketOptionPriceHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMarketOptionPriceHistory(ctx, req.(*GetMarketOptionPriceHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMarketOptionPriceHistoryReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetMarkets0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMarketsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetMarkets)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMarkets(ctx, req.(*GetMarketsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMarketsReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetTags0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTagsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetTags)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTags(ctx, req.(*GetTagsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTagsReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetCategories0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCategoriesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetCategories)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCategories(ctx, req.(*GetCategoriesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCategoriesReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetPaymasterData0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPaymasterDataRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetPaymasterData)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPaymasterData(ctx, req.(*GetPaymasterDataRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPaymasterDataReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetUserNotifications0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserNotificationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetUserNotifications)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserNotifications(ctx, req.(*GetUserNotificationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserNotificationsReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_MarkNotificationsAsRead0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MarkNotificationsAsReadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiMarkNotificationsAsRead)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkNotificationsAsRead(ctx, req.(*MarkNotificationsAsReadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MarkNotificationsAsReadReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetInviteUserList0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetInviteUserListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetInviteUserList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetInviteUserList(ctx, req.(*GetInviteUserListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetInviteUserListReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetUserTransactions0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserTransactionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetUserTransactions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserTransactions(ctx, req.(*GetUserTransactionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserTransactionsReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetBaseTokenConfig0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBaseTokenConfigRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetBaseTokenConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBaseTokenConfig(ctx, req.(*GetBaseTokenConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBaseTokenConfigReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetBanners0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBannersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetBanners)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBanners(ctx, req.(*GetBannersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBannersReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetSections0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSectionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetSections)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSections(ctx, req.(*GetSectionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSectionsReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetTasks0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTasks(ctx, req.(*GetTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTasksReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_ClaimTaskReward0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClaimTaskRewardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiClaimTaskReward)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClaimTaskReward(ctx, req.(*ClaimTaskRewardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClaimTaskRewardReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_ShareTaskDone0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ShareTaskDoneRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiShareTaskDone)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ShareTaskDone(ctx, req.(*ShareTaskDoneRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ShareTaskDoneReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_Translate0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TranslateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiTranslate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Translate(ctx, req.(*TranslateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TranslateReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetLeaderboard0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLeaderboardRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetLeaderboard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLeaderboard(ctx, req.(*GetLeaderboardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLeaderboardResponse)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetEventDetail0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEventDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetEventDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEventDetail(ctx, req.(*GetEventDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEventDetailReply)
		return ctx.Result(200, reply)
	}
}

func _HttpApi_GetEvents0_HTTP_Handler(srv HttpApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEventsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHttpApiGetEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEvents(ctx, req.(*GetEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEventsReply)
		return ctx.Result(200, reply)
	}
}

type HttpApiHTTPClient interface {
	// ClaimMarketResult 领取市场结果 need_auth = true
	ClaimMarketResult(ctx context.Context, req *ClaimMarketResultRequest, opts ...http.CallOption) (rsp *ClaimMarketResultReply, err error)
	ClaimTaskReward(ctx context.Context, req *ClaimTaskRewardRequest, opts ...http.CallOption) (rsp *ClaimTaskRewardReply, err error)
	// DownloadFile 下载文件 need_auth = false
	DownloadFile(ctx context.Context, req *DownloadFileRequest, opts ...http.CallOption) (rsp *DownloadFileReply, err error)
	// FollowMarket 关注市场 need_auth = true
	FollowMarket(ctx context.Context, req *FollowMarketRequest, opts ...http.CallOption) (rsp *FollowMarketReply, err error)
	// FollowUser 关注用户 need_auth = true
	FollowUser(ctx context.Context, req *FollowUserRequest, opts ...http.CallOption) (rsp *FollowUserReply, err error)
	// GetBanners 获取banner列表 need_auth = false
	GetBanners(ctx context.Context, req *GetBannersRequest, opts ...http.CallOption) (rsp *GetBannersReply, err error)
	// GetBaseTokenConfig 获取基础代币配置 need_auth = false
	GetBaseTokenConfig(ctx context.Context, req *GetBaseTokenConfigRequest, opts ...http.CallOption) (rsp *GetBaseTokenConfigReply, err error)
	// GetCategories 获取市场分类列表 need_auth = false
	GetCategories(ctx context.Context, req *GetCategoriesRequest, opts ...http.CallOption) (rsp *GetCategoriesReply, err error)
	// GetComments 获取评论区 root_uuid为空只获取根评论 root_uuid不为空只获取该根评论下的二级评论(回复) need_auth = false
	GetComments(ctx context.Context, req *GetCommentsRequest, opts ...http.CallOption) (rsp *GetCommentsReply, err error)
	// GetEventDetail 获取 Event 详情（含子市场列表） need_auth = false
	GetEventDetail(ctx context.Context, req *GetEventDetailRequest, opts ...http.CallOption) (rsp *GetEventDetailReply, err error)
	// GetEvents 获取 Event 列表（分页） need_auth = false
	GetEvents(ctx context.Context, req *GetEventsRequest, opts ...http.CallOption) (rsp *GetEventsReply, err error)
	// GetFollowMarkets 获取自己关注的市场列表 need_auth = true
	GetFollowMarkets(ctx context.Context, req *GetFollowMarketsRequest, opts ...http.CallOption) (rsp *GetFollowMarketsReply, err error)
	// GetHoldingPositionsMarket 获取持仓的市场列表（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
	GetHoldingPositionsMarket(ctx context.Context, req *GetHoldingPositionsMarketRequest, opts ...http.CallOption) (rsp *GetHoldingPositionsMarketReply, err error)
	// GetHotMarkets 获取热门市场列表 need_auth = false
	GetHotMarkets(ctx context.Context, req *GetHotMarketsRequest, opts ...http.CallOption) (rsp *GetHotMarketsReply, err error)
	// GetInviteUserList 获取邀请用户列表 need_auth = true
	GetInviteUserList(ctx context.Context, req *GetInviteUserListRequest, opts ...http.CallOption) (rsp *GetInviteUserListReply, err error)
	GetLeaderboard(ctx context.Context, req *GetLeaderboardRequest, opts ...http.CallOption) (rsp *GetLeaderboardResponse, err error)
	// GetMarketDetail 获取市场详情 代币信息 与当前价格 need_auth = false
	GetMarketDetail(ctx context.Context, req *GetMarketDetailRequest, opts ...http.CallOption) (rsp *GetMarketDetailReply, err error)
	// GetMarketOptionPriceHistory 获取市场期权价格历史 need_auth = false
	GetMarketOptionPriceHistory(ctx context.Context, req *GetMarketOptionPriceHistoryRequest, opts ...http.CallOption) (rsp *GetMarketOptionPriceHistoryReply, err error)
	// GetMarketPosts 获取市场帖子列表 need_auth = false
	GetMarketPosts(ctx context.Context, req *GetMarketPostsRequest, opts ...http.CallOption) (rsp *GetMarketPostsReply, err error)
	// GetMarketTrades 获取市场交易记录 need_auth = false
	GetMarketTrades(ctx context.Context, req *GetMarketTradesRequest, opts ...http.CallOption) (rsp *GetMarketTradesReply, err error)
	// GetMarkets 首页获取市场列表 need_auth = false
	GetMarkets(ctx context.Context, req *GetMarketsRequest, opts ...http.CallOption) (rsp *GetMarketsReply, err error)
	// GetPaymasterData 获取paymaster数据 need_auth = true
	GetPaymasterData(ctx context.Context, req *GetPaymasterDataRequest, opts ...http.CallOption) (rsp *GetPaymasterDataReply, err error)
	// GetSections 获取section列表 need_auth = false
	GetSections(ctx context.Context, req *GetSectionsRequest, opts ...http.CallOption) (rsp *GetSectionsReply, err error)
	// GetTags 获取标签列表 need_auth = false
	GetTags(ctx context.Context, req *GetTagsRequest, opts ...http.CallOption) (rsp *GetTagsReply, err error)
	GetTasks(ctx context.Context, req *GetTasksRequest, opts ...http.CallOption) (rsp *GetTasksReply, err error)
	// GetUserAssetHistory 查看用户资产历史变化（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
	GetUserAssetHistory(ctx context.Context, req *GetUserAssetHistoryRequest, opts ...http.CallOption) (rsp *GetUserAssetHistoryReply, err error)
	// GetUserAssetInfo 获取用户自身的当前资产信息 need_auth = false
	GetUserAssetInfo(ctx context.Context, req *GetUserAssetInfoRequest, opts ...http.CallOption) (rsp *GetUserAssetInfoReply, err error)
	// GetUserBaseInfo 获取用户基础信息(可以看自己 也可以看别人) need_auth = false
	GetUserBaseInfo(ctx context.Context, req *GetUserBaseInfoRequest, opts ...http.CallOption) (rsp *GetUserBaseInfoReply, err error)
	// GetUserNotifications 获取用户通知列表 need_auth = true
	GetUserNotifications(ctx context.Context, req *GetUserNotificationsRequest, opts ...http.CallOption) (rsp *GetUserNotificationsReply, err error)
	// GetUserPositions 获取用户持仓信息 可以看自己 也可以看别人 need_auth = false
	GetUserPositions(ctx context.Context, req *GetUserPositionsRequest, opts ...http.CallOption) (rsp *GetUserPositionsReply, err error)
	// GetUserTrades 查看交易记录 可以看自己 也可以看别人 need_auth = false
	GetUserTrades(ctx context.Context, req *GetUserTradesRequest, opts ...http.CallOption) (rsp *GetUserTradesReply, err error)
	// GetUserTransactions 获取用户交易记录 need_auth = true
	GetUserTransactions(ctx context.Context, req *GetUserTransactionsRequest, opts ...http.CallOption) (rsp *GetUserTransactionsReply, err error)
	// LikeContent 点赞 need_auth = true
	LikeContent(ctx context.Context, req *LikeContentRequest, opts ...http.CallOption) (rsp *LikeContentReply, err error)
	// Login 用户登录 每次在登录后调用 需要登录态didtoken need_auth = true
	// 没找到用户则自动创建 返回用户uid
	Login(ctx context.Context, req *LoginRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
	// MarkNotificationsAsRead 标记用户的通知为已读 need_auth = true
	MarkNotificationsAsRead(ctx context.Context, req *MarkNotificationsAsReadRequest, opts ...http.CallOption) (rsp *MarkNotificationsAsReadReply, err error)
	// PlaceOrder 下单交易 need_auth = true
	PlaceOrder(ctx context.Context, req *PlaceOrderRequest, opts ...http.CallOption) (rsp *PlaceOrderReply, err error)
	// PublishComment 发布评论 need_auth = true
	PublishComment(ctx context.Context, req *PublishCommentRequest, opts ...http.CallOption) (rsp *PublishCommentReply, err error)
	// PublishPost 发布帖子 need_auth = true
	PublishPost(ctx context.Context, req *PublishPostRequest, opts ...http.CallOption) (rsp *PublishPostReply, err error)
	// Search 搜索 支持市场 用户 搜索  need_auth = false
	Search(ctx context.Context, req *SearchRequest, opts ...http.CallOption) (rsp *SearchReply, err error)
	// SetAvatar 设置用户头像 need_auth = true
	SetAvatar(ctx context.Context, req *SetAvatarRequest, opts ...http.CallOption) (rsp *SetAvatarReply, err error)
	// SetDescription 设置用户描述 need_auth = true
	SetDescription(ctx context.Context, req *SetDescriptionRequest, opts ...http.CallOption) (rsp *SetDescriptionReply, err error)
	// SetName 设置用户名称 need_auth = true
	SetName(ctx context.Context, req *SetNameRequest, opts ...http.CallOption) (rsp *SetNameReply, err error)
	ShareTaskDone(ctx context.Context, req *ShareTaskDoneRequest, opts ...http.CallOption) (rsp *ShareTaskDoneReply, err error)
	// TransferBaseToken 转账基础代币 need_auth = true
	TransferBaseToken(ctx context.Context, req *TransferBaseTokenRequest, opts ...http.CallOption) (rsp *TransferBaseTokenReply, err error)
	Translate(ctx context.Context, req *TranslateRequest, opts ...http.CallOption) (rsp *TranslateReply, err error)
	// UnfollowMarket 取消关注市场 need_auth = true
	UnfollowMarket(ctx context.Context, req *UnfollowMarketRequest, opts ...http.CallOption) (rsp *UnfollowMarketReply, err error)
	// UnfollowUser 取消关注用户 need_auth = true
	UnfollowUser(ctx context.Context, req *UnfollowUserRequest, opts ...http.CallOption) (rsp *UnfollowUserReply, err error)
	// UnlikeContent 取消点赞 need_auth = true
	UnlikeContent(ctx context.Context, req *UnlikeContentRequest, opts ...http.CallOption) (rsp *UnlikeContentReply, err error)
	// UploadFile 上传文件 need_auth = true   上传文件返回访问的key(非完整url)
	UploadFile(ctx context.Context, req *UploadFileRequest, opts ...http.CallOption) (rsp *UploadFileReply, err error)
}

type HttpApiHTTPClientImpl struct {
	cc *http.Client
}

func NewHttpApiHTTPClient(client *http.Client) HttpApiHTTPClient {
	return &HttpApiHTTPClientImpl{client}
}

// ClaimMarketResult 领取市场结果 need_auth = true
func (c *HttpApiHTTPClientImpl) ClaimMarketResult(ctx context.Context, in *ClaimMarketResultRequest, opts ...http.CallOption) (*ClaimMarketResultReply, error) {
	var out ClaimMarketResultReply
	pattern := "/api/v1/market/claim-market-result"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiClaimMarketResult))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HttpApiHTTPClientImpl) ClaimTaskReward(ctx context.Context, in *ClaimTaskRewardRequest, opts ...http.CallOption) (*ClaimTaskRewardReply, error) {
	var out ClaimTaskRewardReply
	pattern := "/api/v1/task/claim-task-reward"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiClaimTaskReward))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DownloadFile 下载文件 need_auth = false
func (c *HttpApiHTTPClientImpl) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...http.CallOption) (*DownloadFileReply, error) {
	var out DownloadFileReply
	pattern := "/api/v1/base/download-file"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiDownloadFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FollowMarket 关注市场 need_auth = true
func (c *HttpApiHTTPClientImpl) FollowMarket(ctx context.Context, in *FollowMarketRequest, opts ...http.CallOption) (*FollowMarketReply, error) {
	var out FollowMarketReply
	pattern := "/api/v1/market/follow-market"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiFollowMarket))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FollowUser 关注用户 need_auth = true
func (c *HttpApiHTTPClientImpl) FollowUser(ctx context.Context, in *FollowUserRequest, opts ...http.CallOption) (*FollowUserReply, error) {
	var out FollowUserReply
	pattern := "/api/v1/user/follow-user"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiFollowUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetBanners 获取banner列表 need_auth = false
func (c *HttpApiHTTPClientImpl) GetBanners(ctx context.Context, in *GetBannersRequest, opts ...http.CallOption) (*GetBannersReply, error) {
	var out GetBannersReply
	pattern := "/api/v1/market/get-banners"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetBanners))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetBaseTokenConfig 获取基础代币配置 need_auth = false
func (c *HttpApiHTTPClientImpl) GetBaseTokenConfig(ctx context.Context, in *GetBaseTokenConfigRequest, opts ...http.CallOption) (*GetBaseTokenConfigReply, error) {
	var out GetBaseTokenConfigReply
	pattern := "/api/v1/base/get-base-token-config"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetBaseTokenConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCategories 获取市场分类列表 need_auth = false
func (c *HttpApiHTTPClientImpl) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...http.CallOption) (*GetCategoriesReply, error) {
	var out GetCategoriesReply
	pattern := "/api/v1/market/get-categories"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetCategories))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetComments 获取评论区 root_uuid为空只获取根评论 root_uuid不为空只获取该根评论下的二级评论(回复) need_auth = false
func (c *HttpApiHTTPClientImpl) GetComments(ctx context.Context, in *GetCommentsRequest, opts ...http.CallOption) (*GetCommentsReply, error) {
	var out GetCommentsReply
	pattern := "/api/v1/community/get-comments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetComments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetEventDetail 获取 Event 详情（含子市场列表） need_auth = false
func (c *HttpApiHTTPClientImpl) GetEventDetail(ctx context.Context, in *GetEventDetailRequest, opts ...http.CallOption) (*GetEventDetailReply, error) {
	var out GetEventDetailReply
	pattern := "/api/v1/market/get-event-detail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetEventDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetEvents 获取 Event 列表（分页） need_auth = false
func (c *HttpApiHTTPClientImpl) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...http.CallOption) (*GetEventsReply, error) {
	var out GetEventsReply
	pattern := "/api/v1/market/get-events"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetEvents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetFollowMarkets 获取自己关注的市场列表 need_auth = true
func (c *HttpApiHTTPClientImpl) GetFollowMarkets(ctx context.Context, in *GetFollowMarketsRequest, opts ...http.CallOption) (*GetFollowMarketsReply, error) {
	var out GetFollowMarketsReply
	pattern := "/api/v1/market/get-follow-markets"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetFollowMarkets))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetHoldingPositionsMarket 获取持仓的市场列表（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
func (c *HttpApiHTTPClientImpl) GetHoldingPositionsMarket(ctx context.Context, in *GetHoldingPositionsMarketRequest, opts ...http.CallOption) (*GetHoldingPositionsMarketReply, error) {
	var out GetHoldingPositionsMarketReply
	pattern := "/api/v1/market/get-holding-positions-market"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetHoldingPositionsMarket))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetHotMarkets 获取热门市场列表 need_auth = false
func (c *HttpApiHTTPClientImpl) GetHotMarkets(ctx context.Context, in *GetHotMarketsRequest, opts ...http.CallOption) (*GetHotMarketsReply, error) {
	var out GetHotMarketsReply
	pattern := "/api/v1/market/get-hot-markets"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetHotMarkets))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetInviteUserList 获取邀请用户列表 need_auth = true
func (c *HttpApiHTTPClientImpl) GetInviteUserList(ctx context.Context, in *GetInviteUserListRequest, opts ...http.CallOption) (*GetInviteUserListReply, error) {
	var out GetInviteUserListReply
	pattern := "/api/v1/user/get-invite-user-list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetInviteUserList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HttpApiHTTPClientImpl) GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...http.CallOption) (*GetLeaderboardResponse, error) {
	var out GetLeaderboardResponse
	pattern := "/api/v1/market/get-leaderboard"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetLeaderboard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMarketDetail 获取市场详情 代币信息 与当前价格 need_auth = false
func (c *HttpApiHTTPClientImpl) GetMarketDetail(ctx context.Context, in *GetMarketDetailRequest, opts ...http.CallOption) (*GetMarketDetailReply, error) {
	var out GetMarketDetailReply
	pattern := "/api/v1/market/get-market-detail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetMarketDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMarketOptionPriceHistory 获取市场期权价格历史 need_auth = false
func (c *HttpApiHTTPClientImpl) GetMarketOptionPriceHistory(ctx context.Context, in *GetMarketOptionPriceHistoryRequest, opts ...http.CallOption) (*GetMarketOptionPriceHistoryReply, error) {
	var out GetMarketOptionPriceHistoryReply
	pattern := "/api/v1/market/get-market-option-price-history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetMarketOptionPriceHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMarketPosts 获取市场帖子列表 need_auth = false
func (c *HttpApiHTTPClientImpl) GetMarketPosts(ctx context.Context, in *GetMarketPostsRequest, opts ...http.CallOption) (*GetMarketPostsReply, error) {
	var out GetMarketPostsReply
	pattern := "/api/v1/community/get-market-posts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetMarketPosts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMarketTrades 获取市场交易记录 need_auth = false
func (c *HttpApiHTTPClientImpl) GetMarketTrades(ctx context.Context, in *GetMarketTradesRequest, opts ...http.CallOption) (*GetMarketTradesReply, error) {
	var out GetMarketTradesReply
	pattern := "/api/v1/market/get-market-trades"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetMarketTrades))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMarkets 首页获取市场列表 need_auth = false
func (c *HttpApiHTTPClientImpl) GetMarkets(ctx context.Context, in *GetMarketsRequest, opts ...http.CallOption) (*GetMarketsReply, error) {
	var out GetMarketsReply
	pattern := "/api/v1/market/get-markets"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetMarkets))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPaymasterData 获取paymaster数据 need_auth = true
func (c *HttpApiHTTPClientImpl) GetPaymasterData(ctx context.Context, in *GetPaymasterDataRequest, opts ...http.CallOption) (*GetPaymasterDataReply, error) {
	var out GetPaymasterDataReply
	pattern := "/api/v1/market/get-paymaster-data"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiGetPaymasterData))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSections 获取section列表 need_auth = false
func (c *HttpApiHTTPClientImpl) GetSections(ctx context.Context, in *GetSectionsRequest, opts ...http.CallOption) (*GetSectionsReply, error) {
	var out GetSectionsReply
	pattern := "/api/v1/market/get-sections"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetSections))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTags 获取标签列表 need_auth = false
func (c *HttpApiHTTPClientImpl) GetTags(ctx context.Context, in *GetTagsRequest, opts ...http.CallOption) (*GetTagsReply, error) {
	var out GetTagsReply
	pattern := "/api/v1/market/get-tags"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetTags))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HttpApiHTTPClientImpl) GetTasks(ctx context.Context, in *GetTasksRequest, opts ...http.CallOption) (*GetTasksReply, error) {
	var out GetTasksReply
	pattern := "/api/v1/task/get-tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUserAssetHistory 查看用户资产历史变化（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
func (c *HttpApiHTTPClientImpl) GetUserAssetHistory(ctx context.Context, in *GetUserAssetHistoryRequest, opts ...http.CallOption) (*GetUserAssetHistoryReply, error) {
	var out GetUserAssetHistoryReply
	pattern := "/api/v1/user/get-user-asset-history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetUserAssetHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUserAssetInfo 获取用户自身的当前资产信息 need_auth = false
func (c *HttpApiHTTPClientImpl) GetUserAssetInfo(ctx context.Context, in *GetUserAssetInfoRequest, opts ...http.CallOption) (*GetUserAssetInfoReply, error) {
	var out GetUserAssetInfoReply
	pattern := "/api/v1/market/get-user-asset-info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetUserAssetInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUserBaseInfo 获取用户基础信息(可以看自己 也可以看别人) need_auth = false
func (c *HttpApiHTTPClientImpl) GetUserBaseInfo(ctx context.Context, in *GetUserBaseInfoRequest, opts ...http.CallOption) (*GetUserBaseInfoReply, error) {
	var out GetUserBaseInfoReply
	pattern := "/api/v1/user/get-user-base-info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetUserBaseInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUserNotifications 获取用户通知列表 need_auth = true
func (c *HttpApiHTTPClientImpl) GetUserNotifications(ctx context.Context, in *GetUserNotificationsRequest, opts ...http.CallOption) (*GetUserNotificationsReply, error) {
	var out GetUserNotificationsReply
	pattern := "/api/v1/user/get-user-notifications"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetUserNotifications))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUserPositions 获取用户持仓信息 可以看自己 也可以看别人 need_auth = false
func (c *HttpApiHTTPClientImpl) GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...http.CallOption) (*GetUserPositionsReply, error) {
	var out GetUserPositionsReply
	pattern := "/api/v1/market/get-user-positions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetUserPositions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUserTrades 查看交易记录 可以看自己 也可以看别人 need_auth = false
func (c *HttpApiHTTPClientImpl) GetUserTrades(ctx context.Context, in *GetUserTradesRequest, opts ...http.CallOption) (*GetUserTradesReply, error) {
	var out GetUserTradesReply
	pattern := "/api/v1/market/get-user-trades"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetUserTrades))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUserTransactions 获取用户交易记录 need_auth = true
func (c *HttpApiHTTPClientImpl) GetUserTransactions(ctx context.Context, in *GetUserTransactionsRequest, opts ...http.CallOption) (*GetUserTransactionsReply, error) {
	var out GetUserTransactionsReply
	pattern := "/api/v1/user/get-user-transactions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiGetUserTransactions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LikeContent 点赞 need_auth = true
func (c *HttpApiHTTPClientImpl) LikeContent(ctx context.Context, in *LikeContentRequest, opts ...http.CallOption) (*LikeContentReply, error) {
	var out LikeContentReply
	pattern := "/api/v1/community/like-content"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiLikeContent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Login 用户登录 每次在登录后调用 需要登录态didtoken need_auth = true
// 没找到用户则自动创建 返回用户uid
func (c *HttpApiHTTPClientImpl) Login(ctx context.Context, in *LoginRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/api/v1/user/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MarkNotificationsAsRead 标记用户的通知为已读 need_auth = true
func (c *HttpApiHTTPClientImpl) MarkNotificationsAsRead(ctx context.Context, in *MarkNotificationsAsReadRequest, opts ...http.CallOption) (*MarkNotificationsAsReadReply, error) {
	var out MarkNotificationsAsReadReply
	pattern := "/api/v1/user/mark-notifications-as-read"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiMarkNotificationsAsRead))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PlaceOrder 下单交易 need_auth = true
func (c *HttpApiHTTPClientImpl) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...http.CallOption) (*PlaceOrderReply, error) {
	var out PlaceOrderReply
	pattern := "/api/v1/market/place-order"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiPlaceOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PublishComment 发布评论 need_auth = true
func (c *HttpApiHTTPClientImpl) PublishComment(ctx context.Context, in *PublishCommentRequest, opts ...http.CallOption) (*PublishCommentReply, error) {
	var out PublishCommentReply
	pattern := "/api/v1/community/publish-comment"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiPublishComment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PublishPost 发布帖子 need_auth = true
func (c *HttpApiHTTPClientImpl) PublishPost(ctx context.Context, in *PublishPostRequest, opts ...http.CallOption) (*PublishPostReply, error) {
	var out PublishPostReply
	pattern := "/api/v1/community/publish-post"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiPublishPost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Search 搜索 支持市场 用户 搜索  need_auth = false
func (c *HttpApiHTTPClientImpl) Search(ctx context.Context, in *SearchRequest, opts ...http.CallOption) (*SearchReply, error) {
	var out SearchReply
	pattern := "/api/v1/base/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHttpApiSearch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetAvatar 设置用户头像 need_auth = true
func (c *HttpApiHTTPClientImpl) SetAvatar(ctx context.Context, in *SetAvatarRequest, opts ...http.CallOption) (*SetAvatarReply, error) {
	var out SetAvatarReply
	pattern := "/api/v1/user/set-avatar"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiSetAvatar))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetDescription 设置用户描述 need_auth = true
func (c *HttpApiHTTPClientImpl) SetDescription(ctx context.Context, in *SetDescriptionRequest, opts ...http.CallOption) (*SetDescriptionReply, error) {
	var out SetDescriptionReply
	pattern := "/api/v1/user/set-description"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiSetDescription))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetName 设置用户名称 need_auth = true
func (c *HttpApiHTTPClientImpl) SetName(ctx context.Context, in *SetNameRequest, opts ...http.CallOption) (*SetNameReply, error) {
	var out SetNameReply
	pattern := "/api/v1/user/set-name"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiSetName))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HttpApiHTTPClientImpl) ShareTaskDone(ctx context.Context, in *ShareTaskDoneRequest, opts ...http.CallOption) (*ShareTaskDoneReply, error) {
	var out ShareTaskDoneReply
	pattern := "/api/v1/task/share-task-done"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiShareTaskDone))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TransferBaseToken 转账基础代币 need_auth = true
func (c *HttpApiHTTPClientImpl) TransferBaseToken(ctx context.Context, in *TransferBaseTokenRequest, opts ...http.CallOption) (*TransferBaseTokenReply, error) {
	var out TransferBaseTokenReply
	pattern := "/api/v1/market/transfer-base-token"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiTransferBaseToken))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HttpApiHTTPClientImpl) Translate(ctx context.Context, in *TranslateRequest, opts ...http.CallOption) (*TranslateReply, error) {
	var out TranslateReply
	pattern := "/api/v1/base/translate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiTranslate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UnfollowMarket 取消关注市场 need_auth = true
func (c *HttpApiHTTPClientImpl) UnfollowMarket(ctx context.Context, in *UnfollowMarketRequest, opts ...http.CallOption) (*UnfollowMarketReply, error) {
	var out UnfollowMarketReply
	pattern := "/api/v1/market/unfollow-market"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiUnfollowMarket))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UnfollowUser 取消关注用户 need_auth = true
func (c *HttpApiHTTPClientImpl) UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...http.CallOption) (*UnfollowUserReply, error) {
	var out UnfollowUserReply
	pattern := "/api/v1/user/unfollow-user"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiUnfollowUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UnlikeContent 取消点赞 need_auth = true
func (c *HttpApiHTTPClientImpl) UnlikeContent(ctx context.Context, in *UnlikeContentRequest, opts ...http.CallOption) (*UnlikeContentReply, error) {
	var out UnlikeContentReply
	pattern := "/api/v1/community/unlike-content"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiUnlikeContent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UploadFile 上传文件 need_auth = true   上传文件返回访问的key(非完整url)
func (c *HttpApiHTTPClientImpl) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...http.CallOption) (*UploadFileReply, error) {
	var out UploadFileReply
	pattern := "/api/v1/base/upload-file"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHttpApiUploadFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
