// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: market-backend/v1/api.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SseApi_Subscribe_FullMethodName   = "/api.v1.SseApi/Subscribe"
	SseApi_Unsubscribe_FullMethodName = "/api.v1.SseApi/Unsubscribe"
)

// SseApiClient is the client API for SseApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SseApiClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeReply, error)
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeReply, error)
}

type sseApiClient struct {
	cc grpc.ClientConnInterface
}

func NewSseApiClient(cc grpc.ClientConnInterface) SseApiClient {
	return &sseApiClient{cc}
}

func (c *sseApiClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeReply)
	err := c.cc.Invoke(ctx, SseApi_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sseApiClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeReply)
	err := c.cc.Invoke(ctx, SseApi_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SseApiServer is the server API for SseApi service.
// All implementations must embed UnimplementedSseApiServer
// for forward compatibility.
type SseApiServer interface {
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeReply, error)
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeReply, error)
	mustEmbedUnimplementedSseApiServer()
}

// UnimplementedSseApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSseApiServer struct{}

func (UnimplementedSseApiServer) Subscribe(context.Context, *SubscribeRequest) (*SubscribeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSseApiServer) Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedSseApiServer) mustEmbedUnimplementedSseApiServer() {}
func (UnimplementedSseApiServer) testEmbeddedByValue()                {}

// UnsafeSseApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SseApiServer will
// result in compilation errors.
type UnsafeSseApiServer interface {
	mustEmbedUnimplementedSseApiServer()
}

func RegisterSseApiServer(s grpc.ServiceRegistrar, srv SseApiServer) {
	// If the following call panics, it indicates UnimplementedSseApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SseApi_ServiceDesc, srv)
}

func _SseApi_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SseApiServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SseApi_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SseApiServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SseApi_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SseApiServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SseApi_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SseApiServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SseApi_ServiceDesc is the grpc.ServiceDesc for SseApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SseApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.SseApi",
	HandlerType: (*SseApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _SseApi_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _SseApi_Unsubscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market-backend/v1/api.proto",
}

const (
	HttpApi_Login_FullMethodName                       = "/api.v1.HttpApi/Login"
	HttpApi_SetAvatar_FullMethodName                   = "/api.v1.HttpApi/SetAvatar"
	HttpApi_SetName_FullMethodName                     = "/api.v1.HttpApi/SetName"
	HttpApi_SetDescription_FullMethodName              = "/api.v1.HttpApi/SetDescription"
	HttpApi_PlaceOrder_FullMethodName                  = "/api.v1.HttpApi/PlaceOrder"
	HttpApi_ClaimMarketResult_FullMethodName           = "/api.v1.HttpApi/ClaimMarketResult"
	HttpApi_TransferBaseToken_FullMethodName           = "/api.v1.HttpApi/TransferBaseToken"
	HttpApi_FollowMarket_FullMethodName                = "/api.v1.HttpApi/FollowMarket"
	HttpApi_UnfollowMarket_FullMethodName              = "/api.v1.HttpApi/UnfollowMarket"
	HttpApi_UploadFile_FullMethodName                  = "/api.v1.HttpApi/UploadFile"
	HttpApi_DownloadFile_FullMethodName                = "/api.v1.HttpApi/DownloadFile"
	HttpApi_PublishPost_FullMethodName                 = "/api.v1.HttpApi/PublishPost"
	HttpApi_PublishComment_FullMethodName              = "/api.v1.HttpApi/PublishComment"
	HttpApi_LikeContent_FullMethodName                 = "/api.v1.HttpApi/LikeContent"
	HttpApi_UnlikeContent_FullMethodName               = "/api.v1.HttpApi/UnlikeContent"
	HttpApi_FollowUser_FullMethodName                  = "/api.v1.HttpApi/FollowUser"
	HttpApi_UnfollowUser_FullMethodName                = "/api.v1.HttpApi/UnfollowUser"
	HttpApi_GetFollowMarkets_FullMethodName            = "/api.v1.HttpApi/GetFollowMarkets"
	HttpApi_GetHoldingPositionsMarket_FullMethodName   = "/api.v1.HttpApi/GetHoldingPositionsMarket"
	HttpApi_GetHotMarkets_FullMethodName               = "/api.v1.HttpApi/GetHotMarkets"
	HttpApi_GetMarketDetail_FullMethodName             = "/api.v1.HttpApi/GetMarketDetail"
	HttpApi_GetMarketTrades_FullMethodName             = "/api.v1.HttpApi/GetMarketTrades"
	HttpApi_GetUserTrades_FullMethodName               = "/api.v1.HttpApi/GetUserTrades"
	HttpApi_GetMarketPosts_FullMethodName              = "/api.v1.HttpApi/GetMarketPosts"
	HttpApi_GetComments_FullMethodName                 = "/api.v1.HttpApi/GetComments"
	HttpApi_GetUserPositions_FullMethodName            = "/api.v1.HttpApi/GetUserPositions"
	HttpApi_GetUserBaseInfo_FullMethodName             = "/api.v1.HttpApi/GetUserBaseInfo"
	HttpApi_GetUserAssetInfo_FullMethodName            = "/api.v1.HttpApi/GetUserAssetInfo"
	HttpApi_Search_FullMethodName                      = "/api.v1.HttpApi/Search"
	HttpApi_GetUserAssetHistory_FullMethodName         = "/api.v1.HttpApi/GetUserAssetHistory"
	HttpApi_GetMarketOptionPriceHistory_FullMethodName = "/api.v1.HttpApi/GetMarketOptionPriceHistory"
	HttpApi_GetMarkets_FullMethodName                  = "/api.v1.HttpApi/GetMarkets"
	HttpApi_GetTags_FullMethodName                     = "/api.v1.HttpApi/GetTags"
	HttpApi_GetCategories_FullMethodName               = "/api.v1.HttpApi/GetCategories"
	HttpApi_GetPaymasterData_FullMethodName            = "/api.v1.HttpApi/GetPaymasterData"
	HttpApi_GetUserNotifications_FullMethodName        = "/api.v1.HttpApi/GetUserNotifications"
	HttpApi_MarkNotificationsAsRead_FullMethodName     = "/api.v1.HttpApi/MarkNotificationsAsRead"
	HttpApi_GetInviteUserList_FullMethodName           = "/api.v1.HttpApi/GetInviteUserList"
	HttpApi_GetUserTransactions_FullMethodName         = "/api.v1.HttpApi/GetUserTransactions"
	HttpApi_GetBaseTokenConfig_FullMethodName          = "/api.v1.HttpApi/GetBaseTokenConfig"
	HttpApi_GetBanners_FullMethodName                  = "/api.v1.HttpApi/GetBanners"
	HttpApi_GetSections_FullMethodName                 = "/api.v1.HttpApi/GetSections"
	HttpApi_GetTasks_FullMethodName                    = "/api.v1.HttpApi/GetTasks"
	HttpApi_ClaimTaskReward_FullMethodName             = "/api.v1.HttpApi/ClaimTaskReward"
	HttpApi_ShareTaskDone_FullMethodName               = "/api.v1.HttpApi/ShareTaskDone"
	HttpApi_Translate_FullMethodName                   = "/api.v1.HttpApi/Translate"
	HttpApi_GetLeaderboard_FullMethodName              = "/api.v1.HttpApi/GetLeaderboard"
	HttpApi_GetEventDetail_FullMethodName              = "/api.v1.HttpApi/GetEventDetail"
	HttpApi_GetEvents_FullMethodName                   = "/api.v1.HttpApi/GetEvents"
)

// HttpApiClient is the client API for HttpApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HttpApi 服务
// 市场的API接口，包括用户管理、市场交易、基础工具等功能
type HttpApiClient interface {
	// 用户登录 每次在登录后调用 需要登录态didtoken need_auth = true
	// 没找到用户则自动创建 返回用户uid
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// 设置用户头像 need_auth = true
	SetAvatar(ctx context.Context, in *SetAvatarRequest, opts ...grpc.CallOption) (*SetAvatarReply, error)
	// 设置用户名称 need_auth = true
	SetName(ctx context.Context, in *SetNameRequest, opts ...grpc.CallOption) (*SetNameReply, error)
	// 设置用户描述 need_auth = true
	SetDescription(ctx context.Context, in *SetDescriptionRequest, opts ...grpc.CallOption) (*SetDescriptionReply, error)
	// 下单交易 need_auth = true
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderReply, error)
	// 领取市场结果 need_auth = true
	ClaimMarketResult(ctx context.Context, in *ClaimMarketResultRequest, opts ...grpc.CallOption) (*ClaimMarketResultReply, error)
	// 转账基础代币 need_auth = true
	TransferBaseToken(ctx context.Context, in *TransferBaseTokenRequest, opts ...grpc.CallOption) (*TransferBaseTokenReply, error)
	// 关注市场 need_auth = true
	FollowMarket(ctx context.Context, in *FollowMarketRequest, opts ...grpc.CallOption) (*FollowMarketReply, error)
	// 取消关注市场 need_auth = true
	UnfollowMarket(ctx context.Context, in *UnfollowMarketRequest, opts ...grpc.CallOption) (*UnfollowMarketReply, error)
	// 上传文件 need_auth = true   上传文件返回访问的key(非完整url)
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileReply, error)
	// 下载文件 need_auth = false
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*DownloadFileReply, error)
	// 发布帖子 need_auth = true
	PublishPost(ctx context.Context, in *PublishPostRequest, opts ...grpc.CallOption) (*PublishPostReply, error)
	// 发布评论 need_auth = true
	PublishComment(ctx context.Context, in *PublishCommentRequest, opts ...grpc.CallOption) (*PublishCommentReply, error)
	// 点赞 need_auth = true
	LikeContent(ctx context.Context, in *LikeContentRequest, opts ...grpc.CallOption) (*LikeContentReply, error)
	// 取消点赞 need_auth = true
	UnlikeContent(ctx context.Context, in *UnlikeContentRequest, opts ...grpc.CallOption) (*UnlikeContentReply, error)
	// 关注用户 need_auth = true
	FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserReply, error)
	// 取消关注用户 need_auth = true
	UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserReply, error)
	// 获取自己关注的市场列表 need_auth = true
	GetFollowMarkets(ctx context.Context, in *GetFollowMarketsRequest, opts ...grpc.CallOption) (*GetFollowMarketsReply, error)
	// 获取持仓的市场列表（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
	GetHoldingPositionsMarket(ctx context.Context, in *GetHoldingPositionsMarketRequest, opts ...grpc.CallOption) (*GetHoldingPositionsMarketReply, error)
	// 获取热门市场列表 need_auth = false
	GetHotMarkets(ctx context.Context, in *GetHotMarketsRequest, opts ...grpc.CallOption) (*GetHotMarketsReply, error)
	// 获取市场详情 代币信息 与当前价格 need_auth = false
	GetMarketDetail(ctx context.Context, in *GetMarketDetailRequest, opts ...grpc.CallOption) (*GetMarketDetailReply, error)
	// 获取市场交易记录 need_auth = false
	GetMarketTrades(ctx context.Context, in *GetMarketTradesRequest, opts ...grpc.CallOption) (*GetMarketTradesReply, error)
	// 查看交易记录 可以看自己 也可以看别人 need_auth = false
	GetUserTrades(ctx context.Context, in *GetUserTradesRequest, opts ...grpc.CallOption) (*GetUserTradesReply, error)
	// 获取市场帖子列表 need_auth = false
	GetMarketPosts(ctx context.Context, in *GetMarketPostsRequest, opts ...grpc.CallOption) (*GetMarketPostsReply, error)
	// 获取评论区 root_uuid为空只获取根评论 root_uuid不为空只获取该根评论下的二级评论(回复) need_auth = false
	GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsReply, error)
	// 获取用户持仓信息 可以看自己 也可以看别人 need_auth = false
	GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsReply, error)
	// 获取用户基础信息(可以看自己 也可以看别人) need_auth = false
	GetUserBaseInfo(ctx context.Context, in *GetUserBaseInfoRequest, opts ...grpc.CallOption) (*GetUserBaseInfoReply, error)
	// 获取用户自身的当前资产信息 need_auth = false
	GetUserAssetInfo(ctx context.Context, in *GetUserAssetInfoRequest, opts ...grpc.CallOption) (*GetUserAssetInfoReply, error)
	// 搜索 支持市场 用户 搜索  need_auth = false
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error)
	// 查看用户资产历史变化（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
	GetUserAssetHistory(ctx context.Context, in *GetUserAssetHistoryRequest, opts ...grpc.CallOption) (*GetUserAssetHistoryReply, error)
	// 获取市场期权价格历史 need_auth = false
	GetMarketOptionPriceHistory(ctx context.Context, in *GetMarketOptionPriceHistoryRequest, opts ...grpc.CallOption) (*GetMarketOptionPriceHistoryReply, error)
	// 首页获取市场列表 need_auth = false
	GetMarkets(ctx context.Context, in *GetMarketsRequest, opts ...grpc.CallOption) (*GetMarketsReply, error)
	// 获取标签列表 need_auth = false
	GetTags(ctx context.Context, in *GetTagsRequest, opts ...grpc.CallOption) (*GetTagsReply, error)
	// 获取市场分类列表 need_auth = false
	GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesReply, error)
	// 获取paymaster数据 need_auth = true
	GetPaymasterData(ctx context.Context, in *GetPaymasterDataRequest, opts ...grpc.CallOption) (*GetPaymasterDataReply, error)
	// 获取用户通知列表 need_auth = true
	GetUserNotifications(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*GetUserNotificationsReply, error)
	// 标记用户的通知为已读 need_auth = true
	MarkNotificationsAsRead(ctx context.Context, in *MarkNotificationsAsReadRequest, opts ...grpc.CallOption) (*MarkNotificationsAsReadReply, error)
	// 获取邀请用户列表 need_auth = true
	GetInviteUserList(ctx context.Context, in *GetInviteUserListRequest, opts ...grpc.CallOption) (*GetInviteUserListReply, error)
	// 获取用户交易记录 need_auth = true
	GetUserTransactions(ctx context.Context, in *GetUserTransactionsRequest, opts ...grpc.CallOption) (*GetUserTransactionsReply, error)
	// 获取基础代币配置 need_auth = false
	GetBaseTokenConfig(ctx context.Context, in *GetBaseTokenConfigRequest, opts ...grpc.CallOption) (*GetBaseTokenConfigReply, error)
	// 获取banner列表 need_auth = false
	GetBanners(ctx context.Context, in *GetBannersRequest, opts ...grpc.CallOption) (*GetBannersReply, error)
	// 获取section列表 need_auth = false
	GetSections(ctx context.Context, in *GetSectionsRequest, opts ...grpc.CallOption) (*GetSectionsReply, error)
	GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksReply, error)
	ClaimTaskReward(ctx context.Context, in *ClaimTaskRewardRequest, opts ...grpc.CallOption) (*ClaimTaskRewardReply, error)
	ShareTaskDone(ctx context.Context, in *ShareTaskDoneRequest, opts ...grpc.CallOption) (*ShareTaskDoneReply, error)
	Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateReply, error)
	GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error)
	// 获取 Event 详情（含子市场列表） need_auth = false
	GetEventDetail(ctx context.Context, in *GetEventDetailRequest, opts ...grpc.CallOption) (*GetEventDetailReply, error)
	// 获取 Event 列表（分页） need_auth = false
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsReply, error)
}

type httpApiClient struct {
	cc grpc.ClientConnInterface
}

func NewHttpApiClient(cc grpc.ClientConnInterface) HttpApiClient {
	return &httpApiClient{cc}
}

func (c *httpApiClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, HttpApi_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) SetAvatar(ctx context.Context, in *SetAvatarRequest, opts ...grpc.CallOption) (*SetAvatarReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAvatarReply)
	err := c.cc.Invoke(ctx, HttpApi_SetAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) SetName(ctx context.Context, in *SetNameRequest, opts ...grpc.CallOption) (*SetNameReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNameReply)
	err := c.cc.Invoke(ctx, HttpApi_SetName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) SetDescription(ctx context.Context, in *SetDescriptionRequest, opts ...grpc.CallOption) (*SetDescriptionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDescriptionReply)
	err := c.cc.Invoke(ctx, HttpApi_SetDescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceOrderReply)
	err := c.cc.Invoke(ctx, HttpApi_PlaceOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) ClaimMarketResult(ctx context.Context, in *ClaimMarketResultRequest, opts ...grpc.CallOption) (*ClaimMarketResultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimMarketResultReply)
	err := c.cc.Invoke(ctx, HttpApi_ClaimMarketResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) TransferBaseToken(ctx context.Context, in *TransferBaseTokenRequest, opts ...grpc.CallOption) (*TransferBaseTokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferBaseTokenReply)
	err := c.cc.Invoke(ctx, HttpApi_TransferBaseToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) FollowMarket(ctx context.Context, in *FollowMarketRequest, opts ...grpc.CallOption) (*FollowMarketReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowMarketReply)
	err := c.cc.Invoke(ctx, HttpApi_FollowMarket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) UnfollowMarket(ctx context.Context, in *UnfollowMarketRequest, opts ...grpc.CallOption) (*UnfollowMarketReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowMarketReply)
	err := c.cc.Invoke(ctx, HttpApi_UnfollowMarket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileReply)
	err := c.cc.Invoke(ctx, HttpApi_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*DownloadFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadFileReply)
	err := c.cc.Invoke(ctx, HttpApi_DownloadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) PublishPost(ctx context.Context, in *PublishPostRequest, opts ...grpc.CallOption) (*PublishPostReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishPostReply)
	err := c.cc.Invoke(ctx, HttpApi_PublishPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) PublishComment(ctx context.Context, in *PublishCommentRequest, opts ...grpc.CallOption) (*PublishCommentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishCommentReply)
	err := c.cc.Invoke(ctx, HttpApi_PublishComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) LikeContent(ctx context.Context, in *LikeContentRequest, opts ...grpc.CallOption) (*LikeContentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeContentReply)
	err := c.cc.Invoke(ctx, HttpApi_LikeContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) UnlikeContent(ctx context.Context, in *UnlikeContentRequest, opts ...grpc.CallOption) (*UnlikeContentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlikeContentReply)
	err := c.cc.Invoke(ctx, HttpApi_UnlikeContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowUserReply)
	err := c.cc.Invoke(ctx, HttpApi_FollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowUserReply)
	err := c.cc.Invoke(ctx, HttpApi_UnfollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetFollowMarkets(ctx context.Context, in *GetFollowMarketsRequest, opts ...grpc.CallOption) (*GetFollowMarketsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowMarketsReply)
	err := c.cc.Invoke(ctx, HttpApi_GetFollowMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetHoldingPositionsMarket(ctx context.Context, in *GetHoldingPositionsMarketRequest, opts ...grpc.CallOption) (*GetHoldingPositionsMarketReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHoldingPositionsMarketReply)
	err := c.cc.Invoke(ctx, HttpApi_GetHoldingPositionsMarket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetHotMarkets(ctx context.Context, in *GetHotMarketsRequest, opts ...grpc.CallOption) (*GetHotMarketsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHotMarketsReply)
	err := c.cc.Invoke(ctx, HttpApi_GetHotMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetMarketDetail(ctx context.Context, in *GetMarketDetailRequest, opts ...grpc.CallOption) (*GetMarketDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketDetailReply)
	err := c.cc.Invoke(ctx, HttpApi_GetMarketDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetMarketTrades(ctx context.Context, in *GetMarketTradesRequest, opts ...grpc.CallOption) (*GetMarketTradesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketTradesReply)
	err := c.cc.Invoke(ctx, HttpApi_GetMarketTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetUserTrades(ctx context.Context, in *GetUserTradesRequest, opts ...grpc.CallOption) (*GetUserTradesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTradesReply)
	err := c.cc.Invoke(ctx, HttpApi_GetUserTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetMarketPosts(ctx context.Context, in *GetMarketPostsRequest, opts ...grpc.CallOption) (*GetMarketPostsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketPostsReply)
	err := c.cc.Invoke(ctx, HttpApi_GetMarketPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommentsReply)
	err := c.cc.Invoke(ctx, HttpApi_GetComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPositionsReply)
	err := c.cc.Invoke(ctx, HttpApi_GetUserPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetUserBaseInfo(ctx context.Context, in *GetUserBaseInfoRequest, opts ...grpc.CallOption) (*GetUserBaseInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserBaseInfoReply)
	err := c.cc.Invoke(ctx, HttpApi_GetUserBaseInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetUserAssetInfo(ctx context.Context, in *GetUserAssetInfoRequest, opts ...grpc.CallOption) (*GetUserAssetInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAssetInfoReply)
	err := c.cc.Invoke(ctx, HttpApi_GetUserAssetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchReply)
	err := c.cc.Invoke(ctx, HttpApi_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetUserAssetHistory(ctx context.Context, in *GetUserAssetHistoryRequest, opts ...grpc.CallOption) (*GetUserAssetHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAssetHistoryReply)
	err := c.cc.Invoke(ctx, HttpApi_GetUserAssetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetMarketOptionPriceHistory(ctx context.Context, in *GetMarketOptionPriceHistoryRequest, opts ...grpc.CallOption) (*GetMarketOptionPriceHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketOptionPriceHistoryReply)
	err := c.cc.Invoke(ctx, HttpApi_GetMarketOptionPriceHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetMarkets(ctx context.Context, in *GetMarketsRequest, opts ...grpc.CallOption) (*GetMarketsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketsReply)
	err := c.cc.Invoke(ctx, HttpApi_GetMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetTags(ctx context.Context, in *GetTagsRequest, opts ...grpc.CallOption) (*GetTagsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTagsReply)
	err := c.cc.Invoke(ctx, HttpApi_GetTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoriesReply)
	err := c.cc.Invoke(ctx, HttpApi_GetCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetPaymasterData(ctx context.Context, in *GetPaymasterDataRequest, opts ...grpc.CallOption) (*GetPaymasterDataReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymasterDataReply)
	err := c.cc.Invoke(ctx, HttpApi_GetPaymasterData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetUserNotifications(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*GetUserNotificationsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserNotificationsReply)
	err := c.cc.Invoke(ctx, HttpApi_GetUserNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) MarkNotificationsAsRead(ctx context.Context, in *MarkNotificationsAsReadRequest, opts ...grpc.CallOption) (*MarkNotificationsAsReadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkNotificationsAsReadReply)
	err := c.cc.Invoke(ctx, HttpApi_MarkNotificationsAsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetInviteUserList(ctx context.Context, in *GetInviteUserListRequest, opts ...grpc.CallOption) (*GetInviteUserListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInviteUserListReply)
	err := c.cc.Invoke(ctx, HttpApi_GetInviteUserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetUserTransactions(ctx context.Context, in *GetUserTransactionsRequest, opts ...grpc.CallOption) (*GetUserTransactionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTransactionsReply)
	err := c.cc.Invoke(ctx, HttpApi_GetUserTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetBaseTokenConfig(ctx context.Context, in *GetBaseTokenConfigRequest, opts ...grpc.CallOption) (*GetBaseTokenConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBaseTokenConfigReply)
	err := c.cc.Invoke(ctx, HttpApi_GetBaseTokenConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetBanners(ctx context.Context, in *GetBannersRequest, opts ...grpc.CallOption) (*GetBannersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBannersReply)
	err := c.cc.Invoke(ctx, HttpApi_GetBanners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetSections(ctx context.Context, in *GetSectionsRequest, opts ...grpc.CallOption) (*GetSectionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSectionsReply)
	err := c.cc.Invoke(ctx, HttpApi_GetSections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTasksReply)
	err := c.cc.Invoke(ctx, HttpApi_GetTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) ClaimTaskReward(ctx context.Context, in *ClaimTaskRewardRequest, opts ...grpc.CallOption) (*ClaimTaskRewardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimTaskRewardReply)
	err := c.cc.Invoke(ctx, HttpApi_ClaimTaskReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) ShareTaskDone(ctx context.Context, in *ShareTaskDoneRequest, opts ...grpc.CallOption) (*ShareTaskDoneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareTaskDoneReply)
	err := c.cc.Invoke(ctx, HttpApi_ShareTaskDone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranslateReply)
	err := c.cc.Invoke(ctx, HttpApi_Translate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderboardResponse)
	err := c.cc.Invoke(ctx, HttpApi_GetLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetEventDetail(ctx context.Context, in *GetEventDetailRequest, opts ...grpc.CallOption) (*GetEventDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventDetailReply)
	err := c.cc.Invoke(ctx, HttpApi_GetEventDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpApiClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsReply)
	err := c.cc.Invoke(ctx, HttpApi_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HttpApiServer is the server API for HttpApi service.
// All implementations must embed UnimplementedHttpApiServer
// for forward compatibility.
//
// HttpApi 服务
// 市场的API接口，包括用户管理、市场交易、基础工具等功能
type HttpApiServer interface {
	// 用户登录 每次在登录后调用 需要登录态didtoken need_auth = true
	// 没找到用户则自动创建 返回用户uid
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// 设置用户头像 need_auth = true
	SetAvatar(context.Context, *SetAvatarRequest) (*SetAvatarReply, error)
	// 设置用户名称 need_auth = true
	SetName(context.Context, *SetNameRequest) (*SetNameReply, error)
	// 设置用户描述 need_auth = true
	SetDescription(context.Context, *SetDescriptionRequest) (*SetDescriptionReply, error)
	// 下单交易 need_auth = true
	PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderReply, error)
	// 领取市场结果 need_auth = true
	ClaimMarketResult(context.Context, *ClaimMarketResultRequest) (*ClaimMarketResultReply, error)
	// 转账基础代币 need_auth = true
	TransferBaseToken(context.Context, *TransferBaseTokenRequest) (*TransferBaseTokenReply, error)
	// 关注市场 need_auth = true
	FollowMarket(context.Context, *FollowMarketRequest) (*FollowMarketReply, error)
	// 取消关注市场 need_auth = true
	UnfollowMarket(context.Context, *UnfollowMarketRequest) (*UnfollowMarketReply, error)
	// 上传文件 need_auth = true   上传文件返回访问的key(非完整url)
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileReply, error)
	// 下载文件 need_auth = false
	DownloadFile(context.Context, *DownloadFileRequest) (*DownloadFileReply, error)
	// 发布帖子 need_auth = true
	PublishPost(context.Context, *PublishPostRequest) (*PublishPostReply, error)
	// 发布评论 need_auth = true
	PublishComment(context.Context, *PublishCommentRequest) (*PublishCommentReply, error)
	// 点赞 need_auth = true
	LikeContent(context.Context, *LikeContentRequest) (*LikeContentReply, error)
	// 取消点赞 need_auth = true
	UnlikeContent(context.Context, *UnlikeContentRequest) (*UnlikeContentReply, error)
	// 关注用户 need_auth = true
	FollowUser(context.Context, *FollowUserRequest) (*FollowUserReply, error)
	// 取消关注用户 need_auth = true
	UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserReply, error)
	// 获取自己关注的市场列表 need_auth = true
	GetFollowMarkets(context.Context, *GetFollowMarketsRequest) (*GetFollowMarketsReply, error)
	// 获取持仓的市场列表（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
	GetHoldingPositionsMarket(context.Context, *GetHoldingPositionsMarketRequest) (*GetHoldingPositionsMarketReply, error)
	// 获取热门市场列表 need_auth = false
	GetHotMarkets(context.Context, *GetHotMarketsRequest) (*GetHotMarketsReply, error)
	// 获取市场详情 代币信息 与当前价格 need_auth = false
	GetMarketDetail(context.Context, *GetMarketDetailRequest) (*GetMarketDetailReply, error)
	// 获取市场交易记录 need_auth = false
	GetMarketTrades(context.Context, *GetMarketTradesRequest) (*GetMarketTradesReply, error)
	// 查看交易记录 可以看自己 也可以看别人 need_auth = false
	GetUserTrades(context.Context, *GetUserTradesRequest) (*GetUserTradesReply, error)
	// 获取市场帖子列表 need_auth = false
	GetMarketPosts(context.Context, *GetMarketPostsRequest) (*GetMarketPostsReply, error)
	// 获取评论区 root_uuid为空只获取根评论 root_uuid不为空只获取该根评论下的二级评论(回复) need_auth = false
	GetComments(context.Context, *GetCommentsRequest) (*GetCommentsReply, error)
	// 获取用户持仓信息 可以看自己 也可以看别人 need_auth = false
	GetUserPositions(context.Context, *GetUserPositionsRequest) (*GetUserPositionsReply, error)
	// 获取用户基础信息(可以看自己 也可以看别人) need_auth = false
	GetUserBaseInfo(context.Context, *GetUserBaseInfoRequest) (*GetUserBaseInfoReply, error)
	// 获取用户自身的当前资产信息 need_auth = false
	GetUserAssetInfo(context.Context, *GetUserAssetInfoRequest) (*GetUserAssetInfoReply, error)
	// 搜索 支持市场 用户 搜索  need_auth = false
	Search(context.Context, *SearchRequest) (*SearchReply, error)
	// 查看用户资产历史变化（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
	GetUserAssetHistory(context.Context, *GetUserAssetHistoryRequest) (*GetUserAssetHistoryReply, error)
	// 获取市场期权价格历史 need_auth = false
	GetMarketOptionPriceHistory(context.Context, *GetMarketOptionPriceHistoryRequest) (*GetMarketOptionPriceHistoryReply, error)
	// 首页获取市场列表 need_auth = false
	GetMarkets(context.Context, *GetMarketsRequest) (*GetMarketsReply, error)
	// 获取标签列表 need_auth = false
	GetTags(context.Context, *GetTagsRequest) (*GetTagsReply, error)
	// 获取市场分类列表 need_auth = false
	GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesReply, error)
	// 获取paymaster数据 need_auth = true
	GetPaymasterData(context.Context, *GetPaymasterDataRequest) (*GetPaymasterDataReply, error)
	// 获取用户通知列表 need_auth = true
	GetUserNotifications(context.Context, *GetUserNotificationsRequest) (*GetUserNotificationsReply, error)
	// 标记用户的通知为已读 need_auth = true
	MarkNotificationsAsRead(context.Context, *MarkNotificationsAsReadRequest) (*MarkNotificationsAsReadReply, error)
	// 获取邀请用户列表 need_auth = true
	GetInviteUserList(context.Context, *GetInviteUserListRequest) (*GetInviteUserListReply, error)
	// 获取用户交易记录 need_auth = true
	GetUserTransactions(context.Context, *GetUserTransactionsRequest) (*GetUserTransactionsReply, error)
	// 获取基础代币配置 need_auth = false
	GetBaseTokenConfig(context.Context, *GetBaseTokenConfigRequest) (*GetBaseTokenConfigReply, error)
	// 获取banner列表 need_auth = false
	GetBanners(context.Context, *GetBannersRequest) (*GetBannersReply, error)
	// 获取section列表 need_auth = false
	GetSections(context.Context, *GetSectionsRequest) (*GetSectionsReply, error)
	GetTasks(context.Context, *GetTasksRequest) (*GetTasksReply, error)
	ClaimTaskReward(context.Context, *ClaimTaskRewardRequest) (*ClaimTaskRewardReply, error)
	ShareTaskDone(context.Context, *ShareTaskDoneRequest) (*ShareTaskDoneReply, error)
	Translate(context.Context, *TranslateRequest) (*TranslateReply, error)
	GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error)
	// 获取 Event 详情（含子市场列表） need_auth = false
	GetEventDetail(context.Context, *GetEventDetailRequest) (*GetEventDetailReply, error)
	// 获取 Event 列表（分页） need_auth = false
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsReply, error)
	mustEmbedUnimplementedHttpApiServer()
}

// UnimplementedHttpApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHttpApiServer struct{}

func (UnimplementedHttpApiServer) Login(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedHttpApiServer) SetAvatar(context.Context, *SetAvatarRequest) (*SetAvatarReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAvatar not implemented")
}
func (UnimplementedHttpApiServer) SetName(context.Context, *SetNameRequest) (*SetNameReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetName not implemented")
}
func (UnimplementedHttpApiServer) SetDescription(context.Context, *SetDescriptionRequest) (*SetDescriptionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDescription not implemented")
}
func (UnimplementedHttpApiServer) PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedHttpApiServer) ClaimMarketResult(context.Context, *ClaimMarketResultRequest) (*ClaimMarketResultReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimMarketResult not implemented")
}
func (UnimplementedHttpApiServer) TransferBaseToken(context.Context, *TransferBaseTokenRequest) (*TransferBaseTokenReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferBaseToken not implemented")
}
func (UnimplementedHttpApiServer) FollowMarket(context.Context, *FollowMarketRequest) (*FollowMarketReply, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowMarket not implemented")
}
func (UnimplementedHttpApiServer) UnfollowMarket(context.Context, *UnfollowMarketRequest) (*UnfollowMarketReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UnfollowMarket not implemented")
}
func (UnimplementedHttpApiServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedHttpApiServer) DownloadFile(context.Context, *DownloadFileRequest) (*DownloadFileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedHttpApiServer) PublishPost(context.Context, *PublishPostRequest) (*PublishPostReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishPost not implemented")
}
func (UnimplementedHttpApiServer) PublishComment(context.Context, *PublishCommentRequest) (*PublishCommentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishComment not implemented")
}
func (UnimplementedHttpApiServer) LikeContent(context.Context, *LikeContentRequest) (*LikeContentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeContent not implemented")
}
func (UnimplementedHttpApiServer) UnlikeContent(context.Context, *UnlikeContentRequest) (*UnlikeContentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlikeContent not implemented")
}
func (UnimplementedHttpApiServer) FollowUser(context.Context, *FollowUserRequest) (*FollowUserReply, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowUser not implemented")
}
func (UnimplementedHttpApiServer) UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UnfollowUser not implemented")
}
func (UnimplementedHttpApiServer) GetFollowMarkets(context.Context, *GetFollowMarketsRequest) (*GetFollowMarketsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowMarkets not implemented")
}
func (UnimplementedHttpApiServer) GetHoldingPositionsMarket(context.Context, *GetHoldingPositionsMarketRequest) (*GetHoldingPositionsMarketReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHoldingPositionsMarket not implemented")
}
func (UnimplementedHttpApiServer) GetHotMarkets(context.Context, *GetHotMarketsRequest) (*GetHotMarketsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHotMarkets not implemented")
}
func (UnimplementedHttpApiServer) GetMarketDetail(context.Context, *GetMarketDetailRequest) (*GetMarketDetailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarketDetail not implemented")
}
func (UnimplementedHttpApiServer) GetMarketTrades(context.Context, *GetMarketTradesRequest) (*GetMarketTradesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarketTrades not implemented")
}
func (UnimplementedHttpApiServer) GetUserTrades(context.Context, *GetUserTradesRequest) (*GetUserTradesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTrades not implemented")
}
func (UnimplementedHttpApiServer) GetMarketPosts(context.Context, *GetMarketPostsRequest) (*GetMarketPostsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarketPosts not implemented")
}
func (UnimplementedHttpApiServer) GetComments(context.Context, *GetCommentsRequest) (*GetCommentsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComments not implemented")
}
func (UnimplementedHttpApiServer) GetUserPositions(context.Context, *GetUserPositionsRequest) (*GetUserPositionsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPositions not implemented")
}
func (UnimplementedHttpApiServer) GetUserBaseInfo(context.Context, *GetUserBaseInfoRequest) (*GetUserBaseInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserBaseInfo not implemented")
}
func (UnimplementedHttpApiServer) GetUserAssetInfo(context.Context, *GetUserAssetInfoRequest) (*GetUserAssetInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAssetInfo not implemented")
}
func (UnimplementedHttpApiServer) Search(context.Context, *SearchRequest) (*SearchReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedHttpApiServer) GetUserAssetHistory(context.Context, *GetUserAssetHistoryRequest) (*GetUserAssetHistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAssetHistory not implemented")
}
func (UnimplementedHttpApiServer) GetMarketOptionPriceHistory(context.Context, *GetMarketOptionPriceHistoryRequest) (*GetMarketOptionPriceHistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarketOptionPriceHistory not implemented")
}
func (UnimplementedHttpApiServer) GetMarkets(context.Context, *GetMarketsRequest) (*GetMarketsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarkets not implemented")
}
func (UnimplementedHttpApiServer) GetTags(context.Context, *GetTagsRequest) (*GetTagsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTags not implemented")
}
func (UnimplementedHttpApiServer) GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategories not implemented")
}
func (UnimplementedHttpApiServer) GetPaymasterData(context.Context, *GetPaymasterDataRequest) (*GetPaymasterDataReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymasterData not implemented")
}
func (UnimplementedHttpApiServer) GetUserNotifications(context.Context, *GetUserNotificationsRequest) (*GetUserNotificationsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserNotifications not implemented")
}
func (UnimplementedHttpApiServer) MarkNotificationsAsRead(context.Context, *MarkNotificationsAsReadRequest) (*MarkNotificationsAsReadReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkNotificationsAsRead not implemented")
}
func (UnimplementedHttpApiServer) GetInviteUserList(context.Context, *GetInviteUserListRequest) (*GetInviteUserListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInviteUserList not implemented")
}
func (UnimplementedHttpApiServer) GetUserTransactions(context.Context, *GetUserTransactionsRequest) (*GetUserTransactionsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTransactions not implemented")
}
func (UnimplementedHttpApiServer) GetBaseTokenConfig(context.Context, *GetBaseTokenConfigRequest) (*GetBaseTokenConfigReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBaseTokenConfig not implemented")
}
func (UnimplementedHttpApiServer) GetBanners(context.Context, *GetBannersRequest) (*GetBannersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBanners not implemented")
}
func (UnimplementedHttpApiServer) GetSections(context.Context, *GetSectionsRequest) (*GetSectionsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSections not implemented")
}
func (UnimplementedHttpApiServer) GetTasks(context.Context, *GetTasksRequest) (*GetTasksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTasks not implemented")
}
func (UnimplementedHttpApiServer) ClaimTaskReward(context.Context, *ClaimTaskRewardRequest) (*ClaimTaskRewardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimTaskReward not implemented")
}
func (UnimplementedHttpApiServer) ShareTaskDone(context.Context, *ShareTaskDoneRequest) (*ShareTaskDoneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareTaskDone not implemented")
}
func (UnimplementedHttpApiServer) Translate(context.Context, *TranslateRequest) (*TranslateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Translate not implemented")
}
func (UnimplementedHttpApiServer) GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeaderboard not implemented")
}
func (UnimplementedHttpApiServer) GetEventDetail(context.Context, *GetEventDetailRequest) (*GetEventDetailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventDetail not implemented")
}
func (UnimplementedHttpApiServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedHttpApiServer) mustEmbedUnimplementedHttpApiServer() {}
func (UnimplementedHttpApiServer) testEmbeddedByValue()                 {}

// UnsafeHttpApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HttpApiServer will
// result in compilation errors.
type UnsafeHttpApiServer interface {
	mustEmbedUnimplementedHttpApiServer()
}

func RegisterHttpApiServer(s grpc.ServiceRegistrar, srv HttpApiServer) {
	// If the following call panics, it indicates UnimplementedHttpApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HttpApi_ServiceDesc, srv)
}

func _HttpApi_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_SetAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).SetAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_SetAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).SetAvatar(ctx, req.(*SetAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_SetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).SetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_SetName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).SetName(ctx, req.(*SetNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_SetDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).SetDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_SetDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).SetDescription(ctx, req.(*SetDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_PlaceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_ClaimMarketResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimMarketResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).ClaimMarketResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_ClaimMarketResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).ClaimMarketResult(ctx, req.(*ClaimMarketResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_TransferBaseToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferBaseTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).TransferBaseToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_TransferBaseToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).TransferBaseToken(ctx, req.(*TransferBaseTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_FollowMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).FollowMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_FollowMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).FollowMarket(ctx, req.(*FollowMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_UnfollowMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).UnfollowMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_UnfollowMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).UnfollowMarket(ctx, req.(*UnfollowMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_DownloadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).DownloadFile(ctx, req.(*DownloadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_PublishPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).PublishPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_PublishPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).PublishPost(ctx, req.(*PublishPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_PublishComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).PublishComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_PublishComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).PublishComment(ctx, req.(*PublishCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_LikeContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).LikeContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_LikeContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).LikeContent(ctx, req.(*LikeContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_UnlikeContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).UnlikeContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_UnlikeContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).UnlikeContent(ctx, req.(*UnlikeContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_FollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).FollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_UnfollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).UnfollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_UnfollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).UnfollowUser(ctx, req.(*UnfollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetFollowMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetFollowMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetFollowMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetFollowMarkets(ctx, req.(*GetFollowMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetHoldingPositionsMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHoldingPositionsMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetHoldingPositionsMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetHoldingPositionsMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetHoldingPositionsMarket(ctx, req.(*GetHoldingPositionsMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetHotMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetHotMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetHotMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetHotMarkets(ctx, req.(*GetHotMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetMarketDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetMarketDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetMarketDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetMarketDetail(ctx, req.(*GetMarketDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetMarketTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetMarketTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetMarketTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetMarketTrades(ctx, req.(*GetMarketTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetUserTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetUserTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetUserTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetUserTrades(ctx, req.(*GetUserTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetMarketPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetMarketPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetMarketPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetMarketPosts(ctx, req.(*GetMarketPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetComments(ctx, req.(*GetCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetUserPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetUserPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetUserPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetUserPositions(ctx, req.(*GetUserPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetUserBaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBaseInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetUserBaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetUserBaseInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetUserBaseInfo(ctx, req.(*GetUserBaseInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetUserAssetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAssetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetUserAssetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetUserAssetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetUserAssetInfo(ctx, req.(*GetUserAssetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetUserAssetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAssetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetUserAssetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetUserAssetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetUserAssetHistory(ctx, req.(*GetUserAssetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetMarketOptionPriceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketOptionPriceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetMarketOptionPriceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetMarketOptionPriceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetMarketOptionPriceHistory(ctx, req.(*GetMarketOptionPriceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetMarkets(ctx, req.(*GetMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetTags(ctx, req.(*GetTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetCategories(ctx, req.(*GetCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetPaymasterData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymasterDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetPaymasterData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetPaymasterData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetPaymasterData(ctx, req.(*GetPaymasterDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetUserNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetUserNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetUserNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetUserNotifications(ctx, req.(*GetUserNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_MarkNotificationsAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationsAsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).MarkNotificationsAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_MarkNotificationsAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).MarkNotificationsAsRead(ctx, req.(*MarkNotificationsAsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetInviteUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInviteUserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetInviteUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetInviteUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetInviteUserList(ctx, req.(*GetInviteUserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetUserTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetUserTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetUserTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetUserTransactions(ctx, req.(*GetUserTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetBaseTokenConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBaseTokenConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetBaseTokenConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetBaseTokenConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetBaseTokenConfig(ctx, req.(*GetBaseTokenConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetBanners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBannersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetBanners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetBanners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetBanners(ctx, req.(*GetBannersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetSections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetSections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetSections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetSections(ctx, req.(*GetSectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetTasks(ctx, req.(*GetTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_ClaimTaskReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimTaskRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).ClaimTaskReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_ClaimTaskReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).ClaimTaskReward(ctx, req.(*ClaimTaskRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_ShareTaskDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareTaskDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).ShareTaskDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_ShareTaskDone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).ShareTaskDone(ctx, req.(*ShareTaskDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_Translate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).Translate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_Translate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).Translate(ctx, req.(*TranslateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetLeaderboard(ctx, req.(*GetLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetEventDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetEventDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetEventDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetEventDetail(ctx, req.(*GetEventDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpApi_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpApiServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpApi_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpApiServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HttpApi_ServiceDesc is the grpc.ServiceDesc for HttpApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HttpApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.HttpApi",
	HandlerType: (*HttpApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _HttpApi_Login_Handler,
		},
		{
			MethodName: "SetAvatar",
			Handler:    _HttpApi_SetAvatar_Handler,
		},
		{
			MethodName: "SetName",
			Handler:    _HttpApi_SetName_Handler,
		},
		{
			MethodName: "SetDescription",
			Handler:    _HttpApi_SetDescription_Handler,
		},
		{
			MethodName: "PlaceOrder",
			Handler:    _HttpApi_PlaceOrder_Handler,
		},
		{
			MethodName: "ClaimMarketResult",
			Handler:    _HttpApi_ClaimMarketResult_Handler,
		},
		{
			MethodName: "TransferBaseToken",
			Handler:    _HttpApi_TransferBaseToken_Handler,
		},
		{
			MethodName: "FollowMarket",
			Handler:    _HttpApi_FollowMarket_Handler,
		},
		{
			MethodName: "UnfollowMarket",
			Handler:    _HttpApi_UnfollowMarket_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _HttpApi_UploadFile_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _HttpApi_DownloadFile_Handler,
		},
		{
			MethodName: "PublishPost",
			Handler:    _HttpApi_PublishPost_Handler,
		},
		{
			MethodName: "PublishComment",
			Handler:    _HttpApi_PublishComment_Handler,
		},
		{
			MethodName: "LikeContent",
			Handler:    _HttpApi_LikeContent_Handler,
		},
		{
			MethodName: "UnlikeContent",
			Handler:    _HttpApi_UnlikeContent_Handler,
		},
		{
			MethodName: "FollowUser",
			Handler:    _HttpApi_FollowUser_Handler,
		},
		{
			MethodName: "UnfollowUser",
			Handler:    _HttpApi_UnfollowUser_Handler,
		},
		{
			MethodName: "GetFollowMarkets",
			Handler:    _HttpApi_GetFollowMarkets_Handler,
		},
		{
			MethodName: "GetHoldingPositionsMarket",
			Handler:    _HttpApi_GetHoldingPositionsMarket_Handler,
		},
		{
			MethodName: "GetHotMarkets",
			Handler:    _HttpApi_GetHotMarkets_Handler,
		},
		{
			MethodName: "GetMarketDetail",
			Handler:    _HttpApi_GetMarketDetail_Handler,
		},
		{
			MethodName: "GetMarketTrades",
			Handler:    _HttpApi_GetMarketTrades_Handler,
		},
		{
			MethodName: "GetUserTrades",
			Handler:    _HttpApi_GetUserTrades_Handler,
		},
		{
			MethodName: "GetMarketPosts",
			Handler:    _HttpApi_GetMarketPosts_Handler,
		},
		{
			MethodName: "GetComments",
			Handler:    _HttpApi_GetComments_Handler,
		},
		{
			MethodName: "GetUserPositions",
			Handler:    _HttpApi_GetUserPositions_Handler,
		},
		{
			MethodName: "GetUserBaseInfo",
			Handler:    _HttpApi_GetUserBaseInfo_Handler,
		},
		{
			MethodName: "GetUserAssetInfo",
			Handler:    _HttpApi_GetUserAssetInfo_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _HttpApi_Search_Handler,
		},
		{
			MethodName: "GetUserAssetHistory",
			Handler:    _HttpApi_GetUserAssetHistory_Handler,
		},
		{
			MethodName: "GetMarketOptionPriceHistory",
			Handler:    _HttpApi_GetMarketOptionPriceHistory_Handler,
		},
		{
			MethodName: "GetMarkets",
			Handler:    _HttpApi_GetMarkets_Handler,
		},
		{
			MethodName: "GetTags",
			Handler:    _HttpApi_GetTags_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _HttpApi_GetCategories_Handler,
		},
		{
			MethodName: "GetPaymasterData",
			Handler:    _HttpApi_GetPaymasterData_Handler,
		},
		{
			MethodName: "GetUserNotifications",
			Handler:    _HttpApi_GetUserNotifications_Handler,
		},
		{
			MethodName: "MarkNotificationsAsRead",
			Handler:    _HttpApi_MarkNotificationsAsRead_Handler,
		},
		{
			MethodName: "GetInviteUserList",
			Handler:    _HttpApi_GetInviteUserList_Handler,
		},
		{
			MethodName: "GetUserTransactions",
			Handler:    _HttpApi_GetUserTransactions_Handler,
		},
		{
			MethodName: "GetBaseTokenConfig",
			Handler:    _HttpApi_GetBaseTokenConfig_Handler,
		},
		{
			MethodName: "GetBanners",
			Handler:    _HttpApi_GetBanners_Handler,
		},
		{
			MethodName: "GetSections",
			Handler:    _HttpApi_GetSections_Handler,
		},
		{
			MethodName: "GetTasks",
			Handler:    _HttpApi_GetTasks_Handler,
		},
		{
			MethodName: "ClaimTaskReward",
			Handler:    _HttpApi_ClaimTaskReward_Handler,
		},
		{
			MethodName: "ShareTaskDone",
			Handler:    _HttpApi_ShareTaskDone_Handler,
		},
		{
			MethodName: "Translate",
			Handler:    _HttpApi_Translate_Handler,
		},
		{
			MethodName: "GetLeaderboard",
			Handler:    _HttpApi_GetLeaderboard_Handler,
		},
		{
			MethodName: "GetEventDetail",
			Handler:    _HttpApi_GetEventDetail_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _HttpApi_GetEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market-backend/v1/api.proto",
}
