// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: market-backend/v1/bayes.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BayesSse_Subscribe_FullMethodName   = "/bayes.v1.BayesSse/Subscribe"
	BayesSse_Unsubscribe_FullMethodName = "/bayes.v1.BayesSse/Unsubscribe"
)

// BayesSseClient is the client API for BayesSse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BayesSseClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeReply, error)
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeReply, error)
}

type bayesSseClient struct {
	cc grpc.ClientConnInterface
}

func NewBayesSseClient(cc grpc.ClientConnInterface) BayesSseClient {
	return &bayesSseClient{cc}
}

func (c *bayesSseClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeReply, error) {
	out := new(SubscribeReply)
	err := c.cc.Invoke(ctx, BayesSse_Subscribe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesSseClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeReply, error) {
	out := new(UnsubscribeReply)
	err := c.cc.Invoke(ctx, BayesSse_Unsubscribe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BayesSseServer is the server API for BayesSse service.
// All implementations must embed UnimplementedBayesSseServer
// for forward compatibility
type BayesSseServer interface {
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeReply, error)
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeReply, error)
	mustEmbedUnimplementedBayesSseServer()
}

// UnimplementedBayesSseServer must be embedded to have forward compatible implementations.
type UnimplementedBayesSseServer struct {
}

func (UnimplementedBayesSseServer) Subscribe(context.Context, *SubscribeRequest) (*SubscribeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedBayesSseServer) Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedBayesSseServer) mustEmbedUnimplementedBayesSseServer() {}

// UnsafeBayesSseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BayesSseServer will
// result in compilation errors.
type UnsafeBayesSseServer interface {
	mustEmbedUnimplementedBayesSseServer()
}

func RegisterBayesSseServer(s grpc.ServiceRegistrar, srv BayesSseServer) {
	s.RegisterService(&BayesSse_ServiceDesc, srv)
}

func _BayesSse_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesSseServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesSse_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesSseServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesSse_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesSseServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesSse_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesSseServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BayesSse_ServiceDesc is the grpc.ServiceDesc for BayesSse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BayesSse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bayes.v1.BayesSse",
	HandlerType: (*BayesSseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _BayesSse_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _BayesSse_Unsubscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market-backend/v1/bayes.proto",
}

const (
	BayesHttp_Login_FullMethodName                       = "/bayes.v1.BayesHttp/Login"
	BayesHttp_SetAvatar_FullMethodName                   = "/bayes.v1.BayesHttp/SetAvatar"
	BayesHttp_SetName_FullMethodName                     = "/bayes.v1.BayesHttp/SetName"
	BayesHttp_SetDescription_FullMethodName              = "/bayes.v1.BayesHttp/SetDescription"
	BayesHttp_PlaceOrder_FullMethodName                  = "/bayes.v1.BayesHttp/PlaceOrder"
	BayesHttp_ClaimMarketResult_FullMethodName           = "/bayes.v1.BayesHttp/ClaimMarketResult"
	BayesHttp_TransferBaseToken_FullMethodName           = "/bayes.v1.BayesHttp/TransferBaseToken"
	BayesHttp_FollowMarket_FullMethodName                = "/bayes.v1.BayesHttp/FollowMarket"
	BayesHttp_UnfollowMarket_FullMethodName              = "/bayes.v1.BayesHttp/UnfollowMarket"
	BayesHttp_UploadFile_FullMethodName                  = "/bayes.v1.BayesHttp/UploadFile"
	BayesHttp_DownloadFile_FullMethodName                = "/bayes.v1.BayesHttp/DownloadFile"
	BayesHttp_PublishPost_FullMethodName                 = "/bayes.v1.BayesHttp/PublishPost"
	BayesHttp_PublishComment_FullMethodName              = "/bayes.v1.BayesHttp/PublishComment"
	BayesHttp_LikeContent_FullMethodName                 = "/bayes.v1.BayesHttp/LikeContent"
	BayesHttp_UnlikeContent_FullMethodName               = "/bayes.v1.BayesHttp/UnlikeContent"
	BayesHttp_FollowUser_FullMethodName                  = "/bayes.v1.BayesHttp/FollowUser"
	BayesHttp_UnfollowUser_FullMethodName                = "/bayes.v1.BayesHttp/UnfollowUser"
	BayesHttp_GetFollowMarkets_FullMethodName            = "/bayes.v1.BayesHttp/GetFollowMarkets"
	BayesHttp_GetHoldingPositionsMarket_FullMethodName   = "/bayes.v1.BayesHttp/GetHoldingPositionsMarket"
	BayesHttp_GetHotMarkets_FullMethodName               = "/bayes.v1.BayesHttp/GetHotMarkets"
	BayesHttp_GetMarketDetail_FullMethodName             = "/bayes.v1.BayesHttp/GetMarketDetail"
	BayesHttp_GetMarketTrades_FullMethodName             = "/bayes.v1.BayesHttp/GetMarketTrades"
	BayesHttp_GetUserTrades_FullMethodName               = "/bayes.v1.BayesHttp/GetUserTrades"
	BayesHttp_GetMarketPosts_FullMethodName              = "/bayes.v1.BayesHttp/GetMarketPosts"
	BayesHttp_GetComments_FullMethodName                 = "/bayes.v1.BayesHttp/GetComments"
	BayesHttp_GetUserPositions_FullMethodName            = "/bayes.v1.BayesHttp/GetUserPositions"
	BayesHttp_GetUserBaseInfo_FullMethodName             = "/bayes.v1.BayesHttp/GetUserBaseInfo"
	BayesHttp_GetUserAssetInfo_FullMethodName            = "/bayes.v1.BayesHttp/GetUserAssetInfo"
	BayesHttp_Search_FullMethodName                      = "/bayes.v1.BayesHttp/Search"
	BayesHttp_GetUserAssetHistory_FullMethodName         = "/bayes.v1.BayesHttp/GetUserAssetHistory"
	BayesHttp_GetMarketOptionPriceHistory_FullMethodName = "/bayes.v1.BayesHttp/GetMarketOptionPriceHistory"
	BayesHttp_GetMarkets_FullMethodName                  = "/bayes.v1.BayesHttp/GetMarkets"
	BayesHttp_GetTags_FullMethodName                     = "/bayes.v1.BayesHttp/GetTags"
	BayesHttp_GetCategories_FullMethodName               = "/bayes.v1.BayesHttp/GetCategories"
	BayesHttp_GetPaymasterData_FullMethodName            = "/bayes.v1.BayesHttp/GetPaymasterData"
	BayesHttp_GetUserNotifications_FullMethodName        = "/bayes.v1.BayesHttp/GetUserNotifications"
	BayesHttp_MarkNotificationsAsRead_FullMethodName     = "/bayes.v1.BayesHttp/MarkNotificationsAsRead"
	BayesHttp_GetInviteUserList_FullMethodName           = "/bayes.v1.BayesHttp/GetInviteUserList"
	BayesHttp_GetUserTransactions_FullMethodName         = "/bayes.v1.BayesHttp/GetUserTransactions"
	BayesHttp_GetBaseTokenConfig_FullMethodName          = "/bayes.v1.BayesHttp/GetBaseTokenConfig"
	BayesHttp_GetBanners_FullMethodName                  = "/bayes.v1.BayesHttp/GetBanners"
	BayesHttp_GetSections_FullMethodName                 = "/bayes.v1.BayesHttp/GetSections"
	BayesHttp_GetTasks_FullMethodName                    = "/bayes.v1.BayesHttp/GetTasks"
	BayesHttp_ClaimTaskReward_FullMethodName             = "/bayes.v1.BayesHttp/ClaimTaskReward"
	BayesHttp_ShareTaskDone_FullMethodName               = "/bayes.v1.BayesHttp/ShareTaskDone"
	BayesHttp_Translate_FullMethodName                   = "/bayes.v1.BayesHttp/Translate"
	BayesHttp_GetLeaderboard_FullMethodName              = "/bayes.v1.BayesHttp/GetLeaderboard"
)

// BayesHttpClient is the client API for BayesHttp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BayesHttpClient interface {
	// 用户登录 每次在登录后调用 需要登录态didtoken need_auth = true
	// 没找到用户则自动创建 返回用户uid
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// 设置用户头像 need_auth = true
	SetAvatar(ctx context.Context, in *SetAvatarRequest, opts ...grpc.CallOption) (*SetAvatarReply, error)
	// 设置用户名称 need_auth = true
	SetName(ctx context.Context, in *SetNameRequest, opts ...grpc.CallOption) (*SetNameReply, error)
	// 设置用户描述 need_auth = true
	SetDescription(ctx context.Context, in *SetDescriptionRequest, opts ...grpc.CallOption) (*SetDescriptionReply, error)
	// 下单交易 need_auth = true
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderReply, error)
	// 领取市场结果 need_auth = true
	ClaimMarketResult(ctx context.Context, in *ClaimMarketResultRequest, opts ...grpc.CallOption) (*ClaimMarketResultReply, error)
	// 转账基础代币 need_auth = true
	TransferBaseToken(ctx context.Context, in *TransferBaseTokenRequest, opts ...grpc.CallOption) (*TransferBaseTokenReply, error)
	// 关注市场 need_auth = true
	FollowMarket(ctx context.Context, in *FollowMarketRequest, opts ...grpc.CallOption) (*FollowMarketReply, error)
	// 取消关注市场 need_auth = true
	UnfollowMarket(ctx context.Context, in *UnfollowMarketRequest, opts ...grpc.CallOption) (*UnfollowMarketReply, error)
	// 上传文件 need_auth = true   上传文件返回访问的key(非完整url)
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileReply, error)
	// 下载文件 need_auth = false
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*DownloadFileReply, error)
	// 发布帖子 need_auth = true
	PublishPost(ctx context.Context, in *PublishPostRequest, opts ...grpc.CallOption) (*PublishPostReply, error)
	// 发布评论 need_auth = true
	PublishComment(ctx context.Context, in *PublishCommentRequest, opts ...grpc.CallOption) (*PublishCommentReply, error)
	// 点赞 need_auth = true
	LikeContent(ctx context.Context, in *LikeContentRequest, opts ...grpc.CallOption) (*LikeContentReply, error)
	// 取消点赞 need_auth = true
	UnlikeContent(ctx context.Context, in *UnlikeContentRequest, opts ...grpc.CallOption) (*UnlikeContentReply, error)
	// 关注用户 need_auth = true
	FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserReply, error)
	// 取消关注用户 need_auth = true
	UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserReply, error)
	// 获取自己关注的市场列表 need_auth = true
	GetFollowMarkets(ctx context.Context, in *GetFollowMarketsRequest, opts ...grpc.CallOption) (*GetFollowMarketsReply, error)
	// 获取持仓的市场列表（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
	GetHoldingPositionsMarket(ctx context.Context, in *GetHoldingPositionsMarketRequest, opts ...grpc.CallOption) (*GetHoldingPositionsMarketReply, error)
	// 获取热门市场列表 need_auth = false
	GetHotMarkets(ctx context.Context, in *GetHotMarketsRequest, opts ...grpc.CallOption) (*GetHotMarketsReply, error)
	// 获取市场详情 代币信息 与当前价格 need_auth = false
	GetMarketDetail(ctx context.Context, in *GetMarketDetailRequest, opts ...grpc.CallOption) (*GetMarketDetailReply, error)
	// 获取市场交易记录 need_auth = false
	GetMarketTrades(ctx context.Context, in *GetMarketTradesRequest, opts ...grpc.CallOption) (*GetMarketTradesReply, error)
	// 查看交易记录 可以看自己 也可以看别人 need_auth = false
	GetUserTrades(ctx context.Context, in *GetUserTradesRequest, opts ...grpc.CallOption) (*GetUserTradesReply, error)
	// 获取市场帖子列表 need_auth = false
	GetMarketPosts(ctx context.Context, in *GetMarketPostsRequest, opts ...grpc.CallOption) (*GetMarketPostsReply, error)
	// 获取评论区 root_uuid为空只获取根评论 root_uuid不为空只获取该根评论下的二级评论(回复) need_auth = false
	GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsReply, error)
	// 获取用户持仓信息 可以看自己 也可以看别人 need_auth = false
	GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsReply, error)
	// 获取用户基础信息(可以看自己 也可以看别人) need_auth = false
	GetUserBaseInfo(ctx context.Context, in *GetUserBaseInfoRequest, opts ...grpc.CallOption) (*GetUserBaseInfoReply, error)
	// 获取用户自身的当前资产信息 need_auth = false
	GetUserAssetInfo(ctx context.Context, in *GetUserAssetInfoRequest, opts ...grpc.CallOption) (*GetUserAssetInfoReply, error)
	// 搜索 支持市场 用户 搜索  need_auth = false
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error)
	// 查看用户资产历史变化（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
	GetUserAssetHistory(ctx context.Context, in *GetUserAssetHistoryRequest, opts ...grpc.CallOption) (*GetUserAssetHistoryReply, error)
	// 获取市场期权价格历史 need_auth = false
	GetMarketOptionPriceHistory(ctx context.Context, in *GetMarketOptionPriceHistoryRequest, opts ...grpc.CallOption) (*GetMarketOptionPriceHistoryReply, error)
	// 首页获取市场列表 need_auth = false
	GetMarkets(ctx context.Context, in *GetMarketsRequest, opts ...grpc.CallOption) (*GetMarketsReply, error)
	// 获取标签列表 need_auth = false
	GetTags(ctx context.Context, in *GetTagsRequest, opts ...grpc.CallOption) (*GetTagsReply, error)
	// 获取市场分类列表 need_auth = false
	GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesReply, error)
	// 获取paymaster数据 need_auth = true
	GetPaymasterData(ctx context.Context, in *GetPaymasterDataRequest, opts ...grpc.CallOption) (*GetPaymasterDataReply, error)
	// 获取用户通知列表 need_auth = true
	GetUserNotifications(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*GetUserNotificationsReply, error)
	// 标记用户的通知为已读 need_auth = true
	MarkNotificationsAsRead(ctx context.Context, in *MarkNotificationsAsReadRequest, opts ...grpc.CallOption) (*MarkNotificationsAsReadReply, error)
	// 获取邀请用户列表 need_auth = true
	GetInviteUserList(ctx context.Context, in *GetInviteUserListRequest, opts ...grpc.CallOption) (*GetInviteUserListReply, error)
	// 获取用户交易记录 need_auth = true
	GetUserTransactions(ctx context.Context, in *GetUserTransactionsRequest, opts ...grpc.CallOption) (*GetUserTransactionsReply, error)
	// 获取基础代币配置 need_auth = false
	GetBaseTokenConfig(ctx context.Context, in *GetBaseTokenConfigRequest, opts ...grpc.CallOption) (*GetBaseTokenConfigReply, error)
	// 获取banner列表 need_auth = false
	GetBanners(ctx context.Context, in *GetBannersRequest, opts ...grpc.CallOption) (*GetBannersReply, error)
	// 获取section列表 need_auth = false
	GetSections(ctx context.Context, in *GetSectionsRequest, opts ...grpc.CallOption) (*GetSectionsReply, error)
	GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksReply, error)
	ClaimTaskReward(ctx context.Context, in *ClaimTaskRewardRequest, opts ...grpc.CallOption) (*ClaimTaskRewardReply, error)
	ShareTaskDone(ctx context.Context, in *ShareTaskDoneRequest, opts ...grpc.CallOption) (*ShareTaskDoneReply, error)
	Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateReply, error)
	GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error)
}

type bayesHttpClient struct {
	cc grpc.ClientConnInterface
}

func NewBayesHttpClient(cc grpc.ClientConnInterface) BayesHttpClient {
	return &bayesHttpClient{cc}
}

func (c *bayesHttpClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, BayesHttp_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) SetAvatar(ctx context.Context, in *SetAvatarRequest, opts ...grpc.CallOption) (*SetAvatarReply, error) {
	out := new(SetAvatarReply)
	err := c.cc.Invoke(ctx, BayesHttp_SetAvatar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) SetName(ctx context.Context, in *SetNameRequest, opts ...grpc.CallOption) (*SetNameReply, error) {
	out := new(SetNameReply)
	err := c.cc.Invoke(ctx, BayesHttp_SetName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) SetDescription(ctx context.Context, in *SetDescriptionRequest, opts ...grpc.CallOption) (*SetDescriptionReply, error) {
	out := new(SetDescriptionReply)
	err := c.cc.Invoke(ctx, BayesHttp_SetDescription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderReply, error) {
	out := new(PlaceOrderReply)
	err := c.cc.Invoke(ctx, BayesHttp_PlaceOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) ClaimMarketResult(ctx context.Context, in *ClaimMarketResultRequest, opts ...grpc.CallOption) (*ClaimMarketResultReply, error) {
	out := new(ClaimMarketResultReply)
	err := c.cc.Invoke(ctx, BayesHttp_ClaimMarketResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) TransferBaseToken(ctx context.Context, in *TransferBaseTokenRequest, opts ...grpc.CallOption) (*TransferBaseTokenReply, error) {
	out := new(TransferBaseTokenReply)
	err := c.cc.Invoke(ctx, BayesHttp_TransferBaseToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) FollowMarket(ctx context.Context, in *FollowMarketRequest, opts ...grpc.CallOption) (*FollowMarketReply, error) {
	out := new(FollowMarketReply)
	err := c.cc.Invoke(ctx, BayesHttp_FollowMarket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) UnfollowMarket(ctx context.Context, in *UnfollowMarketRequest, opts ...grpc.CallOption) (*UnfollowMarketReply, error) {
	out := new(UnfollowMarketReply)
	err := c.cc.Invoke(ctx, BayesHttp_UnfollowMarket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileReply, error) {
	out := new(UploadFileReply)
	err := c.cc.Invoke(ctx, BayesHttp_UploadFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*DownloadFileReply, error) {
	out := new(DownloadFileReply)
	err := c.cc.Invoke(ctx, BayesHttp_DownloadFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) PublishPost(ctx context.Context, in *PublishPostRequest, opts ...grpc.CallOption) (*PublishPostReply, error) {
	out := new(PublishPostReply)
	err := c.cc.Invoke(ctx, BayesHttp_PublishPost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) PublishComment(ctx context.Context, in *PublishCommentRequest, opts ...grpc.CallOption) (*PublishCommentReply, error) {
	out := new(PublishCommentReply)
	err := c.cc.Invoke(ctx, BayesHttp_PublishComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) LikeContent(ctx context.Context, in *LikeContentRequest, opts ...grpc.CallOption) (*LikeContentReply, error) {
	out := new(LikeContentReply)
	err := c.cc.Invoke(ctx, BayesHttp_LikeContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) UnlikeContent(ctx context.Context, in *UnlikeContentRequest, opts ...grpc.CallOption) (*UnlikeContentReply, error) {
	out := new(UnlikeContentReply)
	err := c.cc.Invoke(ctx, BayesHttp_UnlikeContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserReply, error) {
	out := new(FollowUserReply)
	err := c.cc.Invoke(ctx, BayesHttp_FollowUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserReply, error) {
	out := new(UnfollowUserReply)
	err := c.cc.Invoke(ctx, BayesHttp_UnfollowUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetFollowMarkets(ctx context.Context, in *GetFollowMarketsRequest, opts ...grpc.CallOption) (*GetFollowMarketsReply, error) {
	out := new(GetFollowMarketsReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetFollowMarkets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetHoldingPositionsMarket(ctx context.Context, in *GetHoldingPositionsMarketRequest, opts ...grpc.CallOption) (*GetHoldingPositionsMarketReply, error) {
	out := new(GetHoldingPositionsMarketReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetHoldingPositionsMarket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetHotMarkets(ctx context.Context, in *GetHotMarketsRequest, opts ...grpc.CallOption) (*GetHotMarketsReply, error) {
	out := new(GetHotMarketsReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetHotMarkets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetMarketDetail(ctx context.Context, in *GetMarketDetailRequest, opts ...grpc.CallOption) (*GetMarketDetailReply, error) {
	out := new(GetMarketDetailReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetMarketDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetMarketTrades(ctx context.Context, in *GetMarketTradesRequest, opts ...grpc.CallOption) (*GetMarketTradesReply, error) {
	out := new(GetMarketTradesReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetMarketTrades_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetUserTrades(ctx context.Context, in *GetUserTradesRequest, opts ...grpc.CallOption) (*GetUserTradesReply, error) {
	out := new(GetUserTradesReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetUserTrades_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetMarketPosts(ctx context.Context, in *GetMarketPostsRequest, opts ...grpc.CallOption) (*GetMarketPostsReply, error) {
	out := new(GetMarketPostsReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetMarketPosts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsReply, error) {
	out := new(GetCommentsReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetComments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsReply, error) {
	out := new(GetUserPositionsReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetUserPositions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetUserBaseInfo(ctx context.Context, in *GetUserBaseInfoRequest, opts ...grpc.CallOption) (*GetUserBaseInfoReply, error) {
	out := new(GetUserBaseInfoReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetUserBaseInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetUserAssetInfo(ctx context.Context, in *GetUserAssetInfoRequest, opts ...grpc.CallOption) (*GetUserAssetInfoReply, error) {
	out := new(GetUserAssetInfoReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetUserAssetInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error) {
	out := new(SearchReply)
	err := c.cc.Invoke(ctx, BayesHttp_Search_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetUserAssetHistory(ctx context.Context, in *GetUserAssetHistoryRequest, opts ...grpc.CallOption) (*GetUserAssetHistoryReply, error) {
	out := new(GetUserAssetHistoryReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetUserAssetHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetMarketOptionPriceHistory(ctx context.Context, in *GetMarketOptionPriceHistoryRequest, opts ...grpc.CallOption) (*GetMarketOptionPriceHistoryReply, error) {
	out := new(GetMarketOptionPriceHistoryReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetMarketOptionPriceHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetMarkets(ctx context.Context, in *GetMarketsRequest, opts ...grpc.CallOption) (*GetMarketsReply, error) {
	out := new(GetMarketsReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetMarkets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetTags(ctx context.Context, in *GetTagsRequest, opts ...grpc.CallOption) (*GetTagsReply, error) {
	out := new(GetTagsReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetTags_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesReply, error) {
	out := new(GetCategoriesReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetCategories_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetPaymasterData(ctx context.Context, in *GetPaymasterDataRequest, opts ...grpc.CallOption) (*GetPaymasterDataReply, error) {
	out := new(GetPaymasterDataReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetPaymasterData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetUserNotifications(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*GetUserNotificationsReply, error) {
	out := new(GetUserNotificationsReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetUserNotifications_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) MarkNotificationsAsRead(ctx context.Context, in *MarkNotificationsAsReadRequest, opts ...grpc.CallOption) (*MarkNotificationsAsReadReply, error) {
	out := new(MarkNotificationsAsReadReply)
	err := c.cc.Invoke(ctx, BayesHttp_MarkNotificationsAsRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetInviteUserList(ctx context.Context, in *GetInviteUserListRequest, opts ...grpc.CallOption) (*GetInviteUserListReply, error) {
	out := new(GetInviteUserListReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetInviteUserList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetUserTransactions(ctx context.Context, in *GetUserTransactionsRequest, opts ...grpc.CallOption) (*GetUserTransactionsReply, error) {
	out := new(GetUserTransactionsReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetUserTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetBaseTokenConfig(ctx context.Context, in *GetBaseTokenConfigRequest, opts ...grpc.CallOption) (*GetBaseTokenConfigReply, error) {
	out := new(GetBaseTokenConfigReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetBaseTokenConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetBanners(ctx context.Context, in *GetBannersRequest, opts ...grpc.CallOption) (*GetBannersReply, error) {
	out := new(GetBannersReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetBanners_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetSections(ctx context.Context, in *GetSectionsRequest, opts ...grpc.CallOption) (*GetSectionsReply, error) {
	out := new(GetSectionsReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetSections_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksReply, error) {
	out := new(GetTasksReply)
	err := c.cc.Invoke(ctx, BayesHttp_GetTasks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) ClaimTaskReward(ctx context.Context, in *ClaimTaskRewardRequest, opts ...grpc.CallOption) (*ClaimTaskRewardReply, error) {
	out := new(ClaimTaskRewardReply)
	err := c.cc.Invoke(ctx, BayesHttp_ClaimTaskReward_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) ShareTaskDone(ctx context.Context, in *ShareTaskDoneRequest, opts ...grpc.CallOption) (*ShareTaskDoneReply, error) {
	out := new(ShareTaskDoneReply)
	err := c.cc.Invoke(ctx, BayesHttp_ShareTaskDone_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateReply, error) {
	out := new(TranslateReply)
	err := c.cc.Invoke(ctx, BayesHttp_Translate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bayesHttpClient) GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error) {
	out := new(GetLeaderboardResponse)
	err := c.cc.Invoke(ctx, BayesHttp_GetLeaderboard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BayesHttpServer is the server API for BayesHttp service.
// All implementations must embed UnimplementedBayesHttpServer
// for forward compatibility
type BayesHttpServer interface {
	// 用户登录 每次在登录后调用 需要登录态didtoken need_auth = true
	// 没找到用户则自动创建 返回用户uid
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// 设置用户头像 need_auth = true
	SetAvatar(context.Context, *SetAvatarRequest) (*SetAvatarReply, error)
	// 设置用户名称 need_auth = true
	SetName(context.Context, *SetNameRequest) (*SetNameReply, error)
	// 设置用户描述 need_auth = true
	SetDescription(context.Context, *SetDescriptionRequest) (*SetDescriptionReply, error)
	// 下单交易 need_auth = true
	PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderReply, error)
	// 领取市场结果 need_auth = true
	ClaimMarketResult(context.Context, *ClaimMarketResultRequest) (*ClaimMarketResultReply, error)
	// 转账基础代币 need_auth = true
	TransferBaseToken(context.Context, *TransferBaseTokenRequest) (*TransferBaseTokenReply, error)
	// 关注市场 need_auth = true
	FollowMarket(context.Context, *FollowMarketRequest) (*FollowMarketReply, error)
	// 取消关注市场 need_auth = true
	UnfollowMarket(context.Context, *UnfollowMarketRequest) (*UnfollowMarketReply, error)
	// 上传文件 need_auth = true   上传文件返回访问的key(非完整url)
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileReply, error)
	// 下载文件 need_auth = false
	DownloadFile(context.Context, *DownloadFileRequest) (*DownloadFileReply, error)
	// 发布帖子 need_auth = true
	PublishPost(context.Context, *PublishPostRequest) (*PublishPostReply, error)
	// 发布评论 need_auth = true
	PublishComment(context.Context, *PublishCommentRequest) (*PublishCommentReply, error)
	// 点赞 need_auth = true
	LikeContent(context.Context, *LikeContentRequest) (*LikeContentReply, error)
	// 取消点赞 need_auth = true
	UnlikeContent(context.Context, *UnlikeContentRequest) (*UnlikeContentReply, error)
	// 关注用户 need_auth = true
	FollowUser(context.Context, *FollowUserRequest) (*FollowUserReply, error)
	// 取消关注用户 need_auth = true
	UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserReply, error)
	// 获取自己关注的市场列表 need_auth = true
	GetFollowMarkets(context.Context, *GetFollowMarketsRequest) (*GetFollowMarketsReply, error)
	// 获取持仓的市场列表（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
	GetHoldingPositionsMarket(context.Context, *GetHoldingPositionsMarketRequest) (*GetHoldingPositionsMarketReply, error)
	// 获取热门市场列表 need_auth = false
	GetHotMarkets(context.Context, *GetHotMarketsRequest) (*GetHotMarketsReply, error)
	// 获取市场详情 代币信息 与当前价格 need_auth = false
	GetMarketDetail(context.Context, *GetMarketDetailRequest) (*GetMarketDetailReply, error)
	// 获取市场交易记录 need_auth = false
	GetMarketTrades(context.Context, *GetMarketTradesRequest) (*GetMarketTradesReply, error)
	// 查看交易记录 可以看自己 也可以看别人 need_auth = false
	GetUserTrades(context.Context, *GetUserTradesRequest) (*GetUserTradesReply, error)
	// 获取市场帖子列表 need_auth = false
	GetMarketPosts(context.Context, *GetMarketPostsRequest) (*GetMarketPostsReply, error)
	// 获取评论区 root_uuid为空只获取根评论 root_uuid不为空只获取该根评论下的二级评论(回复) need_auth = false
	GetComments(context.Context, *GetCommentsRequest) (*GetCommentsReply, error)
	// 获取用户持仓信息 可以看自己 也可以看别人 need_auth = false
	GetUserPositions(context.Context, *GetUserPositionsRequest) (*GetUserPositionsReply, error)
	// 获取用户基础信息(可以看自己 也可以看别人) need_auth = false
	GetUserBaseInfo(context.Context, *GetUserBaseInfoRequest) (*GetUserBaseInfoReply, error)
	// 获取用户自身的当前资产信息 need_auth = false
	GetUserAssetInfo(context.Context, *GetUserAssetInfoRequest) (*GetUserAssetInfoReply, error)
	// 搜索 支持市场 用户 搜索  need_auth = false
	Search(context.Context, *SearchRequest) (*SearchReply, error)
	// 查看用户资产历史变化（ 个人资产页看自己 也能去别人主页看别人 ） need_auth = false
	GetUserAssetHistory(context.Context, *GetUserAssetHistoryRequest) (*GetUserAssetHistoryReply, error)
	// 获取市场期权价格历史 need_auth = false
	GetMarketOptionPriceHistory(context.Context, *GetMarketOptionPriceHistoryRequest) (*GetMarketOptionPriceHistoryReply, error)
	// 首页获取市场列表 need_auth = false
	GetMarkets(context.Context, *GetMarketsRequest) (*GetMarketsReply, error)
	// 获取标签列表 need_auth = false
	GetTags(context.Context, *GetTagsRequest) (*GetTagsReply, error)
	// 获取市场分类列表 need_auth = false
	GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesReply, error)
	// 获取paymaster数据 need_auth = true
	GetPaymasterData(context.Context, *GetPaymasterDataRequest) (*GetPaymasterDataReply, error)
	// 获取用户通知列表 need_auth = true
	GetUserNotifications(context.Context, *GetUserNotificationsRequest) (*GetUserNotificationsReply, error)
	// 标记用户的通知为已读 need_auth = true
	MarkNotificationsAsRead(context.Context, *MarkNotificationsAsReadRequest) (*MarkNotificationsAsReadReply, error)
	// 获取邀请用户列表 need_auth = true
	GetInviteUserList(context.Context, *GetInviteUserListRequest) (*GetInviteUserListReply, error)
	// 获取用户交易记录 need_auth = true
	GetUserTransactions(context.Context, *GetUserTransactionsRequest) (*GetUserTransactionsReply, error)
	// 获取基础代币配置 need_auth = false
	GetBaseTokenConfig(context.Context, *GetBaseTokenConfigRequest) (*GetBaseTokenConfigReply, error)
	// 获取banner列表 need_auth = false
	GetBanners(context.Context, *GetBannersRequest) (*GetBannersReply, error)
	// 获取section列表 need_auth = false
	GetSections(context.Context, *GetSectionsRequest) (*GetSectionsReply, error)
	GetTasks(context.Context, *GetTasksRequest) (*GetTasksReply, error)
	ClaimTaskReward(context.Context, *ClaimTaskRewardRequest) (*ClaimTaskRewardReply, error)
	ShareTaskDone(context.Context, *ShareTaskDoneRequest) (*ShareTaskDoneReply, error)
	Translate(context.Context, *TranslateRequest) (*TranslateReply, error)
	GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error)
	mustEmbedUnimplementedBayesHttpServer()
}

// UnimplementedBayesHttpServer must be embedded to have forward compatible implementations.
type UnimplementedBayesHttpServer struct {
}

func (UnimplementedBayesHttpServer) Login(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedBayesHttpServer) SetAvatar(context.Context, *SetAvatarRequest) (*SetAvatarReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAvatar not implemented")
}
func (UnimplementedBayesHttpServer) SetName(context.Context, *SetNameRequest) (*SetNameReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetName not implemented")
}
func (UnimplementedBayesHttpServer) SetDescription(context.Context, *SetDescriptionRequest) (*SetDescriptionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDescription not implemented")
}
func (UnimplementedBayesHttpServer) PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedBayesHttpServer) ClaimMarketResult(context.Context, *ClaimMarketResultRequest) (*ClaimMarketResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimMarketResult not implemented")
}
func (UnimplementedBayesHttpServer) TransferBaseToken(context.Context, *TransferBaseTokenRequest) (*TransferBaseTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferBaseToken not implemented")
}
func (UnimplementedBayesHttpServer) FollowMarket(context.Context, *FollowMarketRequest) (*FollowMarketReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowMarket not implemented")
}
func (UnimplementedBayesHttpServer) UnfollowMarket(context.Context, *UnfollowMarketRequest) (*UnfollowMarketReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfollowMarket not implemented")
}
func (UnimplementedBayesHttpServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedBayesHttpServer) DownloadFile(context.Context, *DownloadFileRequest) (*DownloadFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedBayesHttpServer) PublishPost(context.Context, *PublishPostRequest) (*PublishPostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishPost not implemented")
}
func (UnimplementedBayesHttpServer) PublishComment(context.Context, *PublishCommentRequest) (*PublishCommentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishComment not implemented")
}
func (UnimplementedBayesHttpServer) LikeContent(context.Context, *LikeContentRequest) (*LikeContentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeContent not implemented")
}
func (UnimplementedBayesHttpServer) UnlikeContent(context.Context, *UnlikeContentRequest) (*UnlikeContentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlikeContent not implemented")
}
func (UnimplementedBayesHttpServer) FollowUser(context.Context, *FollowUserRequest) (*FollowUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowUser not implemented")
}
func (UnimplementedBayesHttpServer) UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfollowUser not implemented")
}
func (UnimplementedBayesHttpServer) GetFollowMarkets(context.Context, *GetFollowMarketsRequest) (*GetFollowMarketsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowMarkets not implemented")
}
func (UnimplementedBayesHttpServer) GetHoldingPositionsMarket(context.Context, *GetHoldingPositionsMarketRequest) (*GetHoldingPositionsMarketReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHoldingPositionsMarket not implemented")
}
func (UnimplementedBayesHttpServer) GetHotMarkets(context.Context, *GetHotMarketsRequest) (*GetHotMarketsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHotMarkets not implemented")
}
func (UnimplementedBayesHttpServer) GetMarketDetail(context.Context, *GetMarketDetailRequest) (*GetMarketDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketDetail not implemented")
}
func (UnimplementedBayesHttpServer) GetMarketTrades(context.Context, *GetMarketTradesRequest) (*GetMarketTradesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketTrades not implemented")
}
func (UnimplementedBayesHttpServer) GetUserTrades(context.Context, *GetUserTradesRequest) (*GetUserTradesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTrades not implemented")
}
func (UnimplementedBayesHttpServer) GetMarketPosts(context.Context, *GetMarketPostsRequest) (*GetMarketPostsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketPosts not implemented")
}
func (UnimplementedBayesHttpServer) GetComments(context.Context, *GetCommentsRequest) (*GetCommentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComments not implemented")
}
func (UnimplementedBayesHttpServer) GetUserPositions(context.Context, *GetUserPositionsRequest) (*GetUserPositionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPositions not implemented")
}
func (UnimplementedBayesHttpServer) GetUserBaseInfo(context.Context, *GetUserBaseInfoRequest) (*GetUserBaseInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBaseInfo not implemented")
}
func (UnimplementedBayesHttpServer) GetUserAssetInfo(context.Context, *GetUserAssetInfoRequest) (*GetUserAssetInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAssetInfo not implemented")
}
func (UnimplementedBayesHttpServer) Search(context.Context, *SearchRequest) (*SearchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedBayesHttpServer) GetUserAssetHistory(context.Context, *GetUserAssetHistoryRequest) (*GetUserAssetHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAssetHistory not implemented")
}
func (UnimplementedBayesHttpServer) GetMarketOptionPriceHistory(context.Context, *GetMarketOptionPriceHistoryRequest) (*GetMarketOptionPriceHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketOptionPriceHistory not implemented")
}
func (UnimplementedBayesHttpServer) GetMarkets(context.Context, *GetMarketsRequest) (*GetMarketsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarkets not implemented")
}
func (UnimplementedBayesHttpServer) GetTags(context.Context, *GetTagsRequest) (*GetTagsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTags not implemented")
}
func (UnimplementedBayesHttpServer) GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategories not implemented")
}
func (UnimplementedBayesHttpServer) GetPaymasterData(context.Context, *GetPaymasterDataRequest) (*GetPaymasterDataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymasterData not implemented")
}
func (UnimplementedBayesHttpServer) GetUserNotifications(context.Context, *GetUserNotificationsRequest) (*GetUserNotificationsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserNotifications not implemented")
}
func (UnimplementedBayesHttpServer) MarkNotificationsAsRead(context.Context, *MarkNotificationsAsReadRequest) (*MarkNotificationsAsReadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkNotificationsAsRead not implemented")
}
func (UnimplementedBayesHttpServer) GetInviteUserList(context.Context, *GetInviteUserListRequest) (*GetInviteUserListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInviteUserList not implemented")
}
func (UnimplementedBayesHttpServer) GetUserTransactions(context.Context, *GetUserTransactionsRequest) (*GetUserTransactionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTransactions not implemented")
}
func (UnimplementedBayesHttpServer) GetBaseTokenConfig(context.Context, *GetBaseTokenConfigRequest) (*GetBaseTokenConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBaseTokenConfig not implemented")
}
func (UnimplementedBayesHttpServer) GetBanners(context.Context, *GetBannersRequest) (*GetBannersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBanners not implemented")
}
func (UnimplementedBayesHttpServer) GetSections(context.Context, *GetSectionsRequest) (*GetSectionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSections not implemented")
}
func (UnimplementedBayesHttpServer) GetTasks(context.Context, *GetTasksRequest) (*GetTasksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasks not implemented")
}
func (UnimplementedBayesHttpServer) ClaimTaskReward(context.Context, *ClaimTaskRewardRequest) (*ClaimTaskRewardReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimTaskReward not implemented")
}
func (UnimplementedBayesHttpServer) ShareTaskDone(context.Context, *ShareTaskDoneRequest) (*ShareTaskDoneReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareTaskDone not implemented")
}
func (UnimplementedBayesHttpServer) Translate(context.Context, *TranslateRequest) (*TranslateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Translate not implemented")
}
func (UnimplementedBayesHttpServer) GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderboard not implemented")
}
func (UnimplementedBayesHttpServer) mustEmbedUnimplementedBayesHttpServer() {}

// UnsafeBayesHttpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BayesHttpServer will
// result in compilation errors.
type UnsafeBayesHttpServer interface {
	mustEmbedUnimplementedBayesHttpServer()
}

func RegisterBayesHttpServer(s grpc.ServiceRegistrar, srv BayesHttpServer) {
	s.RegisterService(&BayesHttp_ServiceDesc, srv)
}

func _BayesHttp_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_SetAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).SetAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_SetAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).SetAvatar(ctx, req.(*SetAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_SetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).SetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_SetName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).SetName(ctx, req.(*SetNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_SetDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).SetDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_SetDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).SetDescription(ctx, req.(*SetDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_PlaceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_ClaimMarketResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimMarketResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).ClaimMarketResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_ClaimMarketResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).ClaimMarketResult(ctx, req.(*ClaimMarketResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_TransferBaseToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferBaseTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).TransferBaseToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_TransferBaseToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).TransferBaseToken(ctx, req.(*TransferBaseTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_FollowMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).FollowMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_FollowMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).FollowMarket(ctx, req.(*FollowMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_UnfollowMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).UnfollowMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_UnfollowMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).UnfollowMarket(ctx, req.(*UnfollowMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_DownloadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).DownloadFile(ctx, req.(*DownloadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_PublishPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).PublishPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_PublishPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).PublishPost(ctx, req.(*PublishPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_PublishComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).PublishComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_PublishComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).PublishComment(ctx, req.(*PublishCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_LikeContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).LikeContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_LikeContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).LikeContent(ctx, req.(*LikeContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_UnlikeContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).UnlikeContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_UnlikeContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).UnlikeContent(ctx, req.(*UnlikeContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_FollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).FollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_UnfollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).UnfollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_UnfollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).UnfollowUser(ctx, req.(*UnfollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetFollowMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetFollowMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetFollowMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetFollowMarkets(ctx, req.(*GetFollowMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetHoldingPositionsMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHoldingPositionsMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetHoldingPositionsMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetHoldingPositionsMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetHoldingPositionsMarket(ctx, req.(*GetHoldingPositionsMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetHotMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetHotMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetHotMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetHotMarkets(ctx, req.(*GetHotMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetMarketDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetMarketDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetMarketDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetMarketDetail(ctx, req.(*GetMarketDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetMarketTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetMarketTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetMarketTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetMarketTrades(ctx, req.(*GetMarketTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetUserTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetUserTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetUserTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetUserTrades(ctx, req.(*GetUserTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetMarketPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetMarketPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetMarketPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetMarketPosts(ctx, req.(*GetMarketPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetComments(ctx, req.(*GetCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetUserPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetUserPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetUserPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetUserPositions(ctx, req.(*GetUserPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetUserBaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBaseInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetUserBaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetUserBaseInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetUserBaseInfo(ctx, req.(*GetUserBaseInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetUserAssetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAssetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetUserAssetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetUserAssetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetUserAssetInfo(ctx, req.(*GetUserAssetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetUserAssetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAssetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetUserAssetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetUserAssetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetUserAssetHistory(ctx, req.(*GetUserAssetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetMarketOptionPriceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketOptionPriceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetMarketOptionPriceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetMarketOptionPriceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetMarketOptionPriceHistory(ctx, req.(*GetMarketOptionPriceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetMarkets(ctx, req.(*GetMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetTags(ctx, req.(*GetTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetCategories(ctx, req.(*GetCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetPaymasterData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymasterDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetPaymasterData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetPaymasterData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetPaymasterData(ctx, req.(*GetPaymasterDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetUserNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetUserNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetUserNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetUserNotifications(ctx, req.(*GetUserNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_MarkNotificationsAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationsAsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).MarkNotificationsAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_MarkNotificationsAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).MarkNotificationsAsRead(ctx, req.(*MarkNotificationsAsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetInviteUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInviteUserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetInviteUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetInviteUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetInviteUserList(ctx, req.(*GetInviteUserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetUserTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetUserTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetUserTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetUserTransactions(ctx, req.(*GetUserTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetBaseTokenConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBaseTokenConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetBaseTokenConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetBaseTokenConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetBaseTokenConfig(ctx, req.(*GetBaseTokenConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetBanners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBannersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetBanners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetBanners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetBanners(ctx, req.(*GetBannersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetSections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetSections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetSections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetSections(ctx, req.(*GetSectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetTasks(ctx, req.(*GetTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_ClaimTaskReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimTaskRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).ClaimTaskReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_ClaimTaskReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).ClaimTaskReward(ctx, req.(*ClaimTaskRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_ShareTaskDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareTaskDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).ShareTaskDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_ShareTaskDone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).ShareTaskDone(ctx, req.(*ShareTaskDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_Translate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).Translate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_Translate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).Translate(ctx, req.(*TranslateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BayesHttp_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BayesHttpServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BayesHttp_GetLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BayesHttpServer).GetLeaderboard(ctx, req.(*GetLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BayesHttp_ServiceDesc is the grpc.ServiceDesc for BayesHttp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BayesHttp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bayes.v1.BayesHttp",
	HandlerType: (*BayesHttpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _BayesHttp_Login_Handler,
		},
		{
			MethodName: "SetAvatar",
			Handler:    _BayesHttp_SetAvatar_Handler,
		},
		{
			MethodName: "SetName",
			Handler:    _BayesHttp_SetName_Handler,
		},
		{
			MethodName: "SetDescription",
			Handler:    _BayesHttp_SetDescription_Handler,
		},
		{
			MethodName: "PlaceOrder",
			Handler:    _BayesHttp_PlaceOrder_Handler,
		},
		{
			MethodName: "ClaimMarketResult",
			Handler:    _BayesHttp_ClaimMarketResult_Handler,
		},
		{
			MethodName: "TransferBaseToken",
			Handler:    _BayesHttp_TransferBaseToken_Handler,
		},
		{
			MethodName: "FollowMarket",
			Handler:    _BayesHttp_FollowMarket_Handler,
		},
		{
			MethodName: "UnfollowMarket",
			Handler:    _BayesHttp_UnfollowMarket_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _BayesHttp_UploadFile_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _BayesHttp_DownloadFile_Handler,
		},
		{
			MethodName: "PublishPost",
			Handler:    _BayesHttp_PublishPost_Handler,
		},
		{
			MethodName: "PublishComment",
			Handler:    _BayesHttp_PublishComment_Handler,
		},
		{
			MethodName: "LikeContent",
			Handler:    _BayesHttp_LikeContent_Handler,
		},
		{
			MethodName: "UnlikeContent",
			Handler:    _BayesHttp_UnlikeContent_Handler,
		},
		{
			MethodName: "FollowUser",
			Handler:    _BayesHttp_FollowUser_Handler,
		},
		{
			MethodName: "UnfollowUser",
			Handler:    _BayesHttp_UnfollowUser_Handler,
		},
		{
			MethodName: "GetFollowMarkets",
			Handler:    _BayesHttp_GetFollowMarkets_Handler,
		},
		{
			MethodName: "GetHoldingPositionsMarket",
			Handler:    _BayesHttp_GetHoldingPositionsMarket_Handler,
		},
		{
			MethodName: "GetHotMarkets",
			Handler:    _BayesHttp_GetHotMarkets_Handler,
		},
		{
			MethodName: "GetMarketDetail",
			Handler:    _BayesHttp_GetMarketDetail_Handler,
		},
		{
			MethodName: "GetMarketTrades",
			Handler:    _BayesHttp_GetMarketTrades_Handler,
		},
		{
			MethodName: "GetUserTrades",
			Handler:    _BayesHttp_GetUserTrades_Handler,
		},
		{
			MethodName: "GetMarketPosts",
			Handler:    _BayesHttp_GetMarketPosts_Handler,
		},
		{
			MethodName: "GetComments",
			Handler:    _BayesHttp_GetComments_Handler,
		},
		{
			MethodName: "GetUserPositions",
			Handler:    _BayesHttp_GetUserPositions_Handler,
		},
		{
			MethodName: "GetUserBaseInfo",
			Handler:    _BayesHttp_GetUserBaseInfo_Handler,
		},
		{
			MethodName: "GetUserAssetInfo",
			Handler:    _BayesHttp_GetUserAssetInfo_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _BayesHttp_Search_Handler,
		},
		{
			MethodName: "GetUserAssetHistory",
			Handler:    _BayesHttp_GetUserAssetHistory_Handler,
		},
		{
			MethodName: "GetMarketOptionPriceHistory",
			Handler:    _BayesHttp_GetMarketOptionPriceHistory_Handler,
		},
		{
			MethodName: "GetMarkets",
			Handler:    _BayesHttp_GetMarkets_Handler,
		},
		{
			MethodName: "GetTags",
			Handler:    _BayesHttp_GetTags_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _BayesHttp_GetCategories_Handler,
		},
		{
			MethodName: "GetPaymasterData",
			Handler:    _BayesHttp_GetPaymasterData_Handler,
		},
		{
			MethodName: "GetUserNotifications",
			Handler:    _BayesHttp_GetUserNotifications_Handler,
		},
		{
			MethodName: "MarkNotificationsAsRead",
			Handler:    _BayesHttp_MarkNotificationsAsRead_Handler,
		},
		{
			MethodName: "GetInviteUserList",
			Handler:    _BayesHttp_GetInviteUserList_Handler,
		},
		{
			MethodName: "GetUserTransactions",
			Handler:    _BayesHttp_GetUserTransactions_Handler,
		},
		{
			MethodName: "GetBaseTokenConfig",
			Handler:    _BayesHttp_GetBaseTokenConfig_Handler,
		},
		{
			MethodName: "GetBanners",
			Handler:    _BayesHttp_GetBanners_Handler,
		},
		{
			MethodName: "GetSections",
			Handler:    _BayesHttp_GetSections_Handler,
		},
		{
			MethodName: "GetTasks",
			Handler:    _BayesHttp_GetTasks_Handler,
		},
		{
			MethodName: "ClaimTaskReward",
			Handler:    _BayesHttp_ClaimTaskReward_Handler,
		},
		{
			MethodName: "ShareTaskDone",
			Handler:    _BayesHttp_ShareTaskDone_Handler,
		},
		{
			MethodName: "Translate",
			Handler:    _BayesHttp_Translate_Handler,
		},
		{
			MethodName: "GetLeaderboard",
			Handler:    _BayesHttp_GetLeaderboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market-backend/v1/bayes.proto",
}
