// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Data                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Custom        *Custom                `protobuf:"bytes,2,opt,name=custom,proto3" json:"custom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetCustom() *Custom {
	if x != nil {
		return x.Custom
	}
	return nil
}

type Data struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Db              *Data_Db               `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Redis           *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	MarketcenterRpc *Data_Rpc              `protobuf:"bytes,3,opt,name=marketcenter_rpc,json=marketcenterRpc,proto3" json:"marketcenter_rpc,omitempty"`
	UsercenterRpc   *Data_Rpc              `protobuf:"bytes,4,opt,name=usercenter_rpc,json=usercenterRpc,proto3" json:"usercenter_rpc,omitempty"`
	Blockchain      *Data_Blockchain       `protobuf:"bytes,5,opt,name=blockchain,proto3" json:"blockchain,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetDb() *Data_Db {
	if x != nil {
		return x.Db
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetMarketcenterRpc() *Data_Rpc {
	if x != nil {
		return x.MarketcenterRpc
	}
	return nil
}

func (x *Data) GetUsercenterRpc() *Data_Rpc {
	if x != nil {
		return x.UsercenterRpc
	}
	return nil
}

func (x *Data) GetBlockchain() *Data_Blockchain {
	if x != nil {
		return x.Blockchain
	}
	return nil
}

type Custom struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AssetTokens    *Custom_AssetTokens    `protobuf:"bytes,1,opt,name=asset_tokens,json=assetTokens,proto3" json:"asset_tokens,omitempty"`
	LarkWebhookKey string                 `protobuf:"bytes,2,opt,name=lark_webhook_key,json=larkWebhookKey,proto3" json:"lark_webhook_key,omitempty"`
	LarkEnabled    bool                   `protobuf:"varint,3,opt,name=lark_enabled,json=larkEnabled,proto3" json:"lark_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Custom) Reset() {
	*x = Custom{}
	mi := &file_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Custom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom) ProtoMessage() {}

func (x *Custom) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom.ProtoReflect.Descriptor instead.
func (*Custom) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Custom) GetAssetTokens() *Custom_AssetTokens {
	if x != nil {
		return x.AssetTokens
	}
	return nil
}

func (x *Custom) GetLarkWebhookKey() string {
	if x != nil {
		return x.LarkWebhookKey
	}
	return ""
}

func (x *Custom) GetLarkEnabled() bool {
	if x != nil {
		return x.LarkEnabled
	}
	return false
}

type Data_Db struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Dsn             string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	MaxIdleConns    int32                  `protobuf:"varint,2,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	MaxOpenConns    int32                  `protobuf:"varint,3,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	ConnMaxLifetime *durationpb.Duration   `protobuf:"bytes,4,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_Db) Reset() {
	*x = Data_Db{}
	mi := &file_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Db) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Db) ProtoMessage() {}

func (x *Data_Db) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Db.ProtoReflect.Descriptor instead.
func (*Data_Db) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Data_Db) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Data_Db) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Data_Db) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_Db) GetConnMaxLifetime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return nil
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,4,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,5,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

type Data_Rpc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Rpc) Reset() {
	*x = Data_Rpc{}
	mi := &file_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Rpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Rpc) ProtoMessage() {}

func (x *Data_Rpc) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Rpc.ProtoReflect.Descriptor instead.
func (*Data_Rpc) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Data_Rpc) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Rpc) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Blockchain struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	StartBlock               uint64                 `protobuf:"varint,1,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	FactoryContractAddress   string                 `protobuf:"bytes,2,opt,name=factory_contract_address,json=factoryContractAddress,proto3" json:"factory_contract_address,omitempty"`       // 工厂合约地址
	PointsTokenAddress       string                 `protobuf:"bytes,3,opt,name=points_token_address,json=pointsTokenAddress,proto3" json:"points_token_address,omitempty"`                   // 积分代币地址
	BatchScanSize            uint64                 `protobuf:"varint,4,opt,name=batch_scan_size,json=batchScanSize,proto3" json:"batch_scan_size,omitempty"`                                 // 批量扫描的区块数量
	ConfirmedBlockNum        uint32                 `protobuf:"varint,5,opt,name=confirmed_block_num,json=confirmedBlockNum,proto3" json:"confirmed_block_num,omitempty"`                     // 检查分叉的区块深度，通常设置为6-12确认
	CronScanDbRows           uint32                 `protobuf:"varint,6,opt,name=cron_scan_db_rows,json=cronScanDbRows,proto3" json:"cron_scan_db_rows,omitempty"`                            // 定时扫描的db行数
	ArbRpcUrls               []string               `protobuf:"bytes,7,rep,name=arb_rpc_urls,json=arbRpcUrls,proto3" json:"arb_rpc_urls,omitempty"`                                           // Arbitrum RPC URL列表
	ConditionalTokensAddress string                 `protobuf:"bytes,8,opt,name=conditional_tokens_address,json=conditionalTokensAddress,proto3" json:"conditional_tokens_address,omitempty"` // ConditionalTokens合约地址
	PredictionCtfAddresses   []string               `protobuf:"bytes,9,rep,name=prediction_ctf_addresses,json=predictionCtfAddresses,proto3" json:"prediction_ctf_addresses,omitempty"`       // PredictionCTF池合约地址列表
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Data_Blockchain) Reset() {
	*x = Data_Blockchain{}
	mi := &file_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Blockchain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Blockchain) ProtoMessage() {}

func (x *Data_Blockchain) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Blockchain.ProtoReflect.Descriptor instead.
func (*Data_Blockchain) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Data_Blockchain) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *Data_Blockchain) GetFactoryContractAddress() string {
	if x != nil {
		return x.FactoryContractAddress
	}
	return ""
}

func (x *Data_Blockchain) GetPointsTokenAddress() string {
	if x != nil {
		return x.PointsTokenAddress
	}
	return ""
}

func (x *Data_Blockchain) GetBatchScanSize() uint64 {
	if x != nil {
		return x.BatchScanSize
	}
	return 0
}

func (x *Data_Blockchain) GetConfirmedBlockNum() uint32 {
	if x != nil {
		return x.ConfirmedBlockNum
	}
	return 0
}

func (x *Data_Blockchain) GetCronScanDbRows() uint32 {
	if x != nil {
		return x.CronScanDbRows
	}
	return 0
}

func (x *Data_Blockchain) GetArbRpcUrls() []string {
	if x != nil {
		return x.ArbRpcUrls
	}
	return nil
}

func (x *Data_Blockchain) GetConditionalTokensAddress() string {
	if x != nil {
		return x.ConditionalTokensAddress
	}
	return ""
}

func (x *Data_Blockchain) GetPredictionCtfAddresses() []string {
	if x != nil {
		return x.PredictionCtfAddresses
	}
	return nil
}

type Custom_AssetTokens struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Points        *Custom_AssetTokensToken `protobuf:"bytes,1,opt,name=points,proto3" json:"points,omitempty"`
	Usdc          *Custom_AssetTokensToken `protobuf:"bytes,2,opt,name=usdc,proto3" json:"usdc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Custom_AssetTokens) Reset() {
	*x = Custom_AssetTokens{}
	mi := &file_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Custom_AssetTokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom_AssetTokens) ProtoMessage() {}

func (x *Custom_AssetTokens) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom_AssetTokens.ProtoReflect.Descriptor instead.
func (*Custom_AssetTokens) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Custom_AssetTokens) GetPoints() *Custom_AssetTokensToken {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *Custom_AssetTokens) GetUsdc() *Custom_AssetTokensToken {
	if x != nil {
		return x.Usdc
	}
	return nil
}

type Custom_AssetTokensToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals      uint32                 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Custom_AssetTokensToken) Reset() {
	*x = Custom_AssetTokensToken{}
	mi := &file_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Custom_AssetTokensToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom_AssetTokensToken) ProtoMessage() {}

func (x *Custom_AssetTokensToken) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom_AssetTokensToken.ProtoReflect.Descriptor instead.
func (*Custom_AssetTokensToken) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Custom_AssetTokensToken) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Custom_AssetTokensToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Custom_AssetTokensToken) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Custom_AssetTokensToken) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

var File_conf_proto protoreflect.FileDescriptor

const file_conf_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"conf.proto\x12\x04conf\x1a\x1egoogle/protobuf/duration.proto\"Q\n" +
	"\tBootstrap\x12\x1e\n" +
	"\x04data\x18\x01 \x01(\v2\n" +
	".conf.DataR\x04data\x12$\n" +
	"\x06custom\x18\x02 \x01(\v2\f.conf.CustomR\x06custom\"\xf3\b\n" +
	"\x04Data\x12\x1d\n" +
	"\x02db\x18\x01 \x01(\v2\r.conf.Data.DbR\x02db\x12&\n" +
	"\x05redis\x18\x02 \x01(\v2\x10.conf.Data.RedisR\x05redis\x129\n" +
	"\x10marketcenter_rpc\x18\x03 \x01(\v2\x0e.conf.Data.RpcR\x0fmarketcenterRpc\x125\n" +
	"\x0eusercenter_rpc\x18\x04 \x01(\v2\x0e.conf.Data.RpcR\rusercenterRpc\x125\n" +
	"\n" +
	"blockchain\x18\x05 \x01(\v2\x15.conf.Data.BlockchainR\n" +
	"blockchain\x1a\xa9\x01\n" +
	"\x02Db\x12\x10\n" +
	"\x03dsn\x18\x01 \x01(\tR\x03dsn\x12$\n" +
	"\x0emax_idle_conns\x18\x02 \x01(\x05R\fmaxIdleConns\x12$\n" +
	"\x0emax_open_conns\x18\x03 \x01(\x05R\fmaxOpenConns\x12E\n" +
	"\x11conn_max_lifetime\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x0fconnMaxLifetime\x1a\xc5\x01\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\x12<\n" +
	"\fread_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x1aN\n" +
	"\x03Rpc\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1a\xb6\x03\n" +
	"\n" +
	"Blockchain\x12\x1f\n" +
	"\vstart_block\x18\x01 \x01(\x04R\n" +
	"startBlock\x128\n" +
	"\x18factory_contract_address\x18\x02 \x01(\tR\x16factoryContractAddress\x120\n" +
	"\x14points_token_address\x18\x03 \x01(\tR\x12pointsTokenAddress\x12&\n" +
	"\x0fbatch_scan_size\x18\x04 \x01(\x04R\rbatchScanSize\x12.\n" +
	"\x13confirmed_block_num\x18\x05 \x01(\rR\x11confirmedBlockNum\x12)\n" +
	"\x11cron_scan_db_rows\x18\x06 \x01(\rR\x0ecronScanDbRows\x12 \n" +
	"\farb_rpc_urls\x18\a \x03(\tR\n" +
	"arbRpcUrls\x12<\n" +
	"\x1aconditional_tokens_address\x18\b \x01(\tR\x18conditionalTokensAddress\x128\n" +
	"\x18prediction_ctf_addresses\x18\t \x03(\tR\x16predictionCtfAddresses\"\xf9\x02\n" +
	"\x06Custom\x12;\n" +
	"\fasset_tokens\x18\x01 \x01(\v2\x18.conf.Custom.AssetTokensR\vassetTokens\x12(\n" +
	"\x10lark_webhook_key\x18\x02 \x01(\tR\x0elarkWebhookKey\x12!\n" +
	"\flark_enabled\x18\x03 \x01(\bR\vlarkEnabled\x1a\xe4\x01\n" +
	"\vAssetTokens\x126\n" +
	"\x06points\x18\x01 \x01(\v2\x1e.conf.Custom.AssetTokens.tokenR\x06points\x122\n" +
	"\x04usdc\x18\x02 \x01(\v2\x1e.conf.Custom.AssetTokens.tokenR\x04usdc\x1ai\n" +
	"\x05token\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x04 \x01(\rR\bdecimalsB#Z!block-listener/internal/conf;confb\x06proto3"

var (
	file_conf_proto_rawDescOnce sync.Once
	file_conf_proto_rawDescData []byte
)

func file_conf_proto_rawDescGZIP() []byte {
	file_conf_proto_rawDescOnce.Do(func() {
		file_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)))
	})
	return file_conf_proto_rawDescData
}

var file_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),               // 0: conf.Bootstrap
	(*Data)(nil),                    // 1: conf.Data
	(*Custom)(nil),                  // 2: conf.Custom
	(*Data_Db)(nil),                 // 3: conf.Data.Db
	(*Data_Redis)(nil),              // 4: conf.Data.Redis
	(*Data_Rpc)(nil),                // 5: conf.Data.Rpc
	(*Data_Blockchain)(nil),         // 6: conf.Data.Blockchain
	(*Custom_AssetTokens)(nil),      // 7: conf.Custom.AssetTokens
	(*Custom_AssetTokensToken)(nil), // 8: conf.Custom.AssetTokens.token
	(*durationpb.Duration)(nil),     // 9: google.protobuf.Duration
}
var file_conf_proto_depIdxs = []int32{
	1,  // 0: conf.Bootstrap.data:type_name -> conf.Data
	2,  // 1: conf.Bootstrap.custom:type_name -> conf.Custom
	3,  // 2: conf.Data.db:type_name -> conf.Data.Db
	4,  // 3: conf.Data.redis:type_name -> conf.Data.Redis
	5,  // 4: conf.Data.marketcenter_rpc:type_name -> conf.Data.Rpc
	5,  // 5: conf.Data.usercenter_rpc:type_name -> conf.Data.Rpc
	6,  // 6: conf.Data.blockchain:type_name -> conf.Data.Blockchain
	7,  // 7: conf.Custom.asset_tokens:type_name -> conf.Custom.AssetTokens
	9,  // 8: conf.Data.Db.conn_max_lifetime:type_name -> google.protobuf.Duration
	9,  // 9: conf.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	9,  // 10: conf.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	9,  // 11: conf.Data.Rpc.timeout:type_name -> google.protobuf.Duration
	8,  // 12: conf.Custom.AssetTokens.points:type_name -> conf.Custom.AssetTokens.token
	8,  // 13: conf.Custom.AssetTokens.usdc:type_name -> conf.Custom.AssetTokens.token
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_conf_proto_init() }
func file_conf_proto_init() {
	if File_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_proto_goTypes,
		DependencyIndexes: file_conf_proto_depIdxs,
		MessageInfos:      file_conf_proto_msgTypes,
	}.Build()
	File_conf_proto = out.File
	file_conf_proto_goTypes = nil
	file_conf_proto_depIdxs = nil
}
