// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: market-service/marketcenter/v1/marketcenter.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Marketcenter_GetPayMasterData_FullMethodName                     = "/marketcenter.v1.Marketcenter/GetPayMasterData"
	Marketcenter_UpdateUserMarketFollowStatus_FullMethodName         = "/marketcenter.v1.Marketcenter/UpdateUserMarketFollowStatus"
	Marketcenter_PlaceOrder_FullMethodName                           = "/marketcenter.v1.Marketcenter/PlaceOrder"
	Marketcenter_ClaimMarketResult_FullMethodName                    = "/marketcenter.v1.Marketcenter/ClaimMarketResult"
	Marketcenter_TransferBaseToken_FullMethodName                    = "/marketcenter.v1.Marketcenter/TransferBaseToken"
	Marketcenter_GetOptionTokensPrice_FullMethodName                 = "/marketcenter.v1.Marketcenter/GetOptionTokensPrice"
	Marketcenter_GetMarketUsersPositions_FullMethodName              = "/marketcenter.v1.Marketcenter/GetMarketUsersPositions"
	Marketcenter_GetHotMarkets_FullMethodName                        = "/marketcenter.v1.Marketcenter/GetHotMarkets"
	Marketcenter_GetFollowedMarkets_FullMethodName                   = "/marketcenter.v1.Marketcenter/GetFollowedMarkets"
	Marketcenter_GetHoldingPositionsMarkets_FullMethodName           = "/marketcenter.v1.Marketcenter/GetHoldingPositionsMarkets"
	Marketcenter_GetMarketDetail_FullMethodName                      = "/marketcenter.v1.Marketcenter/GetMarketDetail"
	Marketcenter_GetMarketTrades_FullMethodName                      = "/marketcenter.v1.Marketcenter/GetMarketTrades"
	Marketcenter_GetUserPositions_FullMethodName                     = "/marketcenter.v1.Marketcenter/GetUserPositions"
	Marketcenter_GetUserTrades_FullMethodName                        = "/marketcenter.v1.Marketcenter/GetUserTrades"
	Marketcenter_GetUserLatestAssetValue_FullMethodName              = "/marketcenter.v1.Marketcenter/GetUserLatestAssetValue"
	Marketcenter_SearchMarket_FullMethodName                         = "/marketcenter.v1.Marketcenter/SearchMarket"
	Marketcenter_GetUserAssetHistory_FullMethodName                  = "/marketcenter.v1.Marketcenter/GetUserAssetHistory"
	Marketcenter_GetMarketOptionPriceHistory_FullMethodName          = "/marketcenter.v1.Marketcenter/GetMarketOptionPriceHistory"
	Marketcenter_GetMarketTags_FullMethodName                        = "/marketcenter.v1.Marketcenter/GetMarketTags"
	Marketcenter_GetMarketCategories_FullMethodName                  = "/marketcenter.v1.Marketcenter/GetMarketCategories"
	Marketcenter_GetMarketsAndOptionsInfo_FullMethodName             = "/marketcenter.v1.Marketcenter/GetMarketsAndOptionsInfo"
	Marketcenter_BatchGetMarketUsersPositions_FullMethodName         = "/marketcenter.v1.Marketcenter/BatchGetMarketUsersPositions"
	Marketcenter_GetMarketsAndOptionsForBlockListener_FullMethodName = "/marketcenter.v1.Marketcenter/GetMarketsAndOptionsForBlockListener"
	Marketcenter_CreateMarketsAndOptions_FullMethodName              = "/marketcenter.v1.Marketcenter/CreateMarketsAndOptions"
	Marketcenter_ProcessMarketDepositOrWithdrawEvent_FullMethodName  = "/marketcenter.v1.Marketcenter/ProcessMarketDepositOrWithdrawEvent"
	Marketcenter_ProcessMarketSwapEvent_FullMethodName               = "/marketcenter.v1.Marketcenter/ProcessMarketSwapEvent"
	Marketcenter_ProcessMarketClaimResultEvent_FullMethodName        = "/marketcenter.v1.Marketcenter/ProcessMarketClaimResultEvent"
	Marketcenter_ProcessMarketSettingEvent_FullMethodName            = "/marketcenter.v1.Marketcenter/ProcessMarketSettingEvent"
	Marketcenter_ProcessMarketAssertDisputedEvent_FullMethodName     = "/marketcenter.v1.Marketcenter/ProcessMarketAssertDisputedEvent"
	Marketcenter_ProcessMarketAssertionResolvedEvent_FullMethodName  = "/marketcenter.v1.Marketcenter/ProcessMarketAssertionResolvedEvent"
	Marketcenter_UpdateUserBaseTokenBalance_FullMethodName           = "/marketcenter.v1.Marketcenter/UpdateUserBaseTokenBalance"
	Marketcenter_BatchUpdateOptionPrice_FullMethodName               = "/marketcenter.v1.Marketcenter/BatchUpdateOptionPrice"
	Marketcenter_UpdateMarketStatus_FullMethodName                   = "/marketcenter.v1.Marketcenter/UpdateMarketStatus"
	Marketcenter_UpdateMarketInfo_FullMethodName                     = "/marketcenter.v1.Marketcenter/UpdateMarketInfo"
	Marketcenter_GetUserTransactions_FullMethodName                  = "/marketcenter.v1.Marketcenter/GetUserTransactions"
	Marketcenter_GetBanners_FullMethodName                           = "/marketcenter.v1.Marketcenter/GetBanners"
	Marketcenter_GetSections_FullMethodName                          = "/marketcenter.v1.Marketcenter/GetSections"
	Marketcenter_GetLeaderboard_FullMethodName                       = "/marketcenter.v1.Marketcenter/GetLeaderboard"
	Marketcenter_GetQuestionDetail_FullMethodName                    = "/marketcenter.v1.Marketcenter/GetQuestionDetail"
)

// MarketcenterClient is the client API for Marketcenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketcenterClient interface {
	GetPayMasterData(ctx context.Context, in *GetPayMasterDataRequest, opts ...grpc.CallOption) (*GetPayMasterDataResponse, error)
	UpdateUserMarketFollowStatus(ctx context.Context, in *UpdateUserMarketFollowStatusRequest, opts ...grpc.CallOption) (*UpdateUserMarketFollowStatusResponse, error)
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
	ClaimMarketResult(ctx context.Context, in *ClaimMarketResultRequest, opts ...grpc.CallOption) (*ClaimMarketResultResponse, error)
	TransferBaseToken(ctx context.Context, in *TransferBaseTokenRequest, opts ...grpc.CallOption) (*TransferBaseTokenResponse, error)
	GetOptionTokensPrice(ctx context.Context, in *GetOptionTokensPriceRequest, opts ...grpc.CallOption) (*GetOptionTokensPriceResponse, error)
	// 获取某市场下用户的持仓情况
	GetMarketUsersPositions(ctx context.Context, in *GetMarketUsersPositionsRequest, opts ...grpc.CallOption) (*GetMarketUsersPositionsResponse, error)
	GetHotMarkets(ctx context.Context, in *GetHotMarketsRequest, opts ...grpc.CallOption) (*GetHotMarketsResponse, error)
	GetFollowedMarkets(ctx context.Context, in *GetFollowedMarketsRequest, opts ...grpc.CallOption) (*GetFollowedMarketsResponse, error)
	// 获取用户有持仓的市场信息
	GetHoldingPositionsMarkets(ctx context.Context, in *GetHoldingPositionsMarketsRequest, opts ...grpc.CallOption) (*GetHoldingPositionsMarketsResponse, error)
	GetMarketDetail(ctx context.Context, in *GetMarketDetailRequest, opts ...grpc.CallOption) (*GetMarketDetailResponse, error)
	GetMarketTrades(ctx context.Context, in *GetMarketTradesRequest, opts ...grpc.CallOption) (*GetMarketTradesResponse, error)
	GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsResponse, error)
	GetUserTrades(ctx context.Context, in *GetUserTradesRequest, opts ...grpc.CallOption) (*GetUserTradesResponse, error)
	GetUserLatestAssetValue(ctx context.Context, in *GetUserLatestAssetValueRequest, opts ...grpc.CallOption) (*GetUserLatestAssetValueResponse, error)
	SearchMarket(ctx context.Context, in *SearchMarketRequest, opts ...grpc.CallOption) (*SearchMarketResponse, error)
	GetUserAssetHistory(ctx context.Context, in *GetUserAssetHistoryRequest, opts ...grpc.CallOption) (*GetUserAssetHistoryResponse, error)
	GetMarketOptionPriceHistory(ctx context.Context, in *GetMarketOptionPriceHistoryRequest, opts ...grpc.CallOption) (*GetMarketOptionPriceHistoryResponse, error)
	GetMarketTags(ctx context.Context, in *GetMarketTagsRequest, opts ...grpc.CallOption) (*GetMarketTagsResponse, error)
	GetMarketCategories(ctx context.Context, in *GetMarketCategoriesRequest, opts ...grpc.CallOption) (*GetMarketCategoriesResponse, error)
	// 分页获取市场信息
	GetMarketsAndOptionsInfo(ctx context.Context, in *GetMarketsAndOptionsInfoRequest, opts ...grpc.CallOption) (*GetMarketsAndOptionsInfoResponse, error)
	// 批量查询市场用户的持仓
	BatchGetMarketUsersPositions(ctx context.Context, in *BatchGetMarketUsersPositionsRequest, opts ...grpc.CallOption) (*BatchGetMarketUsersPositionsResponse, error)
	// 爬块监听链上事件后调用
	GetMarketsAndOptionsForBlockListener(ctx context.Context, in *GetMarketsAndOptionsForBlockListenerRequest, opts ...grpc.CallOption) (*GetMarketsAndOptionsForBlockListenerResponse, error)
	CreateMarketsAndOptions(ctx context.Context, in *CreateMarketsAndOptionsRequest, opts ...grpc.CallOption) (*CreateMarketsAndOptionsResponse, error)
	ProcessMarketDepositOrWithdrawEvent(ctx context.Context, in *ProcessMarketDepositOrWithdrawEventRequest, opts ...grpc.CallOption) (*ProcessMarketDepositOrWithdrawEventResponse, error)
	ProcessMarketSwapEvent(ctx context.Context, in *ProcessMarketSwapEventRequest, opts ...grpc.CallOption) (*ProcessMarketSwapEventResponse, error)
	ProcessMarketClaimResultEvent(ctx context.Context, in *ProcessMarketClaimResultEventRequest, opts ...grpc.CallOption) (*ProcessMarketClaimResultEventResponse, error)
	ProcessMarketSettingEvent(ctx context.Context, in *ProcessMarketSettingEventRequest, opts ...grpc.CallOption) (*ProcessMarketSettingEventResponse, error)
	ProcessMarketAssertDisputedEvent(ctx context.Context, in *ProcessMarketAssertDisputedEventRequest, opts ...grpc.CallOption) (*ProcessMarketAssertDisputedEventResponse, error)
	ProcessMarketAssertionResolvedEvent(ctx context.Context, in *ProcessMarketAssertionResolvedEventRequest, opts ...grpc.CallOption) (*ProcessMarketAssertionResolvedEventResponse, error)
	UpdateUserBaseTokenBalance(ctx context.Context, in *UpdateUserBaseTokenBalanceRequest, opts ...grpc.CallOption) (*UpdateUserBaseTokenBalanceResponse, error)
	BatchUpdateOptionPrice(ctx context.Context, in *BatchUpdateOptionPriceRequest, opts ...grpc.CallOption) (*BatchUpdateOptionPriceResponse, error)
	UpdateMarketStatus(ctx context.Context, in *UpdateMarketStatusRequest, opts ...grpc.CallOption) (*UpdateMarketStatusResponse, error)
	UpdateMarketInfo(ctx context.Context, in *UpdateMarketInfoRequest, opts ...grpc.CallOption) (*UpdateMarketInfoResponse, error)
	GetUserTransactions(ctx context.Context, in *GetUserTransactionsRequest, opts ...grpc.CallOption) (*GetUserTransactionsResponse, error)
	GetBanners(ctx context.Context, in *GetBannersRequest, opts ...grpc.CallOption) (*GetBannersResponse, error)
	GetSections(ctx context.Context, in *GetSectionsRequest, opts ...grpc.CallOption) (*GetSectionsResponse, error)
	GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error)
	GetQuestionDetail(ctx context.Context, in *GetQuestionDetailRequest, opts ...grpc.CallOption) (*GetQuestionDetailResponse, error)
}

type marketcenterClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketcenterClient(cc grpc.ClientConnInterface) MarketcenterClient {
	return &marketcenterClient{cc}
}

func (c *marketcenterClient) GetPayMasterData(ctx context.Context, in *GetPayMasterDataRequest, opts ...grpc.CallOption) (*GetPayMasterDataResponse, error) {
	out := new(GetPayMasterDataResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetPayMasterData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) UpdateUserMarketFollowStatus(ctx context.Context, in *UpdateUserMarketFollowStatusRequest, opts ...grpc.CallOption) (*UpdateUserMarketFollowStatusResponse, error) {
	out := new(UpdateUserMarketFollowStatusResponse)
	err := c.cc.Invoke(ctx, Marketcenter_UpdateUserMarketFollowStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	out := new(PlaceOrderResponse)
	err := c.cc.Invoke(ctx, Marketcenter_PlaceOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) ClaimMarketResult(ctx context.Context, in *ClaimMarketResultRequest, opts ...grpc.CallOption) (*ClaimMarketResultResponse, error) {
	out := new(ClaimMarketResultResponse)
	err := c.cc.Invoke(ctx, Marketcenter_ClaimMarketResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) TransferBaseToken(ctx context.Context, in *TransferBaseTokenRequest, opts ...grpc.CallOption) (*TransferBaseTokenResponse, error) {
	out := new(TransferBaseTokenResponse)
	err := c.cc.Invoke(ctx, Marketcenter_TransferBaseToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetOptionTokensPrice(ctx context.Context, in *GetOptionTokensPriceRequest, opts ...grpc.CallOption) (*GetOptionTokensPriceResponse, error) {
	out := new(GetOptionTokensPriceResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetOptionTokensPrice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetMarketUsersPositions(ctx context.Context, in *GetMarketUsersPositionsRequest, opts ...grpc.CallOption) (*GetMarketUsersPositionsResponse, error) {
	out := new(GetMarketUsersPositionsResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetMarketUsersPositions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetHotMarkets(ctx context.Context, in *GetHotMarketsRequest, opts ...grpc.CallOption) (*GetHotMarketsResponse, error) {
	out := new(GetHotMarketsResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetHotMarkets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetFollowedMarkets(ctx context.Context, in *GetFollowedMarketsRequest, opts ...grpc.CallOption) (*GetFollowedMarketsResponse, error) {
	out := new(GetFollowedMarketsResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetFollowedMarkets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetHoldingPositionsMarkets(ctx context.Context, in *GetHoldingPositionsMarketsRequest, opts ...grpc.CallOption) (*GetHoldingPositionsMarketsResponse, error) {
	out := new(GetHoldingPositionsMarketsResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetHoldingPositionsMarkets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetMarketDetail(ctx context.Context, in *GetMarketDetailRequest, opts ...grpc.CallOption) (*GetMarketDetailResponse, error) {
	out := new(GetMarketDetailResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetMarketDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetMarketTrades(ctx context.Context, in *GetMarketTradesRequest, opts ...grpc.CallOption) (*GetMarketTradesResponse, error) {
	out := new(GetMarketTradesResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetMarketTrades_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsResponse, error) {
	out := new(GetUserPositionsResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetUserPositions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetUserTrades(ctx context.Context, in *GetUserTradesRequest, opts ...grpc.CallOption) (*GetUserTradesResponse, error) {
	out := new(GetUserTradesResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetUserTrades_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetUserLatestAssetValue(ctx context.Context, in *GetUserLatestAssetValueRequest, opts ...grpc.CallOption) (*GetUserLatestAssetValueResponse, error) {
	out := new(GetUserLatestAssetValueResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetUserLatestAssetValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) SearchMarket(ctx context.Context, in *SearchMarketRequest, opts ...grpc.CallOption) (*SearchMarketResponse, error) {
	out := new(SearchMarketResponse)
	err := c.cc.Invoke(ctx, Marketcenter_SearchMarket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetUserAssetHistory(ctx context.Context, in *GetUserAssetHistoryRequest, opts ...grpc.CallOption) (*GetUserAssetHistoryResponse, error) {
	out := new(GetUserAssetHistoryResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetUserAssetHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetMarketOptionPriceHistory(ctx context.Context, in *GetMarketOptionPriceHistoryRequest, opts ...grpc.CallOption) (*GetMarketOptionPriceHistoryResponse, error) {
	out := new(GetMarketOptionPriceHistoryResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetMarketOptionPriceHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetMarketTags(ctx context.Context, in *GetMarketTagsRequest, opts ...grpc.CallOption) (*GetMarketTagsResponse, error) {
	out := new(GetMarketTagsResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetMarketTags_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetMarketCategories(ctx context.Context, in *GetMarketCategoriesRequest, opts ...grpc.CallOption) (*GetMarketCategoriesResponse, error) {
	out := new(GetMarketCategoriesResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetMarketCategories_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetMarketsAndOptionsInfo(ctx context.Context, in *GetMarketsAndOptionsInfoRequest, opts ...grpc.CallOption) (*GetMarketsAndOptionsInfoResponse, error) {
	out := new(GetMarketsAndOptionsInfoResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetMarketsAndOptionsInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) BatchGetMarketUsersPositions(ctx context.Context, in *BatchGetMarketUsersPositionsRequest, opts ...grpc.CallOption) (*BatchGetMarketUsersPositionsResponse, error) {
	out := new(BatchGetMarketUsersPositionsResponse)
	err := c.cc.Invoke(ctx, Marketcenter_BatchGetMarketUsersPositions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetMarketsAndOptionsForBlockListener(ctx context.Context, in *GetMarketsAndOptionsForBlockListenerRequest, opts ...grpc.CallOption) (*GetMarketsAndOptionsForBlockListenerResponse, error) {
	out := new(GetMarketsAndOptionsForBlockListenerResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetMarketsAndOptionsForBlockListener_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) CreateMarketsAndOptions(ctx context.Context, in *CreateMarketsAndOptionsRequest, opts ...grpc.CallOption) (*CreateMarketsAndOptionsResponse, error) {
	out := new(CreateMarketsAndOptionsResponse)
	err := c.cc.Invoke(ctx, Marketcenter_CreateMarketsAndOptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) ProcessMarketDepositOrWithdrawEvent(ctx context.Context, in *ProcessMarketDepositOrWithdrawEventRequest, opts ...grpc.CallOption) (*ProcessMarketDepositOrWithdrawEventResponse, error) {
	out := new(ProcessMarketDepositOrWithdrawEventResponse)
	err := c.cc.Invoke(ctx, Marketcenter_ProcessMarketDepositOrWithdrawEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) ProcessMarketSwapEvent(ctx context.Context, in *ProcessMarketSwapEventRequest, opts ...grpc.CallOption) (*ProcessMarketSwapEventResponse, error) {
	out := new(ProcessMarketSwapEventResponse)
	err := c.cc.Invoke(ctx, Marketcenter_ProcessMarketSwapEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) ProcessMarketClaimResultEvent(ctx context.Context, in *ProcessMarketClaimResultEventRequest, opts ...grpc.CallOption) (*ProcessMarketClaimResultEventResponse, error) {
	out := new(ProcessMarketClaimResultEventResponse)
	err := c.cc.Invoke(ctx, Marketcenter_ProcessMarketClaimResultEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) ProcessMarketSettingEvent(ctx context.Context, in *ProcessMarketSettingEventRequest, opts ...grpc.CallOption) (*ProcessMarketSettingEventResponse, error) {
	out := new(ProcessMarketSettingEventResponse)
	err := c.cc.Invoke(ctx, Marketcenter_ProcessMarketSettingEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) ProcessMarketAssertDisputedEvent(ctx context.Context, in *ProcessMarketAssertDisputedEventRequest, opts ...grpc.CallOption) (*ProcessMarketAssertDisputedEventResponse, error) {
	out := new(ProcessMarketAssertDisputedEventResponse)
	err := c.cc.Invoke(ctx, Marketcenter_ProcessMarketAssertDisputedEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) ProcessMarketAssertionResolvedEvent(ctx context.Context, in *ProcessMarketAssertionResolvedEventRequest, opts ...grpc.CallOption) (*ProcessMarketAssertionResolvedEventResponse, error) {
	out := new(ProcessMarketAssertionResolvedEventResponse)
	err := c.cc.Invoke(ctx, Marketcenter_ProcessMarketAssertionResolvedEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) UpdateUserBaseTokenBalance(ctx context.Context, in *UpdateUserBaseTokenBalanceRequest, opts ...grpc.CallOption) (*UpdateUserBaseTokenBalanceResponse, error) {
	out := new(UpdateUserBaseTokenBalanceResponse)
	err := c.cc.Invoke(ctx, Marketcenter_UpdateUserBaseTokenBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) BatchUpdateOptionPrice(ctx context.Context, in *BatchUpdateOptionPriceRequest, opts ...grpc.CallOption) (*BatchUpdateOptionPriceResponse, error) {
	out := new(BatchUpdateOptionPriceResponse)
	err := c.cc.Invoke(ctx, Marketcenter_BatchUpdateOptionPrice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) UpdateMarketStatus(ctx context.Context, in *UpdateMarketStatusRequest, opts ...grpc.CallOption) (*UpdateMarketStatusResponse, error) {
	out := new(UpdateMarketStatusResponse)
	err := c.cc.Invoke(ctx, Marketcenter_UpdateMarketStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) UpdateMarketInfo(ctx context.Context, in *UpdateMarketInfoRequest, opts ...grpc.CallOption) (*UpdateMarketInfoResponse, error) {
	out := new(UpdateMarketInfoResponse)
	err := c.cc.Invoke(ctx, Marketcenter_UpdateMarketInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetUserTransactions(ctx context.Context, in *GetUserTransactionsRequest, opts ...grpc.CallOption) (*GetUserTransactionsResponse, error) {
	out := new(GetUserTransactionsResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetUserTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetBanners(ctx context.Context, in *GetBannersRequest, opts ...grpc.CallOption) (*GetBannersResponse, error) {
	out := new(GetBannersResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetBanners_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetSections(ctx context.Context, in *GetSectionsRequest, opts ...grpc.CallOption) (*GetSectionsResponse, error) {
	out := new(GetSectionsResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetSections_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error) {
	out := new(GetLeaderboardResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetLeaderboard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketcenterClient) GetQuestionDetail(ctx context.Context, in *GetQuestionDetailRequest, opts ...grpc.CallOption) (*GetQuestionDetailResponse, error) {
	out := new(GetQuestionDetailResponse)
	err := c.cc.Invoke(ctx, Marketcenter_GetQuestionDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketcenterServer is the server API for Marketcenter service.
// All implementations must embed UnimplementedMarketcenterServer
// for forward compatibility
type MarketcenterServer interface {
	GetPayMasterData(context.Context, *GetPayMasterDataRequest) (*GetPayMasterDataResponse, error)
	UpdateUserMarketFollowStatus(context.Context, *UpdateUserMarketFollowStatusRequest) (*UpdateUserMarketFollowStatusResponse, error)
	PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error)
	ClaimMarketResult(context.Context, *ClaimMarketResultRequest) (*ClaimMarketResultResponse, error)
	TransferBaseToken(context.Context, *TransferBaseTokenRequest) (*TransferBaseTokenResponse, error)
	GetOptionTokensPrice(context.Context, *GetOptionTokensPriceRequest) (*GetOptionTokensPriceResponse, error)
	// 获取某市场下用户的持仓情况
	GetMarketUsersPositions(context.Context, *GetMarketUsersPositionsRequest) (*GetMarketUsersPositionsResponse, error)
	GetHotMarkets(context.Context, *GetHotMarketsRequest) (*GetHotMarketsResponse, error)
	GetFollowedMarkets(context.Context, *GetFollowedMarketsRequest) (*GetFollowedMarketsResponse, error)
	// 获取用户有持仓的市场信息
	GetHoldingPositionsMarkets(context.Context, *GetHoldingPositionsMarketsRequest) (*GetHoldingPositionsMarketsResponse, error)
	GetMarketDetail(context.Context, *GetMarketDetailRequest) (*GetMarketDetailResponse, error)
	GetMarketTrades(context.Context, *GetMarketTradesRequest) (*GetMarketTradesResponse, error)
	GetUserPositions(context.Context, *GetUserPositionsRequest) (*GetUserPositionsResponse, error)
	GetUserTrades(context.Context, *GetUserTradesRequest) (*GetUserTradesResponse, error)
	GetUserLatestAssetValue(context.Context, *GetUserLatestAssetValueRequest) (*GetUserLatestAssetValueResponse, error)
	SearchMarket(context.Context, *SearchMarketRequest) (*SearchMarketResponse, error)
	GetUserAssetHistory(context.Context, *GetUserAssetHistoryRequest) (*GetUserAssetHistoryResponse, error)
	GetMarketOptionPriceHistory(context.Context, *GetMarketOptionPriceHistoryRequest) (*GetMarketOptionPriceHistoryResponse, error)
	GetMarketTags(context.Context, *GetMarketTagsRequest) (*GetMarketTagsResponse, error)
	GetMarketCategories(context.Context, *GetMarketCategoriesRequest) (*GetMarketCategoriesResponse, error)
	// 分页获取市场信息
	GetMarketsAndOptionsInfo(context.Context, *GetMarketsAndOptionsInfoRequest) (*GetMarketsAndOptionsInfoResponse, error)
	// 批量查询市场用户的持仓
	BatchGetMarketUsersPositions(context.Context, *BatchGetMarketUsersPositionsRequest) (*BatchGetMarketUsersPositionsResponse, error)
	// 爬块监听链上事件后调用
	GetMarketsAndOptionsForBlockListener(context.Context, *GetMarketsAndOptionsForBlockListenerRequest) (*GetMarketsAndOptionsForBlockListenerResponse, error)
	CreateMarketsAndOptions(context.Context, *CreateMarketsAndOptionsRequest) (*CreateMarketsAndOptionsResponse, error)
	ProcessMarketDepositOrWithdrawEvent(context.Context, *ProcessMarketDepositOrWithdrawEventRequest) (*ProcessMarketDepositOrWithdrawEventResponse, error)
	ProcessMarketSwapEvent(context.Context, *ProcessMarketSwapEventRequest) (*ProcessMarketSwapEventResponse, error)
	ProcessMarketClaimResultEvent(context.Context, *ProcessMarketClaimResultEventRequest) (*ProcessMarketClaimResultEventResponse, error)
	ProcessMarketSettingEvent(context.Context, *ProcessMarketSettingEventRequest) (*ProcessMarketSettingEventResponse, error)
	ProcessMarketAssertDisputedEvent(context.Context, *ProcessMarketAssertDisputedEventRequest) (*ProcessMarketAssertDisputedEventResponse, error)
	ProcessMarketAssertionResolvedEvent(context.Context, *ProcessMarketAssertionResolvedEventRequest) (*ProcessMarketAssertionResolvedEventResponse, error)
	UpdateUserBaseTokenBalance(context.Context, *UpdateUserBaseTokenBalanceRequest) (*UpdateUserBaseTokenBalanceResponse, error)
	BatchUpdateOptionPrice(context.Context, *BatchUpdateOptionPriceRequest) (*BatchUpdateOptionPriceResponse, error)
	UpdateMarketStatus(context.Context, *UpdateMarketStatusRequest) (*UpdateMarketStatusResponse, error)
	UpdateMarketInfo(context.Context, *UpdateMarketInfoRequest) (*UpdateMarketInfoResponse, error)
	GetUserTransactions(context.Context, *GetUserTransactionsRequest) (*GetUserTransactionsResponse, error)
	GetBanners(context.Context, *GetBannersRequest) (*GetBannersResponse, error)
	GetSections(context.Context, *GetSectionsRequest) (*GetSectionsResponse, error)
	GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error)
	GetQuestionDetail(context.Context, *GetQuestionDetailRequest) (*GetQuestionDetailResponse, error)
	mustEmbedUnimplementedMarketcenterServer()
}

// UnimplementedMarketcenterServer must be embedded to have forward compatible implementations.
type UnimplementedMarketcenterServer struct {
}

func (UnimplementedMarketcenterServer) GetPayMasterData(context.Context, *GetPayMasterDataRequest) (*GetPayMasterDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayMasterData not implemented")
}
func (UnimplementedMarketcenterServer) UpdateUserMarketFollowStatus(context.Context, *UpdateUserMarketFollowStatusRequest) (*UpdateUserMarketFollowStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserMarketFollowStatus not implemented")
}
func (UnimplementedMarketcenterServer) PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedMarketcenterServer) ClaimMarketResult(context.Context, *ClaimMarketResultRequest) (*ClaimMarketResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimMarketResult not implemented")
}
func (UnimplementedMarketcenterServer) TransferBaseToken(context.Context, *TransferBaseTokenRequest) (*TransferBaseTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferBaseToken not implemented")
}
func (UnimplementedMarketcenterServer) GetOptionTokensPrice(context.Context, *GetOptionTokensPriceRequest) (*GetOptionTokensPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOptionTokensPrice not implemented")
}
func (UnimplementedMarketcenterServer) GetMarketUsersPositions(context.Context, *GetMarketUsersPositionsRequest) (*GetMarketUsersPositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketUsersPositions not implemented")
}
func (UnimplementedMarketcenterServer) GetHotMarkets(context.Context, *GetHotMarketsRequest) (*GetHotMarketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHotMarkets not implemented")
}
func (UnimplementedMarketcenterServer) GetFollowedMarkets(context.Context, *GetFollowedMarketsRequest) (*GetFollowedMarketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowedMarkets not implemented")
}
func (UnimplementedMarketcenterServer) GetHoldingPositionsMarkets(context.Context, *GetHoldingPositionsMarketsRequest) (*GetHoldingPositionsMarketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHoldingPositionsMarkets not implemented")
}
func (UnimplementedMarketcenterServer) GetMarketDetail(context.Context, *GetMarketDetailRequest) (*GetMarketDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketDetail not implemented")
}
func (UnimplementedMarketcenterServer) GetMarketTrades(context.Context, *GetMarketTradesRequest) (*GetMarketTradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketTrades not implemented")
}
func (UnimplementedMarketcenterServer) GetUserPositions(context.Context, *GetUserPositionsRequest) (*GetUserPositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPositions not implemented")
}
func (UnimplementedMarketcenterServer) GetUserTrades(context.Context, *GetUserTradesRequest) (*GetUserTradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTrades not implemented")
}
func (UnimplementedMarketcenterServer) GetUserLatestAssetValue(context.Context, *GetUserLatestAssetValueRequest) (*GetUserLatestAssetValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLatestAssetValue not implemented")
}
func (UnimplementedMarketcenterServer) SearchMarket(context.Context, *SearchMarketRequest) (*SearchMarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMarket not implemented")
}
func (UnimplementedMarketcenterServer) GetUserAssetHistory(context.Context, *GetUserAssetHistoryRequest) (*GetUserAssetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAssetHistory not implemented")
}
func (UnimplementedMarketcenterServer) GetMarketOptionPriceHistory(context.Context, *GetMarketOptionPriceHistoryRequest) (*GetMarketOptionPriceHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketOptionPriceHistory not implemented")
}
func (UnimplementedMarketcenterServer) GetMarketTags(context.Context, *GetMarketTagsRequest) (*GetMarketTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketTags not implemented")
}
func (UnimplementedMarketcenterServer) GetMarketCategories(context.Context, *GetMarketCategoriesRequest) (*GetMarketCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketCategories not implemented")
}
func (UnimplementedMarketcenterServer) GetMarketsAndOptionsInfo(context.Context, *GetMarketsAndOptionsInfoRequest) (*GetMarketsAndOptionsInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketsAndOptionsInfo not implemented")
}
func (UnimplementedMarketcenterServer) BatchGetMarketUsersPositions(context.Context, *BatchGetMarketUsersPositionsRequest) (*BatchGetMarketUsersPositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetMarketUsersPositions not implemented")
}
func (UnimplementedMarketcenterServer) GetMarketsAndOptionsForBlockListener(context.Context, *GetMarketsAndOptionsForBlockListenerRequest) (*GetMarketsAndOptionsForBlockListenerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketsAndOptionsForBlockListener not implemented")
}
func (UnimplementedMarketcenterServer) CreateMarketsAndOptions(context.Context, *CreateMarketsAndOptionsRequest) (*CreateMarketsAndOptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMarketsAndOptions not implemented")
}
func (UnimplementedMarketcenterServer) ProcessMarketDepositOrWithdrawEvent(context.Context, *ProcessMarketDepositOrWithdrawEventRequest) (*ProcessMarketDepositOrWithdrawEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMarketDepositOrWithdrawEvent not implemented")
}
func (UnimplementedMarketcenterServer) ProcessMarketSwapEvent(context.Context, *ProcessMarketSwapEventRequest) (*ProcessMarketSwapEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMarketSwapEvent not implemented")
}
func (UnimplementedMarketcenterServer) ProcessMarketClaimResultEvent(context.Context, *ProcessMarketClaimResultEventRequest) (*ProcessMarketClaimResultEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMarketClaimResultEvent not implemented")
}
func (UnimplementedMarketcenterServer) ProcessMarketSettingEvent(context.Context, *ProcessMarketSettingEventRequest) (*ProcessMarketSettingEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMarketSettingEvent not implemented")
}
func (UnimplementedMarketcenterServer) ProcessMarketAssertDisputedEvent(context.Context, *ProcessMarketAssertDisputedEventRequest) (*ProcessMarketAssertDisputedEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMarketAssertDisputedEvent not implemented")
}
func (UnimplementedMarketcenterServer) ProcessMarketAssertionResolvedEvent(context.Context, *ProcessMarketAssertionResolvedEventRequest) (*ProcessMarketAssertionResolvedEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMarketAssertionResolvedEvent not implemented")
}
func (UnimplementedMarketcenterServer) UpdateUserBaseTokenBalance(context.Context, *UpdateUserBaseTokenBalanceRequest) (*UpdateUserBaseTokenBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserBaseTokenBalance not implemented")
}
func (UnimplementedMarketcenterServer) BatchUpdateOptionPrice(context.Context, *BatchUpdateOptionPriceRequest) (*BatchUpdateOptionPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpdateOptionPrice not implemented")
}
func (UnimplementedMarketcenterServer) UpdateMarketStatus(context.Context, *UpdateMarketStatusRequest) (*UpdateMarketStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMarketStatus not implemented")
}
func (UnimplementedMarketcenterServer) UpdateMarketInfo(context.Context, *UpdateMarketInfoRequest) (*UpdateMarketInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMarketInfo not implemented")
}
func (UnimplementedMarketcenterServer) GetUserTransactions(context.Context, *GetUserTransactionsRequest) (*GetUserTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTransactions not implemented")
}
func (UnimplementedMarketcenterServer) GetBanners(context.Context, *GetBannersRequest) (*GetBannersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBanners not implemented")
}
func (UnimplementedMarketcenterServer) GetSections(context.Context, *GetSectionsRequest) (*GetSectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSections not implemented")
}
func (UnimplementedMarketcenterServer) GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderboard not implemented")
}
func (UnimplementedMarketcenterServer) GetQuestionDetail(context.Context, *GetQuestionDetailRequest) (*GetQuestionDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionDetail not implemented")
}
func (UnimplementedMarketcenterServer) mustEmbedUnimplementedMarketcenterServer() {}

// UnsafeMarketcenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketcenterServer will
// result in compilation errors.
type UnsafeMarketcenterServer interface {
	mustEmbedUnimplementedMarketcenterServer()
}

func RegisterMarketcenterServer(s grpc.ServiceRegistrar, srv MarketcenterServer) {
	s.RegisterService(&Marketcenter_ServiceDesc, srv)
}

func _Marketcenter_GetPayMasterData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayMasterDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetPayMasterData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetPayMasterData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetPayMasterData(ctx, req.(*GetPayMasterDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_UpdateUserMarketFollowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserMarketFollowStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).UpdateUserMarketFollowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_UpdateUserMarketFollowStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).UpdateUserMarketFollowStatus(ctx, req.(*UpdateUserMarketFollowStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_PlaceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_ClaimMarketResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimMarketResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).ClaimMarketResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_ClaimMarketResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).ClaimMarketResult(ctx, req.(*ClaimMarketResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_TransferBaseToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferBaseTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).TransferBaseToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_TransferBaseToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).TransferBaseToken(ctx, req.(*TransferBaseTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetOptionTokensPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOptionTokensPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetOptionTokensPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetOptionTokensPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetOptionTokensPrice(ctx, req.(*GetOptionTokensPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetMarketUsersPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketUsersPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetMarketUsersPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetMarketUsersPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetMarketUsersPositions(ctx, req.(*GetMarketUsersPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetHotMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetHotMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetHotMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetHotMarkets(ctx, req.(*GetHotMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetFollowedMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowedMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetFollowedMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetFollowedMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetFollowedMarkets(ctx, req.(*GetFollowedMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetHoldingPositionsMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHoldingPositionsMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetHoldingPositionsMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetHoldingPositionsMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetHoldingPositionsMarkets(ctx, req.(*GetHoldingPositionsMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetMarketDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetMarketDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetMarketDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetMarketDetail(ctx, req.(*GetMarketDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetMarketTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetMarketTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetMarketTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetMarketTrades(ctx, req.(*GetMarketTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetUserPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetUserPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetUserPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetUserPositions(ctx, req.(*GetUserPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetUserTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetUserTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetUserTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetUserTrades(ctx, req.(*GetUserTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetUserLatestAssetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLatestAssetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetUserLatestAssetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetUserLatestAssetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetUserLatestAssetValue(ctx, req.(*GetUserLatestAssetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_SearchMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).SearchMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_SearchMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).SearchMarket(ctx, req.(*SearchMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetUserAssetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAssetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetUserAssetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetUserAssetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetUserAssetHistory(ctx, req.(*GetUserAssetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetMarketOptionPriceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketOptionPriceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetMarketOptionPriceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetMarketOptionPriceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetMarketOptionPriceHistory(ctx, req.(*GetMarketOptionPriceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetMarketTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetMarketTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetMarketTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetMarketTags(ctx, req.(*GetMarketTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetMarketCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetMarketCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetMarketCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetMarketCategories(ctx, req.(*GetMarketCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetMarketsAndOptionsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketsAndOptionsInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetMarketsAndOptionsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetMarketsAndOptionsInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetMarketsAndOptionsInfo(ctx, req.(*GetMarketsAndOptionsInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_BatchGetMarketUsersPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetMarketUsersPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).BatchGetMarketUsersPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_BatchGetMarketUsersPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).BatchGetMarketUsersPositions(ctx, req.(*BatchGetMarketUsersPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetMarketsAndOptionsForBlockListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketsAndOptionsForBlockListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetMarketsAndOptionsForBlockListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetMarketsAndOptionsForBlockListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetMarketsAndOptionsForBlockListener(ctx, req.(*GetMarketsAndOptionsForBlockListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_CreateMarketsAndOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMarketsAndOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).CreateMarketsAndOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_CreateMarketsAndOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).CreateMarketsAndOptions(ctx, req.(*CreateMarketsAndOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_ProcessMarketDepositOrWithdrawEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessMarketDepositOrWithdrawEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).ProcessMarketDepositOrWithdrawEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_ProcessMarketDepositOrWithdrawEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).ProcessMarketDepositOrWithdrawEvent(ctx, req.(*ProcessMarketDepositOrWithdrawEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_ProcessMarketSwapEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessMarketSwapEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).ProcessMarketSwapEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_ProcessMarketSwapEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).ProcessMarketSwapEvent(ctx, req.(*ProcessMarketSwapEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_ProcessMarketClaimResultEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessMarketClaimResultEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).ProcessMarketClaimResultEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_ProcessMarketClaimResultEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).ProcessMarketClaimResultEvent(ctx, req.(*ProcessMarketClaimResultEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_ProcessMarketSettingEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessMarketSettingEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).ProcessMarketSettingEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_ProcessMarketSettingEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).ProcessMarketSettingEvent(ctx, req.(*ProcessMarketSettingEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_ProcessMarketAssertDisputedEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessMarketAssertDisputedEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).ProcessMarketAssertDisputedEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_ProcessMarketAssertDisputedEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).ProcessMarketAssertDisputedEvent(ctx, req.(*ProcessMarketAssertDisputedEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_ProcessMarketAssertionResolvedEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessMarketAssertionResolvedEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).ProcessMarketAssertionResolvedEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_ProcessMarketAssertionResolvedEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).ProcessMarketAssertionResolvedEvent(ctx, req.(*ProcessMarketAssertionResolvedEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_UpdateUserBaseTokenBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserBaseTokenBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).UpdateUserBaseTokenBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_UpdateUserBaseTokenBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).UpdateUserBaseTokenBalance(ctx, req.(*UpdateUserBaseTokenBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_BatchUpdateOptionPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateOptionPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).BatchUpdateOptionPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_BatchUpdateOptionPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).BatchUpdateOptionPrice(ctx, req.(*BatchUpdateOptionPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_UpdateMarketStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMarketStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).UpdateMarketStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_UpdateMarketStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).UpdateMarketStatus(ctx, req.(*UpdateMarketStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_UpdateMarketInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMarketInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).UpdateMarketInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_UpdateMarketInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).UpdateMarketInfo(ctx, req.(*UpdateMarketInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetUserTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetUserTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetUserTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetUserTransactions(ctx, req.(*GetUserTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetBanners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBannersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetBanners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetBanners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetBanners(ctx, req.(*GetBannersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetSections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetSections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetSections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetSections(ctx, req.(*GetSectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetLeaderboard(ctx, req.(*GetLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketcenter_GetQuestionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestionDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketcenterServer).GetQuestionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketcenter_GetQuestionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketcenterServer).GetQuestionDetail(ctx, req.(*GetQuestionDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Marketcenter_ServiceDesc is the grpc.ServiceDesc for Marketcenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Marketcenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketcenter.v1.Marketcenter",
	HandlerType: (*MarketcenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPayMasterData",
			Handler:    _Marketcenter_GetPayMasterData_Handler,
		},
		{
			MethodName: "UpdateUserMarketFollowStatus",
			Handler:    _Marketcenter_UpdateUserMarketFollowStatus_Handler,
		},
		{
			MethodName: "PlaceOrder",
			Handler:    _Marketcenter_PlaceOrder_Handler,
		},
		{
			MethodName: "ClaimMarketResult",
			Handler:    _Marketcenter_ClaimMarketResult_Handler,
		},
		{
			MethodName: "TransferBaseToken",
			Handler:    _Marketcenter_TransferBaseToken_Handler,
		},
		{
			MethodName: "GetOptionTokensPrice",
			Handler:    _Marketcenter_GetOptionTokensPrice_Handler,
		},
		{
			MethodName: "GetMarketUsersPositions",
			Handler:    _Marketcenter_GetMarketUsersPositions_Handler,
		},
		{
			MethodName: "GetHotMarkets",
			Handler:    _Marketcenter_GetHotMarkets_Handler,
		},
		{
			MethodName: "GetFollowedMarkets",
			Handler:    _Marketcenter_GetFollowedMarkets_Handler,
		},
		{
			MethodName: "GetHoldingPositionsMarkets",
			Handler:    _Marketcenter_GetHoldingPositionsMarkets_Handler,
		},
		{
			MethodName: "GetMarketDetail",
			Handler:    _Marketcenter_GetMarketDetail_Handler,
		},
		{
			MethodName: "GetMarketTrades",
			Handler:    _Marketcenter_GetMarketTrades_Handler,
		},
		{
			MethodName: "GetUserPositions",
			Handler:    _Marketcenter_GetUserPositions_Handler,
		},
		{
			MethodName: "GetUserTrades",
			Handler:    _Marketcenter_GetUserTrades_Handler,
		},
		{
			MethodName: "GetUserLatestAssetValue",
			Handler:    _Marketcenter_GetUserLatestAssetValue_Handler,
		},
		{
			MethodName: "SearchMarket",
			Handler:    _Marketcenter_SearchMarket_Handler,
		},
		{
			MethodName: "GetUserAssetHistory",
			Handler:    _Marketcenter_GetUserAssetHistory_Handler,
		},
		{
			MethodName: "GetMarketOptionPriceHistory",
			Handler:    _Marketcenter_GetMarketOptionPriceHistory_Handler,
		},
		{
			MethodName: "GetMarketTags",
			Handler:    _Marketcenter_GetMarketTags_Handler,
		},
		{
			MethodName: "GetMarketCategories",
			Handler:    _Marketcenter_GetMarketCategories_Handler,
		},
		{
			MethodName: "GetMarketsAndOptionsInfo",
			Handler:    _Marketcenter_GetMarketsAndOptionsInfo_Handler,
		},
		{
			MethodName: "BatchGetMarketUsersPositions",
			Handler:    _Marketcenter_BatchGetMarketUsersPositions_Handler,
		},
		{
			MethodName: "GetMarketsAndOptionsForBlockListener",
			Handler:    _Marketcenter_GetMarketsAndOptionsForBlockListener_Handler,
		},
		{
			MethodName: "CreateMarketsAndOptions",
			Handler:    _Marketcenter_CreateMarketsAndOptions_Handler,
		},
		{
			MethodName: "ProcessMarketDepositOrWithdrawEvent",
			Handler:    _Marketcenter_ProcessMarketDepositOrWithdrawEvent_Handler,
		},
		{
			MethodName: "ProcessMarketSwapEvent",
			Handler:    _Marketcenter_ProcessMarketSwapEvent_Handler,
		},
		{
			MethodName: "ProcessMarketClaimResultEvent",
			Handler:    _Marketcenter_ProcessMarketClaimResultEvent_Handler,
		},
		{
			MethodName: "ProcessMarketSettingEvent",
			Handler:    _Marketcenter_ProcessMarketSettingEvent_Handler,
		},
		{
			MethodName: "ProcessMarketAssertDisputedEvent",
			Handler:    _Marketcenter_ProcessMarketAssertDisputedEvent_Handler,
		},
		{
			MethodName: "ProcessMarketAssertionResolvedEvent",
			Handler:    _Marketcenter_ProcessMarketAssertionResolvedEvent_Handler,
		},
		{
			MethodName: "UpdateUserBaseTokenBalance",
			Handler:    _Marketcenter_UpdateUserBaseTokenBalance_Handler,
		},
		{
			MethodName: "BatchUpdateOptionPrice",
			Handler:    _Marketcenter_BatchUpdateOptionPrice_Handler,
		},
		{
			MethodName: "UpdateMarketStatus",
			Handler:    _Marketcenter_UpdateMarketStatus_Handler,
		},
		{
			MethodName: "UpdateMarketInfo",
			Handler:    _Marketcenter_UpdateMarketInfo_Handler,
		},
		{
			MethodName: "GetUserTransactions",
			Handler:    _Marketcenter_GetUserTransactions_Handler,
		},
		{
			MethodName: "GetBanners",
			Handler:    _Marketcenter_GetBanners_Handler,
		},
		{
			MethodName: "GetSections",
			Handler:    _Marketcenter_GetSections_Handler,
		},
		{
			MethodName: "GetLeaderboard",
			Handler:    _Marketcenter_GetLeaderboard_Handler,
		},
		{
			MethodName: "GetQuestionDetail",
			Handler:    _Marketcenter_GetQuestionDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market-service/marketcenter/v1/marketcenter.proto",
}
