// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: market-service/usercenter/v1/usercenter.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Usercenter_CreateUser_FullMethodName                     = "/usercenter.v1.Usercenter/CreateUser"
	Usercenter_GetUserInfo_FullMethodName                    = "/usercenter.v1.Usercenter/GetUserInfo"
	Usercenter_GetUsersInfoByAddresses_FullMethodName        = "/usercenter.v1.Usercenter/GetUsersInfoByAddresses"
	Usercenter_GetUserInfosByUids_FullMethodName             = "/usercenter.v1.Usercenter/GetUserInfosByUids"
	Usercenter_SearchUser_FullMethodName                     = "/usercenter.v1.Usercenter/SearchUser"
	Usercenter_SetUserInfo_FullMethodName                    = "/usercenter.v1.Usercenter/SetUserInfo"
	Usercenter_GetInviteUserList_FullMethodName              = "/usercenter.v1.Usercenter/GetInviteUserList"
	Usercenter_PublishPost_FullMethodName                    = "/usercenter.v1.Usercenter/PublishPost"
	Usercenter_PublishComment_FullMethodName                 = "/usercenter.v1.Usercenter/PublishComment"
	Usercenter_UpdateLikeContentStatus_FullMethodName        = "/usercenter.v1.Usercenter/UpdateLikeContentStatus"
	Usercenter_UpdateFollowStatus_FullMethodName             = "/usercenter.v1.Usercenter/UpdateFollowStatus"
	Usercenter_UploadFileToBizBucketS3_FullMethodName        = "/usercenter.v1.Usercenter/UploadFileToBizBucketS3"
	Usercenter_DownloadFileFromBizBucketS3_FullMethodName    = "/usercenter.v1.Usercenter/DownloadFileFromBizBucketS3"
	Usercenter_GetMarketPostsAndPublishers_FullMethodName    = "/usercenter.v1.Usercenter/GetMarketPostsAndPublishers"
	Usercenter_BatchGetMarketPostAndPublisher_FullMethodName = "/usercenter.v1.Usercenter/BatchGetMarketPostAndPublisher"
	Usercenter_GetComments_FullMethodName                    = "/usercenter.v1.Usercenter/GetComments"
	Usercenter_BatchGetCommentReplysAndUsers_FullMethodName  = "/usercenter.v1.Usercenter/BatchGetCommentReplysAndUsers"
	Usercenter_GetUserNotifications_FullMethodName           = "/usercenter.v1.Usercenter/GetUserNotifications"
	Usercenter_MarkNotificationsAsRead_FullMethodName        = "/usercenter.v1.Usercenter/MarkNotificationsAsRead"
	Usercenter_GetTasks_FullMethodName                       = "/usercenter.v1.Usercenter/GetTasks"
	Usercenter_ClaimTaskReward_FullMethodName                = "/usercenter.v1.Usercenter/ClaimTaskReward"
	Usercenter_TaskDone_FullMethodName                       = "/usercenter.v1.Usercenter/TaskDone"
)

// UsercenterClient is the client API for Usercenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsercenterClient interface {
	// 用户注册
	// 通过邮箱、地址等信息创建新用户
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error)
	// 获取用户信息
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoReply, error)
	GetUsersInfoByAddresses(ctx context.Context, in *GetUsersInfoByAddressesRequest, opts ...grpc.CallOption) (*GetUsersInfoByAddressesReply, error)
	GetUserInfosByUids(ctx context.Context, in *GetUserInfosByUidsRequest, opts ...grpc.CallOption) (*GetUserInfosByUidsReply, error)
	SearchUser(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error)
	// 设置用户信息
	// 更新用户的名称、头像、描述等基本信息
	SetUserInfo(ctx context.Context, in *SetUserInfoRequest, opts ...grpc.CallOption) (*SetUserInfoReply, error)
	GetInviteUserList(ctx context.Context, in *GetInviteUserListRequest, opts ...grpc.CallOption) (*GetInviteUserListReply, error)
	// 发布帖子
	PublishPost(ctx context.Context, in *PublishPostRequest, opts ...grpc.CallOption) (*PublishPostReply, error)
	// 发布评论
	PublishComment(ctx context.Context, in *PublishCommentRequest, opts ...grpc.CallOption) (*PublishCommentReply, error)
	// 更新点赞状态
	UpdateLikeContentStatus(ctx context.Context, in *UpdateLikeContentStatusRequest, opts ...grpc.CallOption) (*UpdateLikeContentStatusReply, error)
	// 更新关注状态
	UpdateFollowStatus(ctx context.Context, in *UpdateFollowStatusRequest, opts ...grpc.CallOption) (*UpdateFollowStatusReply, error)
	UploadFileToBizBucketS3(ctx context.Context, in *UploadFileToBizBucketS3Request, opts ...grpc.CallOption) (*UploadFileToBizBucketS3Reply, error)
	DownloadFileFromBizBucketS3(ctx context.Context, in *DownloadFileFromBizBucketS3Request, opts ...grpc.CallOption) (*DownloadFileFromBizBucketS3Reply, error)
	GetMarketPostsAndPublishers(ctx context.Context, in *GetMarketPostsAndPublishersRequest, opts ...grpc.CallOption) (*GetMarketPostsAndPublishersResponse, error)
	// 批量获取多个市场的一个帖子和发帖人信息
	BatchGetMarketPostAndPublisher(ctx context.Context, in *BatchGetMarketPostAndPublisherRequest, opts ...grpc.CallOption) (*BatchGetMarketPostAndPublisherResponse, error)
	GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error)
	// 批量查询多个根评论的前几条回复
	BatchGetCommentReplysAndUsers(ctx context.Context, in *BatchGetCommentReplysAndUsersRequest, opts ...grpc.CallOption) (*BatchGetCommentReplysAndUsersResponse, error)
	GetUserNotifications(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*GetUserNotificationsResponse, error)
	MarkNotificationsAsRead(ctx context.Context, in *MarkNotificationsAsReadRequest, opts ...grpc.CallOption) (*MarkNotificationsAsReadResponse, error)
	GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksResponse, error)
	ClaimTaskReward(ctx context.Context, in *ClaimTaskRewardRequest, opts ...grpc.CallOption) (*ClaimTaskRewardResponse, error)
	TaskDone(ctx context.Context, in *TaskDoneRequest, opts ...grpc.CallOption) (*TaskDoneResponse, error)
}

type usercenterClient struct {
	cc grpc.ClientConnInterface
}

func NewUsercenterClient(cc grpc.ClientConnInterface) UsercenterClient {
	return &usercenterClient{cc}
}

func (c *usercenterClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error) {
	out := new(CreateUserReply)
	err := c.cc.Invoke(ctx, Usercenter_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoReply, error) {
	out := new(GetUserInfoReply)
	err := c.cc.Invoke(ctx, Usercenter_GetUserInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) GetUsersInfoByAddresses(ctx context.Context, in *GetUsersInfoByAddressesRequest, opts ...grpc.CallOption) (*GetUsersInfoByAddressesReply, error) {
	out := new(GetUsersInfoByAddressesReply)
	err := c.cc.Invoke(ctx, Usercenter_GetUsersInfoByAddresses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) GetUserInfosByUids(ctx context.Context, in *GetUserInfosByUidsRequest, opts ...grpc.CallOption) (*GetUserInfosByUidsReply, error) {
	out := new(GetUserInfosByUidsReply)
	err := c.cc.Invoke(ctx, Usercenter_GetUserInfosByUids_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) SearchUser(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error) {
	out := new(SearchUserResponse)
	err := c.cc.Invoke(ctx, Usercenter_SearchUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) SetUserInfo(ctx context.Context, in *SetUserInfoRequest, opts ...grpc.CallOption) (*SetUserInfoReply, error) {
	out := new(SetUserInfoReply)
	err := c.cc.Invoke(ctx, Usercenter_SetUserInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) GetInviteUserList(ctx context.Context, in *GetInviteUserListRequest, opts ...grpc.CallOption) (*GetInviteUserListReply, error) {
	out := new(GetInviteUserListReply)
	err := c.cc.Invoke(ctx, Usercenter_GetInviteUserList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) PublishPost(ctx context.Context, in *PublishPostRequest, opts ...grpc.CallOption) (*PublishPostReply, error) {
	out := new(PublishPostReply)
	err := c.cc.Invoke(ctx, Usercenter_PublishPost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) PublishComment(ctx context.Context, in *PublishCommentRequest, opts ...grpc.CallOption) (*PublishCommentReply, error) {
	out := new(PublishCommentReply)
	err := c.cc.Invoke(ctx, Usercenter_PublishComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) UpdateLikeContentStatus(ctx context.Context, in *UpdateLikeContentStatusRequest, opts ...grpc.CallOption) (*UpdateLikeContentStatusReply, error) {
	out := new(UpdateLikeContentStatusReply)
	err := c.cc.Invoke(ctx, Usercenter_UpdateLikeContentStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) UpdateFollowStatus(ctx context.Context, in *UpdateFollowStatusRequest, opts ...grpc.CallOption) (*UpdateFollowStatusReply, error) {
	out := new(UpdateFollowStatusReply)
	err := c.cc.Invoke(ctx, Usercenter_UpdateFollowStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) UploadFileToBizBucketS3(ctx context.Context, in *UploadFileToBizBucketS3Request, opts ...grpc.CallOption) (*UploadFileToBizBucketS3Reply, error) {
	out := new(UploadFileToBizBucketS3Reply)
	err := c.cc.Invoke(ctx, Usercenter_UploadFileToBizBucketS3_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) DownloadFileFromBizBucketS3(ctx context.Context, in *DownloadFileFromBizBucketS3Request, opts ...grpc.CallOption) (*DownloadFileFromBizBucketS3Reply, error) {
	out := new(DownloadFileFromBizBucketS3Reply)
	err := c.cc.Invoke(ctx, Usercenter_DownloadFileFromBizBucketS3_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) GetMarketPostsAndPublishers(ctx context.Context, in *GetMarketPostsAndPublishersRequest, opts ...grpc.CallOption) (*GetMarketPostsAndPublishersResponse, error) {
	out := new(GetMarketPostsAndPublishersResponse)
	err := c.cc.Invoke(ctx, Usercenter_GetMarketPostsAndPublishers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) BatchGetMarketPostAndPublisher(ctx context.Context, in *BatchGetMarketPostAndPublisherRequest, opts ...grpc.CallOption) (*BatchGetMarketPostAndPublisherResponse, error) {
	out := new(BatchGetMarketPostAndPublisherResponse)
	err := c.cc.Invoke(ctx, Usercenter_BatchGetMarketPostAndPublisher_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error) {
	out := new(GetCommentsResponse)
	err := c.cc.Invoke(ctx, Usercenter_GetComments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) BatchGetCommentReplysAndUsers(ctx context.Context, in *BatchGetCommentReplysAndUsersRequest, opts ...grpc.CallOption) (*BatchGetCommentReplysAndUsersResponse, error) {
	out := new(BatchGetCommentReplysAndUsersResponse)
	err := c.cc.Invoke(ctx, Usercenter_BatchGetCommentReplysAndUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) GetUserNotifications(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*GetUserNotificationsResponse, error) {
	out := new(GetUserNotificationsResponse)
	err := c.cc.Invoke(ctx, Usercenter_GetUserNotifications_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) MarkNotificationsAsRead(ctx context.Context, in *MarkNotificationsAsReadRequest, opts ...grpc.CallOption) (*MarkNotificationsAsReadResponse, error) {
	out := new(MarkNotificationsAsReadResponse)
	err := c.cc.Invoke(ctx, Usercenter_MarkNotificationsAsRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksResponse, error) {
	out := new(GetTasksResponse)
	err := c.cc.Invoke(ctx, Usercenter_GetTasks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) ClaimTaskReward(ctx context.Context, in *ClaimTaskRewardRequest, opts ...grpc.CallOption) (*ClaimTaskRewardResponse, error) {
	out := new(ClaimTaskRewardResponse)
	err := c.cc.Invoke(ctx, Usercenter_ClaimTaskReward_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) TaskDone(ctx context.Context, in *TaskDoneRequest, opts ...grpc.CallOption) (*TaskDoneResponse, error) {
	out := new(TaskDoneResponse)
	err := c.cc.Invoke(ctx, Usercenter_TaskDone_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsercenterServer is the server API for Usercenter service.
// All implementations must embed UnimplementedUsercenterServer
// for forward compatibility
type UsercenterServer interface {
	// 用户注册
	// 通过邮箱、地址等信息创建新用户
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserReply, error)
	// 获取用户信息
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoReply, error)
	GetUsersInfoByAddresses(context.Context, *GetUsersInfoByAddressesRequest) (*GetUsersInfoByAddressesReply, error)
	GetUserInfosByUids(context.Context, *GetUserInfosByUidsRequest) (*GetUserInfosByUidsReply, error)
	SearchUser(context.Context, *SearchUserRequest) (*SearchUserResponse, error)
	// 设置用户信息
	// 更新用户的名称、头像、描述等基本信息
	SetUserInfo(context.Context, *SetUserInfoRequest) (*SetUserInfoReply, error)
	GetInviteUserList(context.Context, *GetInviteUserListRequest) (*GetInviteUserListReply, error)
	// 发布帖子
	PublishPost(context.Context, *PublishPostRequest) (*PublishPostReply, error)
	// 发布评论
	PublishComment(context.Context, *PublishCommentRequest) (*PublishCommentReply, error)
	// 更新点赞状态
	UpdateLikeContentStatus(context.Context, *UpdateLikeContentStatusRequest) (*UpdateLikeContentStatusReply, error)
	// 更新关注状态
	UpdateFollowStatus(context.Context, *UpdateFollowStatusRequest) (*UpdateFollowStatusReply, error)
	UploadFileToBizBucketS3(context.Context, *UploadFileToBizBucketS3Request) (*UploadFileToBizBucketS3Reply, error)
	DownloadFileFromBizBucketS3(context.Context, *DownloadFileFromBizBucketS3Request) (*DownloadFileFromBizBucketS3Reply, error)
	GetMarketPostsAndPublishers(context.Context, *GetMarketPostsAndPublishersRequest) (*GetMarketPostsAndPublishersResponse, error)
	// 批量获取多个市场的一个帖子和发帖人信息
	BatchGetMarketPostAndPublisher(context.Context, *BatchGetMarketPostAndPublisherRequest) (*BatchGetMarketPostAndPublisherResponse, error)
	GetComments(context.Context, *GetCommentsRequest) (*GetCommentsResponse, error)
	// 批量查询多个根评论的前几条回复
	BatchGetCommentReplysAndUsers(context.Context, *BatchGetCommentReplysAndUsersRequest) (*BatchGetCommentReplysAndUsersResponse, error)
	GetUserNotifications(context.Context, *GetUserNotificationsRequest) (*GetUserNotificationsResponse, error)
	MarkNotificationsAsRead(context.Context, *MarkNotificationsAsReadRequest) (*MarkNotificationsAsReadResponse, error)
	GetTasks(context.Context, *GetTasksRequest) (*GetTasksResponse, error)
	ClaimTaskReward(context.Context, *ClaimTaskRewardRequest) (*ClaimTaskRewardResponse, error)
	TaskDone(context.Context, *TaskDoneRequest) (*TaskDoneResponse, error)
	mustEmbedUnimplementedUsercenterServer()
}

// UnimplementedUsercenterServer must be embedded to have forward compatible implementations.
type UnimplementedUsercenterServer struct {
}

func (UnimplementedUsercenterServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUsercenterServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUsercenterServer) GetUsersInfoByAddresses(context.Context, *GetUsersInfoByAddressesRequest) (*GetUsersInfoByAddressesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersInfoByAddresses not implemented")
}
func (UnimplementedUsercenterServer) GetUserInfosByUids(context.Context, *GetUserInfosByUidsRequest) (*GetUserInfosByUidsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfosByUids not implemented")
}
func (UnimplementedUsercenterServer) SearchUser(context.Context, *SearchUserRequest) (*SearchUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUser not implemented")
}
func (UnimplementedUsercenterServer) SetUserInfo(context.Context, *SetUserInfoRequest) (*SetUserInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserInfo not implemented")
}
func (UnimplementedUsercenterServer) GetInviteUserList(context.Context, *GetInviteUserListRequest) (*GetInviteUserListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInviteUserList not implemented")
}
func (UnimplementedUsercenterServer) PublishPost(context.Context, *PublishPostRequest) (*PublishPostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishPost not implemented")
}
func (UnimplementedUsercenterServer) PublishComment(context.Context, *PublishCommentRequest) (*PublishCommentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishComment not implemented")
}
func (UnimplementedUsercenterServer) UpdateLikeContentStatus(context.Context, *UpdateLikeContentStatusRequest) (*UpdateLikeContentStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLikeContentStatus not implemented")
}
func (UnimplementedUsercenterServer) UpdateFollowStatus(context.Context, *UpdateFollowStatusRequest) (*UpdateFollowStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFollowStatus not implemented")
}
func (UnimplementedUsercenterServer) UploadFileToBizBucketS3(context.Context, *UploadFileToBizBucketS3Request) (*UploadFileToBizBucketS3Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFileToBizBucketS3 not implemented")
}
func (UnimplementedUsercenterServer) DownloadFileFromBizBucketS3(context.Context, *DownloadFileFromBizBucketS3Request) (*DownloadFileFromBizBucketS3Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadFileFromBizBucketS3 not implemented")
}
func (UnimplementedUsercenterServer) GetMarketPostsAndPublishers(context.Context, *GetMarketPostsAndPublishersRequest) (*GetMarketPostsAndPublishersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketPostsAndPublishers not implemented")
}
func (UnimplementedUsercenterServer) BatchGetMarketPostAndPublisher(context.Context, *BatchGetMarketPostAndPublisherRequest) (*BatchGetMarketPostAndPublisherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetMarketPostAndPublisher not implemented")
}
func (UnimplementedUsercenterServer) GetComments(context.Context, *GetCommentsRequest) (*GetCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComments not implemented")
}
func (UnimplementedUsercenterServer) BatchGetCommentReplysAndUsers(context.Context, *BatchGetCommentReplysAndUsersRequest) (*BatchGetCommentReplysAndUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetCommentReplysAndUsers not implemented")
}
func (UnimplementedUsercenterServer) GetUserNotifications(context.Context, *GetUserNotificationsRequest) (*GetUserNotificationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserNotifications not implemented")
}
func (UnimplementedUsercenterServer) MarkNotificationsAsRead(context.Context, *MarkNotificationsAsReadRequest) (*MarkNotificationsAsReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkNotificationsAsRead not implemented")
}
func (UnimplementedUsercenterServer) GetTasks(context.Context, *GetTasksRequest) (*GetTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasks not implemented")
}
func (UnimplementedUsercenterServer) ClaimTaskReward(context.Context, *ClaimTaskRewardRequest) (*ClaimTaskRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimTaskReward not implemented")
}
func (UnimplementedUsercenterServer) TaskDone(context.Context, *TaskDoneRequest) (*TaskDoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskDone not implemented")
}
func (UnimplementedUsercenterServer) mustEmbedUnimplementedUsercenterServer() {}

// UnsafeUsercenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsercenterServer will
// result in compilation errors.
type UnsafeUsercenterServer interface {
	mustEmbedUnimplementedUsercenterServer()
}

func RegisterUsercenterServer(s grpc.ServiceRegistrar, srv UsercenterServer) {
	s.RegisterService(&Usercenter_ServiceDesc, srv)
}

func _Usercenter_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_GetUsersInfoByAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersInfoByAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).GetUsersInfoByAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_GetUsersInfoByAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).GetUsersInfoByAddresses(ctx, req.(*GetUsersInfoByAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_GetUserInfosByUids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfosByUidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).GetUserInfosByUids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_GetUserInfosByUids_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).GetUserInfosByUids(ctx, req.(*GetUserInfosByUidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_SearchUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).SearchUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_SearchUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).SearchUser(ctx, req.(*SearchUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_SetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).SetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_SetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).SetUserInfo(ctx, req.(*SetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_GetInviteUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInviteUserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).GetInviteUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_GetInviteUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).GetInviteUserList(ctx, req.(*GetInviteUserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_PublishPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).PublishPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_PublishPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).PublishPost(ctx, req.(*PublishPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_PublishComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).PublishComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_PublishComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).PublishComment(ctx, req.(*PublishCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_UpdateLikeContentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLikeContentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).UpdateLikeContentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_UpdateLikeContentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).UpdateLikeContentStatus(ctx, req.(*UpdateLikeContentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_UpdateFollowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFollowStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).UpdateFollowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_UpdateFollowStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).UpdateFollowStatus(ctx, req.(*UpdateFollowStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_UploadFileToBizBucketS3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileToBizBucketS3Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).UploadFileToBizBucketS3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_UploadFileToBizBucketS3_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).UploadFileToBizBucketS3(ctx, req.(*UploadFileToBizBucketS3Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_DownloadFileFromBizBucketS3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadFileFromBizBucketS3Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).DownloadFileFromBizBucketS3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_DownloadFileFromBizBucketS3_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).DownloadFileFromBizBucketS3(ctx, req.(*DownloadFileFromBizBucketS3Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_GetMarketPostsAndPublishers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketPostsAndPublishersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).GetMarketPostsAndPublishers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_GetMarketPostsAndPublishers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).GetMarketPostsAndPublishers(ctx, req.(*GetMarketPostsAndPublishersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_BatchGetMarketPostAndPublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetMarketPostAndPublisherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).BatchGetMarketPostAndPublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_BatchGetMarketPostAndPublisher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).BatchGetMarketPostAndPublisher(ctx, req.(*BatchGetMarketPostAndPublisherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_GetComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).GetComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_GetComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).GetComments(ctx, req.(*GetCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_BatchGetCommentReplysAndUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetCommentReplysAndUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).BatchGetCommentReplysAndUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_BatchGetCommentReplysAndUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).BatchGetCommentReplysAndUsers(ctx, req.(*BatchGetCommentReplysAndUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_GetUserNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).GetUserNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_GetUserNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).GetUserNotifications(ctx, req.(*GetUserNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_MarkNotificationsAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationsAsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).MarkNotificationsAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_MarkNotificationsAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).MarkNotificationsAsRead(ctx, req.(*MarkNotificationsAsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_GetTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).GetTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_GetTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).GetTasks(ctx, req.(*GetTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_ClaimTaskReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimTaskRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).ClaimTaskReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_ClaimTaskReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).ClaimTaskReward(ctx, req.(*ClaimTaskRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_TaskDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).TaskDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_TaskDone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).TaskDone(ctx, req.(*TaskDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Usercenter_ServiceDesc is the grpc.ServiceDesc for Usercenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Usercenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usercenter.v1.Usercenter",
	HandlerType: (*UsercenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Usercenter_CreateUser_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _Usercenter_GetUserInfo_Handler,
		},
		{
			MethodName: "GetUsersInfoByAddresses",
			Handler:    _Usercenter_GetUsersInfoByAddresses_Handler,
		},
		{
			MethodName: "GetUserInfosByUids",
			Handler:    _Usercenter_GetUserInfosByUids_Handler,
		},
		{
			MethodName: "SearchUser",
			Handler:    _Usercenter_SearchUser_Handler,
		},
		{
			MethodName: "SetUserInfo",
			Handler:    _Usercenter_SetUserInfo_Handler,
		},
		{
			MethodName: "GetInviteUserList",
			Handler:    _Usercenter_GetInviteUserList_Handler,
		},
		{
			MethodName: "PublishPost",
			Handler:    _Usercenter_PublishPost_Handler,
		},
		{
			MethodName: "PublishComment",
			Handler:    _Usercenter_PublishComment_Handler,
		},
		{
			MethodName: "UpdateLikeContentStatus",
			Handler:    _Usercenter_UpdateLikeContentStatus_Handler,
		},
		{
			MethodName: "UpdateFollowStatus",
			Handler:    _Usercenter_UpdateFollowStatus_Handler,
		},
		{
			MethodName: "UploadFileToBizBucketS3",
			Handler:    _Usercenter_UploadFileToBizBucketS3_Handler,
		},
		{
			MethodName: "DownloadFileFromBizBucketS3",
			Handler:    _Usercenter_DownloadFileFromBizBucketS3_Handler,
		},
		{
			MethodName: "GetMarketPostsAndPublishers",
			Handler:    _Usercenter_GetMarketPostsAndPublishers_Handler,
		},
		{
			MethodName: "BatchGetMarketPostAndPublisher",
			Handler:    _Usercenter_BatchGetMarketPostAndPublisher_Handler,
		},
		{
			MethodName: "GetComments",
			Handler:    _Usercenter_GetComments_Handler,
		},
		{
			MethodName: "BatchGetCommentReplysAndUsers",
			Handler:    _Usercenter_BatchGetCommentReplysAndUsers_Handler,
		},
		{
			MethodName: "GetUserNotifications",
			Handler:    _Usercenter_GetUserNotifications_Handler,
		},
		{
			MethodName: "MarkNotificationsAsRead",
			Handler:    _Usercenter_MarkNotificationsAsRead_Handler,
		},
		{
			MethodName: "GetTasks",
			Handler:    _Usercenter_GetTasks_Handler,
		},
		{
			MethodName: "ClaimTaskReward",
			Handler:    _Usercenter_ClaimTaskReward_Handler,
		},
		{
			MethodName: "TaskDone",
			Handler:    _Usercenter_TaskDone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market-service/usercenter/v1/usercenter.proto",
}
