// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"block-listener/internal/biz"
	"block-listener/internal/conf"
	"block-listener/internal/contract"
	"block-listener/internal/data"
	"block-listener/internal/server"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp 通过依赖注入组装应用
func wireApp(bootstrap *conf.Bootstrap, custom *conf.Custom, logger log.Logger) (*kratos.App, func(), error) {
	dbClient := data.NewDbClient(bootstrap, logger)
	contractContract, err := contract.NewContract(logger)
	if err != nil {
		return nil, nil, err
	}
	arbClient, err := data.NewArbClient(bootstrap, logger, contractContract)
	if err != nil {
		return nil, nil, err
	}
	redisClient, err := data.NewRedisClient(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	rpcClient, err := data.NewRpcClient(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	blockScanner := biz.NewBlockScanner(dbClient, arbClient, redisClient, rpcClient, bootstrap, logger)
	blockScannerServer := server.NewBlockScannerServer(blockScanner, logger)
	eventProcessor := biz.NewEventProcessor(dbClient, arbClient, redisClient, rpcClient, bootstrap, logger)
	eventProcessorServer := server.NewEventProcessorServer(eventProcessor, logger)
	queryPriceProcessor := biz.NewQueryPriceProcessor(dbClient, arbClient, redisClient, rpcClient, bootstrap, logger)
	schedulerServer := server.NewSchedulerServer(logger, queryPriceProcessor, redisClient)
	app := newApp(blockScannerServer, eventProcessorServer, schedulerServer, logger)
	return app, func() {
	}, nil
}
