// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	asset2 "market-service/internal/biz/asset"
	community2 "market-service/internal/biz/community"
	market2 "market-service/internal/biz/market"
	task2 "market-service/internal/biz/task"
	user2 "market-service/internal/biz/user"
	"market-service/internal/conf"
	"market-service/internal/crontask"
	"market-service/internal/data/asset"
	"market-service/internal/data/base"
	"market-service/internal/data/community"
	"market-service/internal/data/market"
	"market-service/internal/data/task"
	"market-service/internal/data/user"
	"market-service/internal/redis_stream_consumer"
	"market-service/internal/server"
	"market-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, custom *conf.Custom, logger log.Logger) (*kratos.App, func(), error) {
	baseData, cleanup, err := base.NewData(data, logger)
	if err != nil {
		return nil, nil, err
	}
	usercenterInfra := base.NewUsercenterInfra(baseData, logger)
	userRepoInterface := user.NewUserRepo(usercenterInfra)
	userHandler := user2.NewUserHandler(userRepoInterface, logger, data)
	marketcenterInfra := base.NewMarketcenterInfra(baseData, logger)
	marketRepoInterface := market.NewMarketRepo(marketcenterInfra)
	eventRepoInterface := market.NewEventRepo(marketcenterInfra)
	marketHandler := market2.NewMarketHandler(marketRepoInterface, eventRepoInterface, logger, custom)
	taskRepoInterface := task.NewTaskRepo(usercenterInfra)
	taskHandler := task2.NewTaskHandler(taskRepoInterface, logger, custom)
	assetRepoInterface := asset.NewAssetRepo(marketcenterInfra)
	assetHandler := asset2.NewAssetHandler(userRepoInterface, taskRepoInterface, assetRepoInterface, marketRepoInterface, custom, logger)
	communityRepoInterface := community.NewCommunityRepo(usercenterInfra)
	communityHandler := community2.NewCommunityHandler(communityRepoInterface, logger)
	marketService := service.NewMarketService(userHandler, marketHandler, taskHandler, assetHandler, communityHandler, custom, logger)
	grpcServer := server.NewGRPCServer(confServer, marketService, logger)
	updateUserAssetProcessor := crontask.NewUpdateUserAssetProcessor(logger, userHandler, marketHandler, assetHandler, custom)
	schedulerServer := server.NewSchedulerServer(logger, updateUserAssetProcessor, usercenterInfra)
	mintPointsHandler := redis_stream_consumer.NewMintPointsHandler(usercenterInfra, logger, userHandler, assetHandler, marketHandler, taskHandler, custom)
	verifyTaskHandler := redis_stream_consumer.NewVerifyTaskHandler(usercenterInfra, logger, taskHandler, userHandler, assetHandler, marketHandler, custom)
	pnlAllTimeLeaderboardHandler := redis_stream_consumer.NewPnlAllTimeLeaderboardHandler(usercenterInfra, logger, userHandler, assetHandler, marketHandler, custom)
	pnlDailyLeaderboardHandler := redis_stream_consumer.NewPnlDailyLeaderboardHandler(logger, userHandler, assetHandler, marketHandler, custom, usercenterInfra)
	pnlMonthlyLeaderboardHandler := redis_stream_consumer.NewPnlMonthlyLeaderboardHandler(logger, userHandler, assetHandler, marketHandler, custom, usercenterInfra)
	pnlWeeklyLeaderboardHandler := redis_stream_consumer.NewPnlWeeklyLeaderboardHandler(logger, userHandler, assetHandler, marketHandler, custom, usercenterInfra)
	tradesAllTimeLeaderboardHandler := redis_stream_consumer.NewTradesAllTimeLeaderboardHandler(logger, userHandler, assetHandler, marketHandler, custom, usercenterInfra)
	tradesDailyLeaderboardHandler := redis_stream_consumer.NewTradesDailyLeaderboardHandler(logger, userHandler, assetHandler, marketHandler, custom, usercenterInfra)
	tradesMonthlyLeaderboardHandler := redis_stream_consumer.NewTradesMonthlyLeaderboardHandler(logger, userHandler, assetHandler, marketHandler, custom, usercenterInfra)
	tradesWeeklyLeaderboardHandler := redis_stream_consumer.NewTradesWeeklyLeaderboardHandler(logger, userHandler, assetHandler, marketHandler, custom, usercenterInfra)
	volumeAllTimeLeaderboardHandler := redis_stream_consumer.NewVolumeAllTimeLeaderboardHandler(logger, userHandler, assetHandler, marketHandler, custom, usercenterInfra)
	volumeDailyLeaderboardHandler := redis_stream_consumer.NewVolumeDailyLeaderboardHandler(logger, userHandler, assetHandler, marketHandler, custom, usercenterInfra)
	volumeMonthlyLeaderboardHandler := redis_stream_consumer.NewVolumeMonthlyLeaderboardHandler(logger, userHandler, assetHandler, marketHandler, custom, usercenterInfra)
	volumeWeeklyLeaderboardHandler := redis_stream_consumer.NewVolumeWeeklyLeaderboardHandler(logger, userHandler, assetHandler, marketHandler, custom, usercenterInfra)
	consumerServer := server.NewConsumerServer(logger, mintPointsHandler, verifyTaskHandler, pnlAllTimeLeaderboardHandler, pnlDailyLeaderboardHandler, pnlMonthlyLeaderboardHandler, pnlWeeklyLeaderboardHandler, tradesAllTimeLeaderboardHandler, tradesDailyLeaderboardHandler, tradesMonthlyLeaderboardHandler, tradesWeeklyLeaderboardHandler, volumeAllTimeLeaderboardHandler, volumeDailyLeaderboardHandler, volumeMonthlyLeaderboardHandler, volumeWeeklyLeaderboardHandler, marketcenterInfra)
	app := newApp(logger, grpcServer, schedulerServer, consumerServer)
	return app, func() {
		cleanup()
	}, nil
}
